### ISSUE TITLE
How to switch to a different sync service?

### ISSUE THREAD

**Issue by orschiro** [xBrowserSync/App#1]
Hello, 

Thank you for your promising extension. :-)

I wanted to sync my bookmarks but I seem to have too many. 

How do I proceed?

> switch to a different xBrowserSync service that allows for larger syncs.

![image](https://cloud.githubusercontent.com/assets/170947/20840627/2a0ebf2e-b8b1-11e6-8fad-499e8b9f714d.png)

**Comment by nero120** [comment]
Hi and thanks for using xBrowserSync!

As this extension is pretty new and doesn't have a large userbase there's currently only one xBrowserSync service (the default one, [api.xbrowsersync.org](https://api.xbrowsersync.org)), so unless you'd like to [set up your own](https://github.com/xBrowserSync/Api) you'll have to use the default one.

The default service has a fair usage policy that sets a limit on the amount of (encrypted) data you can sync. As there is currently pretty light usage I can increase it, but it would be good to know how much data you are trying to sync. To figure this out, follow these steps:

1. Open xBrowserSync, go to the Settings panel and export your bookmarks to save them to a text file.
2. Open the text file and copy all of the text.
3. Go to [this](https://www.browserling.com/tools/aes-encrypt) website and paste your exported bookmarks text into the textarea, type your sync password (or similar) into the password field and click the Encrypt button.
4. Copy the encrypted value and then go to [this](https://mothereff.in/byte-counter) website. Paste the encrypted text into the textarea and take note of how many bytes it is.

If you can reply here with the value of bytes you got I'll see if I can increase the sync limit to accommodate you. :)

**Comment by orschiro** [comment]
Thank you for your help. :-)

If I followed the process correctly, then this is the result:

![image](https://cloud.githubusercontent.com/assets/170947/20845185/1eb14670-b8c4-11e6-8018-ccf607279b75.png)

I hope this is not too much.

**Comment by nero120** [comment]
Ah that's pretty big dude, I just don't have enough storage space to let people sync that much data. The platform that I'm running the xBrowserSync service on ([Red Hat's OpenShift](https://www.openshift.com/)) only gives you 1GB of storage which means if I event set the max sync size to only 500kB then still only around 2000 people can use the extension.

I wanted to make this extension free and open source which means it's very limited on storage space as it's dependent on using a free platform to host it. I was hoping that as more people start to use it they'd run their own services (i.e. install it or their own web server or sign up to something like [OpenShift](https://www.openshift.com/) and install the [xBrowserSync API](https://github.com/xBrowserSync/API) on there) and potentially [make it available to others via the xBrowserSync website](https://www.xbrowsersync.org/#getinvolved), and collectively there'd be more storage available to anyone who wanted to use the extension.

Sorry I couldn't be of more help. If you're tech savvy at all and you want to set up your own xBrowserSync service (you can set any max sync size or disable it entirely) then I'm happy to help you through it.

**Comment by orschiro** [comment]
Hello Rich,

This is totally reasonable.

Let me see if I can create an exported archive and declutter myself. :-)

Thank you,

-Robert

**Comment by orschiro** [comment]
Actually, I have one idea. 

How if one could exclude folders and only sync certain bookmark folders?

**Comment by nero120** [comment]
That's possible for a future feature, however I'm literally just about to release a major update (v1.2.0) which includes many enhancements to the extension, plus future support for Firefox (once Mozilla finishes full support for the Chrome web extensions api) and will also allow me to release the Android and iOS apps imminently! It's a huge update and once it's stable I'll probably take a break from dev for xBrowserSync for a while and see how many people pick it up. There's some other projects I want to get started on, just not enough hours in the day!!

If you can declutter then I think you won't be sorry, the mobile apps are pretty sick if I do say so myself (not at all biased :) ) and would definitely recommend you check them out. They really do complete the productivity loop of having all my bookmarks with me at all times, adding new ones on the go and finding existing bookmarks easily, all whilst protecting my privacy and anonymity. Anyways, I hope you stick with xBrowserSync and sorry I couldn't be of more help.

**Comment by orschiro** [comment]
I am very glad for all your great work, thank you.

I think I am fine for now.

Good luck with your other projects. :-)
