### ISSUE TITLE
Unable to enter credentials for existing sync ID

### ISSUE THREAD

**Issue by coreagile** [xbrowsersync/app#101]
### Steps to reproduce
1. Install 1.5.0b6
2. Go to Enpass and copy Sync ID to clipboard
3. Click to open the plugin
4. Click "Already got a Sync ID?"
5. Paste Sync ID
6. Go to Enpass and copy Password to clipboard
7. Click to open the plugin

### Expected behaviour
The plugin should have remembered the Sync ID I entered and allowed me to enter my password.

### Actual behaviour
The plugin forgot the Sync ID, making it impossible for me to copy-paste both values into the plugin from my password manager.

### Client app information
**App Platform:** (Chrome, Firefox, etc) 
Firefox

**App Platform Version:** 
67.0

#### Other info
```
$ uname -a
Linux pop-os 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 19.04 \n \l
```

**Comment by nero120** [comment]
Hey @coreagile, I'll have a think about whether I want to change the current behaviour to save any input in the ID field (currently it only saves the ID once you've successfully synced), however in the meantime see [this post](https://github.com/xbrowsersync/app/issues/86#issuecomment-487276896) for a workaround.

**Comment by coreagile** [comment]
Thanks. That workaround is very painful for beginners that use a password manager.

**Comment by nero120** [comment]
@coreagile this has now been resolved, from the next release the sync ID value will be saved whenever it is updated.

**Comment by coreagile** [comment]
Thanks!!

Stephen Starkey, ACC
forgiveness | bravery | honesty | fairness | leadership | creativity
