### ISSUE TITLE
User interface - SyncID clipboard copy

### ISSUE THREAD

**Issue by danpeig** [xbrowsersync/app#102]
When the extension generates garbage sync data (folders and bookmarks repeated and mixed) the only solution I found is create another sync ID and restart the process. If I try to delete all folders it logs out the extension and when I sign in again the garbage is back.
 
In order to sync the new ID to other browsers/computers I copy/paste the huge string to somewhere else.

The problem is that is almost impossible to select and copy the ID tag string. If I, by mistake, click on that a QR-Code appears and I can't select the text. 

For future versions I recommend adding a specific button for the QR-Code (I don't know the purpose of this QR code) or another button to copy the ID to the clipboard.

**Comment by nero120** [comment]
Thanks @danpeig, good idea.
