### ISSUE TITLE
Solution: Corrupted Sync, Garbled Sync, Incomplete Sync

### ISSUE THREAD

**Issue by mohsenkhanpour** [xbrowsersync/app#103]
I had a similar problem to what others have said concerning incomplete syncs and duplicates.
I wanted to sync across 2 machines, and 4 browsers (2 Chrome, and 2 Firefox), however it would always end up getting corrupted.
What solved the issue completely for me was to disable the browser's bookmarks sync via Chrome Sync or Firefox Sync. It seems that the browsers sync the bookmarks after it is synced via Xbrowsersync.

**Comment by ipk01** [comment]
Oh boy ... good hypothesis. Will test instantly! Thanks for that idea!!!

**Comment by nero120** [comment]
It says on the first screen when you open xBrowserSync for the first time:

> As xBrowserSync modifies your local browser data, we recommend you back up your bookmarks and disable any existing browser sync services to avoid conflicts.

Please ensure you **read the help text** before using xBrowserSync to avoid issues.

**Comment by ipk01** [comment]
No more issues now. Admittedly, after re-installing a few times I did not read the help text anymore, and even now that I know I cannot find it mentioned in the FAQs. I think it is not only recommendable to turn of the inbuilt sync services but possibly mandatory. In any case ... this is great. Love it!!! Thanks for your patience with us users :-)

**Comment by nero120** [comment]
No worries at all @ipk01, glad your issues are now sorted. I will add it to the FAQs but I'll also add a warning on initial sync to disable existing sync tools just so that users don't fall foul of it in future.

**Comment by ipk01** [comment]
Great!
