### ISSUE TITLE
Extension won't install in Firefox

### ISSUE THREAD

**Issue by eCyclops** [xbrowsersync/app#104]
### Steps to reproduce
1. Try to install xBrowserSync extension

### Expected behaviour
I expect the browser extension to be loaded into FireFox

### Actual behaviour
1. If installing from the FireFox / Mozilla add-on repository (https://addons.mozilla.org/en-GB/firefox/addon/xbs/) I get the message: "Download failed. Please check your connection."
2. If trying to directly install the xpi (https://github.com/xbrowsersync/app/releases/download/v1.4.0/xbrowsersync_1.4.0.xpi) I get : "The add-on downloaded from this site could not be installed because it appears to be corrupt."

### Client app information
Firefox Quantum 66.0.3 64-bit
Linux Mint 19 Cinnamon

#### Other info
about.config xpinstall.signatures.required is set to false.

It appears to work properly if loaded as a Temporary Add-on under about:debugging

**Comment by nero120** [comment]
Suggest you check [this](https://discourse.mozilla.org/t/fixed-certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/2) post out, relating to a well known recent Firefox issue, or report your issue [here](https://github.com/mozilla/addons/issues/).
