### ISSUE TITLE
Website certificate expired, so browser extension doesn't work

### ISSUE THREAD

**Issue by ProfessorO** [xbrowsersync/app#106]
### Steps to reproduce
1. Browse to https://xbrowsersync.org

### Expected behaviour
Should see xBrowserSync home page

### Actual behaviour
Browser warns that the certificate is invalid for xbrowsersync.org, as it was issued to TRAEFIK DEFAULT CERT.

### Client app information
Have tested on current version of extension for both Chrome and Firefox on Windows 10--neither one is syncing properly.

**Comment by nero120** [comment]
Thanks @ProfessorO, root domain now redirects to www.
