### ISSUE TITLE
Dropped bookmarks in sync

### ISSUE THREAD

**Issue by servicedevice** [xbrowsersync/app#107]
### Steps to reproduce
1. Allow sync to upload on browser with change of 3 added bookmarks (Chrome, laptop)
2. Allow sync to download on second browser (Chrome, PC)
3. Check expected changes

### Expected behaviour
Tell us what should happen
All 3 bookmarks should be present on both devices

### Actual behaviour
Tell us what happens instead
Only one added bookmark makes it onto the second device--and all were from same website, made within seconds of each other. All are still present on first device, hours later (until a change on second device updates the first, and wipes out the two that remained only on first device)
### Client app information
**App Platform:** (Chrome, Firefox, etc) 
Chrome
**App Platform Version:** 
1.4.0
#### Other info
```Both devices running Windows 10
Enter any other information you think would be helpful here.
```

**Comment by servicedevice** [comment]
Incidentally, I did go back and add the missing bookmarks again, and this time they synced. But this means that I would have to always check that every change went through, or just hope for the best, neither of is a workable solution for me...

**Comment by servicedevice** [comment]
Not sure if I put all this in the right place, or if it's being read, but: I think I solved the issue--I think I a) possibly bookmarked the links too quickly together and/or b) probably closed the browser too quickly thereafter, thus not giving it enough time to sync. I was able to reproduce the behavior by repeating these factors.

**Comment by nero120** [comment]
Ok thanks for the update @servicedevice. v1.5.0 will be released shortly that should resolveany remaining sync issues/bugs.
