### ISSUE TITLE
Unable to start sync

### ISSUE THREAD

**Issue by cocox** [xbrowsersync/app#112]
Does not sync with second browser

### Steps to reproduce
1. Create new id sync from Opera
2. Sync in Firefox

### Expected behaviour
Download all chrome bookmarks

### Actual behaviour
Nothing appends

### Client app information
Opera: 62.0.3331.72
FireFox: 60.8.0esr

**Comment by nero120** [comment]
@cocox Opera is not supported yet (see #11). I'm expecting to implement Opera support in v1.6.0.
