### ISSUE TITLE
Crash on Chromium Version 76.0.3809.87

### ISSUE THREAD

**Issue by vsatmydynipnet** [xbrowsersync/app#113]
Hi,

first let me say thank you for this great software. Running self hosted API, using App on all of my Linux Boxes and LineageOS mobiles with Firefox. Works really great. 

I have a few setups with Chromium on Linux. starting with Version 76.0.3809.87 the app crashes on start of Chromium. But also uBlock and ScriptSafe crashes. Must be some general change in Chromium.

Greetings!

**Comment by nero120** [comment]
Hi @vsatmydynipnet, first of all many thanks for the nice comments!!

I've just tried both v1.4.0 and the newly released v1.5.0 versions of xBrowserSync using Chromium 76.0.3809.87 for Win10 ([Marmaduke's ungoogled build](https://chromium.woolyss.com/)), and I'm unable to reproduce the issue. I've got an Ubuntu box at home that I can test on, which Linux distro are you running?

Some users have reported issues with Arch in the past, so there could be general issues with browser packages used by certain distros.

**Comment by vsatmydynipnet** [comment]
Hi @nero120,

I run Debian Sid on all of my Linux boxes. The problem occured since the Sid updates of yesterday. I have no Windows here, so cannot test.

**Comment by nero120** [comment]
ok thanks, I'll test on Ubuntu tonight and see if I can recreate on there.

**Comment by nero120** [comment]
@vsatmydynipnet I downloaded the current beta version of Chrome (76.0.3809.87-1) for Ubuntu (18.04.2 LTS) and xBrowserSync v1.5.0 works fine with it. When starting up the browser and sync is active, it updates the sync automatically as it should, no issues.

Can you download it from [here](https://www.google.com/chrome/beta/?platform=linux) and see if you still get the issue?

**Comment by vsatmydynipnet** [comment]
I just apt-get dist upgraded sid, and there was another chromium update. Version still shows 76.0.3809.87, but now all extensions, incl.ublock and scriptsafe works again on all boxes.

Thank you for your help. We can close this one.

**Comment by nero120** [comment]
Glad to hear it @vsatmydynipnet!
