### ISSUE TITLE
xBrowserSync not compatible with bookmark sorters

### ISSUE THREAD

**Issue by boomshankerx** [xbrowsersync/app#120]
I am using a chrome extension called SuperSorter to properly sort my bookmarks and folders. Every time I perform a sort on my bookmarks xBookmarkSync throws an error and reverts my bookmarks back to before the sort.

I've attached log file and screen cap of the error. 

![SNAG-2019-08-10-0000](https://user-images.githubusercontent.com/518179/62824777-cbfaa880-bb5f-11e9-9ac0-d0ef49d099ba.png)

[xBrowserSyncLog_20190810110519568.txt](https://github.com/xbrowsersync/app/files/3489134/xBrowserSyncLog_20190810110519568.txt)

**Comment by boomshankerx** [comment]
Additional Info:

It appears that the extension "Recursive Bookmark Sorter" seems to work fine with xBrowserSync. At least when making small changes.

SuperSorter has some extra valuable features that are valuable like deleting duplicates and removing empty folders.

**Comment by nero120** [comment]
@boomshankerx in order for me to fix this, can you please provide me with an xbrowsersync backup file that when SuperSorter is applied causes the error? It doesn't have to be your bookmarks data, anything generic that recreates the issue will work.

**Comment by maephisto666** [comment]
Hello @nero120, I think I was able to narrow the set of boomarks that **in my case** is causing the issue described by @boomshankerx (i.e. when I run SuperSorter, I got the same error message). Now as you can see (for some reasons, don't ask my why) I have 2 folders with the same name and this is causing the crash: when I moved every bookmark from one folder to the other one and I ran again SuperSorter, the sync went fine.

[xBrowserSyncBackup_20190812205656287.txt](https://github.com/xbrowsersync/app/files/3493950/xBrowserSyncBackup_20190812205656287.txt)

**Comment by nero120** [comment]
@maephisto666 thanks for this. It appears that the process of moving bookmarks either simultaneously or in quick succession (as does SuperSorter) can sometimes lead to conflicts. This is because xBrowserSync uses indexes when processing syncs. I have some ideas on how to resolve this, but it will take some experimentation, it's good that you can work around this issue for the time being.

**Comment by zackmuc** [comment]
Still get error when using Supersorter

**Comment by gibelium** [comment]
1) When will v1.5.3 be released?
2) Is the issue addressed / fixed within v1.6.0-beta and v1.7.0-beta releases?
