### ISSUE TITLE
Access sync data via other alternatives such as username/email/github, etc instead of sync id only which is hard to remember ...

### ISSUE THREAD

**Issue by mike652638** [xbrowsersync/app#122]
Thanks for the nice extension !

Currently it seems that the random generated Sync Id is the only way to access and sync data across different browsers/devices, it's somehow difficult for users to remember/keep. 

Could you please consider other alternatives ? 
For example, allow custom username/email address/github/facebook account .etc to associate with and to manage sync ids and sync data ? :)

**Comment by nero120** [comment]
Hi @mike652638, you're very welcome! Glad you're enjoying xBrowserSync.

Although the xBrowserSync service will always use the anonymous sync ID, the [plan](https://github.com/xbrowsersync/app/wiki/Roadmap) is to support syncing to different types of services in the future, for example, Nextcloud/Dropbox/etc. That way you can use an existing cloud storage account (as long as it's supported by xBrowserSync) to store your encrypted xBrowserSync data, and that will use the existing credentials for that service so no need to remember any xbs sync ID.

Hope that works for you. I'll close this issue but if you have any other questions just respond below.
