### ISSUE TITLE
tag v1.5.0 lacks Android APK

### ISSUE THREAD

**Issue by IzzySoft** [xbrowsersync/app#124]
Could you please also attach the `*.apk` to release v1.5.0 – as you did with previous releases? Somehow it is missing there. Thanks in advance!

**Comment by nero120** [comment]
Hi @IzzySoft, v1.5.0 was for Chrome and Firefox only. I'm currently working on v1.5.1 which includes a completely updated android app, it's mostly finished just tweaking the offline functionality. Expecting to release it first half of next month.

**Comment by IzzySoft** [comment]
Ah OK, that explains – thanks!
