### ISSUE TITLE
Android: cant fetch data for new bookmark

### ISSUE THREAD

**Issue by Offerel** [xbrowsersync/app#125]
If I use the share function in Android to add a new bookmark, the app can't fetch the URL or it's metadata. Tested with Firefox, Bromite, Firefox Preview and Samsung Internet on Android 9.

**Comment by nero120** [comment]
Hi @Offerel, this issue was fixed in 8310d5b69c1916a0dc5aba94131bd2e00b527024 and will be released in v1.5.1 (very soon hopefully!).
