### ISSUE TITLE
sync options

### ISSUE THREAD

**Issue by bijang** [xbrowsersync/app#129]
Has the encryption process gone though, r are there an plans to, put it through a 3rd party audit?
Thank you for your work
Also Is there a way to donate money to this project?

**Comment by bijang** [comment]
Also can it be made to work well with non cloud sync options like via syncthing. Perhaps whenever a change is made a local sync, or backup, occur. If this were possible would a temporary versioning be possible to see a 'history', where could roll back, like the way etesync backs up?

**Comment by nero120** [comment]
> Has the encryption process gone though, r are there an plans to, put it through a 3rd party audit?

No specific plans, but as this is an open source project anyone is free to 'audit' the code themselves. All encryption in xBrowserSync is done using the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) as implemented by the host browser, and the code that interfaces with this API can be found in [`utility.js`](https://github.com/xbrowsersync/app/blob/master/js/utility.js) as follows:

- [`getPasswordHash`](https://github.com/xbrowsersync/app/blob/master/js/utility.js#L377)
- [`encryptData`](https://github.com/xbrowsersync/app/blob/master/js/utility.js#L170)
- [`decryptData`](https://github.com/xbrowsersync/app/blob/master/js/utility.js#L104)

> Also Is there a way to donate money to this project?

Yes absolutely, just click on the `Sponsor` button above at the top of the page for a number of ways to donate. Thanks very much! 🙇 

> Also can it be made to work well with non cloud sync options like via syncthing...

The easiest way is just to [run your own xBrowserSync service using docker](https://github.com/xbrowsersync/api-docker) and only expose the service over your local network. That way you can sync between multiple computers on your network without worry about data going out over the net.

> If this were possible would a temporary versioning be possible to see a 'history', where could roll back, like the way etesync backs up?

It's possible but would require a large amount of changes to the syncing engine. I'm not planning on doing this unless absolutely necessary though...
