### ISSUE TITLE
Puffin browser support

### ISSUE THREAD

**Issue by 3xploiton3** [xbrowsersync/app#130]
The fastest way to load web in android,

**Comment by nero120** [comment]
Hi @3xploiton3, xBrowserSync currently does not support integration with any mobile browser (to access your synced bookmarks on mobile you'd need to use the xBrowserSync android app). It is not currently on the [roadmap](https://github.com/xbrowsersync/app/wiki/Roadmap) and is unlikely to change for the foreseeable future, really sorry.
