### ISSUE TITLE
New Firefox Nightly breaks sync?

### ISSUE THREAD

**Issue by ipk01** [xbrowsersync/app#131]
For the first time in ages my bookmarks have become garbled again. Have no logs yet but will provide after attempting to rescue my bookmarks at home. Possibly related to new Firefox Nightly that installed itself? Will need to confirm.

**Comment by nero120** [comment]
Ok that would be useful if you could provide the log. Bear in mind though that I can't support nightly builds for obvious reasons (betas possibly depending on effort required). I would recommend using at least beta if not standard releases ideally.

**Comment by ipk01** [comment]
Indeed ... no more issues after downgrading to version firefox 70 on all machines.

**Comment by nero120** [comment]
Ah glad to hear it @ipk01!
