### ISSUE TITLE
Deleted bookmarks are not synced

### ISSUE THREAD

**Issue by gregersn** [xbrowsersync/app#134]
Installed the extension
Did a massive cleanup of duplicate bookmarks from ealier (bad) sync services
Deletion is not synced to server.

Chrome with extension from chrome store

**Comment by nero120** [comment]
@gregersn are you still seeing this with v1.5.2?

**Comment by gregersn** [comment]
I deleted a bunch of bookmarks just now (a few hundred), and it has been trying to sync that for over ten minutes, showing over 100 on CPU usages in the browser task manager.

**Comment by nero120** [comment]
@gregersn then you'll need to provide all the information required by the [issue template](https://github.com/xbrowsersync/app/issues/new?assignees=&labels=&template=bug_report.md&title=) otherwise I cant help you.

**Comment by gregersn** [comment]
Seems like it just took a really long time to sync. So looks to be better now. 
Closing this.
