### ISSUE TITLE
Ubuntu+Brave  no sync

### ISSUE THREAD

**Issue by ziomik** [xbrowsersync/app#136]
I'm using the Brave Browser in 2 machines. One is Windows and the other Linux. Syncing on linux doesn't work. This is the error:

> Connection lost
> Couldn’t connect to the xBrowserSync service, check the service status in the Settings panel.

If I try to import the backup file made by windows I get this answer:

> Sync error
> An error occurred whilst syncing local changes. Your local bookmarks have now been refreshed so you may need to redo the previous change.

**Comment by trymeouteh** [comment]
I got this too. I wonder if it is because Brave sync even when it is not used is causing issues with xbrowsersync to function. I believe that only on bookmark syncing tool can run at a time and if Brave sync is "running" even if it is not being used, it could be preventing xbrowsersync from working.

**Comment by nero120** [comment]
@ziomik if you could provide some log files that include the error that would be useful.

@trymeouteh if Brave sync is disabled then it would not be updating bookmarks that could cause conflicts with xBrowserSync, so very unlikely.

**Comment by trymeouteh** [comment]
https://privatebin.net/?d39087eea5a07c57#5J8MrfwpgF1Dm6bknAtHHuFMyW3R4hjFAnNdnujTQCuh

Here is my log

**Comment by nero120** [comment]
Ah ok, looks like it's the [Brave update](https://github.com/xbrowsersync/app/issues/100#issuecomment-571476516) which broke bookmark compatibility with chromium, from your log:

```
2020-01-07 20:56:49.524	[error]	bookmarks.sync: [10113] LocalContainerNotFound
2020-01-07 20:58:37.910	[warn]	Missing container: other bookmarks
```

xBrowserSync doesn't officially support Brave until v1.6.0 and this is being tracked [here](https://github.com/xbrowsersync/app/issues/100), so I'm going to close this issue. I'll update the main Brave support issue with any news so please subscribe to that issue for updates.
