### ISSUE TITLE
Sync errors when cleaning up bookmarks

### ISSUE THREAD

**Issue by teeruku-github** [xbrowsersync/app#137]
I am trying to cleanup my bookmarks and remove dead links. When I do that Xbrowsersync app on brave seems to error out. Here is the log.
[xBrowserSyncLog_20191128115613058.txt](https://github.com/xbrowsersync/app/files/3900175/xBrowserSyncLog_20191128115613058.txt)

**Comment by nero120** [comment]
@teeruku-github currently there is a known issue when modifying multiple bookmarks at once, I have a plan to fix it in a future version.

For now, I can only suggest modifying smaller batches, and when you hit the issue, modify individually one by one. Hope that helps.
