### ISSUE TITLE
Brave Login Issue

### ISSUE THREAD

**Issue by ace13131** [xbrowsersync/app#138]
The issue is that i cannot get logged into the Brave-Nightly or any of the other Brave Builds on my Windows 10 Pro build 1903 laptop.  I have it working fine with Firefox on the same machine. 
During the login process the sync just spins and spins and never successfully completes.  From the logs it appears that it is unable to update the local Bookmarks file.

![2019-12-03 10_54_59-New Issue · xbrowsersync_app - Brave](https://user-images.githubusercontent.com/41758606/70071810-81dc7d80-15bb-11ea-84c7-4dbe976ca211.jpg)

[xBrowserSyncLog_20191203095402677.txt](https://github.com/xbrowsersync/app/files/3917739/xBrowserSyncLog_20191203095402677.txt)

**Comment by nero120** [comment]
@ace13131 the logs are saying the other bookmarks container cannot be found. I'd be surprised if Brave have changed something fundamental with the Chromium bookmarks structure, can you create a brand new profile and add xBrowserSync to that profile and see if you get the same error?

**Comment by ace13131** [comment]
It is the same issue with a Clean Profile.  It appears from the log that it is having issues accessing the bookmarks file.

[xBrowserSyncLog_20191203154425210.txt](https://github.com/xbrowsersync/app/files/3918852/xBrowserSyncLog_20191203154425210.txt)

**Comment by nero120** [comment]
Is the issue occurring just on the nightly or do you get it on latest release? I'm running on Brave version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit) on Win10 1803 and I don't get this issue.

Otherwise, could be that they've changed something fundamental in the nightly.

**Comment by ace13131** [comment]
I have the same issue on the dev beta and the stable also.  I tried each one.  Firefox works on the same computer

**Comment by nero120** [comment]
Ok can you check the browser native bookmark data, as per the following steps:

- Go to `brave://version/` and get the Profile Path value, open this path in explorer
- Browse to the file titled `Bookmarks`, open it in a text editor, it should look something like this:

```
{
   "checksum": "cb01f5c27ab7ca4eee40d94553096b71",
   "roots": {
      "bookmark_bar": {
         "children": [  ],
         "date_added": "13209504751806829",
         "date_modified": "0",
         "guid": "00000000-0000-4000-A000-000000000002",
         "id": "1",
         "name": "Bookmarks bar",
         "type": "folder"
      },
      "other": {
         "children": [  ],
         "date_added": "13209504751806847",
         "date_modified": "13219278619415842",
         "guid": "00000000-0000-4000-A000-000000000003",
         "id": "2",
         "name": "Other bookmarks",
         "type": "folder"
      },
      "synced": {
         "children": [  ],
         "date_added": "13209504751806849",
         "date_modified": "0",
         "guid": "00000000-0000-4000-A000-000000000004",
         "id": "3",
         "name": "Mobile bookmarks",
         "type": "folder"
      }
   },
   "version": 1
}
```

The important part is that the `id` value for `bookmark_bar` should be `1` and the `id` value for `other` should be `2`. There are some instances where users have different id values for these nodes and that means xBrowserSync cannot find them, hence the errors.

**Comment by ace13131** [comment]
That allowed me to get the Stable version of Brave Running. Still the same error on the nightly, even if i copy over the bookmark file from the working stable version.  I will use the Stable version and keep checking the nightly every once and a while.

**Comment by nero120** [comment]
Good stuff, glad it's working now!
