### ISSUE TITLE
Firefox Extension - Onboarding Wizard never ends

### ISSUE THREAD

**Issue by matthewdavis** [xbrowsersync/app#140]
**Describe the issue you are experiencing**
The onboarding wizard will not end. Even if I try to skip, the Skp will not work. After getting to the end of the wizard, and click on Close, it does not close and starts over again.

**How can the issue be reproduced?**
1. Fresh Firefox Install (I'm actually using the [ghacks user.js](https://github.com/ghacksuserjs/ghacks-user.js/) if that matters. It has not in the past
2. Install Extenison
3. Attempt to complete the onboarding wizard
4. Attempt to complete the onboarding wizard
5. Attempt to complete the onboarding wizard
6. ...

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Fedora 31
 - Browser Firefox
 - Version 71

**Application log**
Please include the logs from the affected clients:

I'm unable to get to the settings to get the logs.

**Comment by nero120** [comment]
@matthewdavis I can't recreate this in Firefox 71. Can you please re-try with a brand new, unmodified Firefox profile and without ghacks please?

**Comment by matthewdavis** [comment]
Ok. Fresh install, no issue. I'll re-open if I can pin-point the issue (as an FYI). But it doesn't look to be an issue on your end. Sorry for the noise.

**Comment by nero120** [comment]
Ok thanks for confirming @matthewdavis!

**Comment by matthewdavis** [comment]
Btw, I'm not sure how many users you have on Fedora and Firefox, but I believe the issue I encountered was attributed to [this](https://bugzilla.redhat.com/show_bug.cgi?id=1779570). Just FYI. There is a fix and I'm using the -15 rpm and the onboarding wizard (if thats what you call it) completed successfully.

**Comment by nero120** [comment]
Ah thank you for that @matthewdavis, very useful!
