### ISSUE TITLE
Move search bar to bottom of screen

### ISSUE THREAD

**Issue by marissarousseau** [xbrowsersync/app#143]
Currently the search bar is at the top of the screen, which makes it somewhat difficult to reach on taller devices. It would be convenient to at least have an option to move the search bar to the bottom of the screen for quick access to searching your bookmarks.

**Comment by nero120** [comment]
@marissarousseau this will be released with v1.5.1 within the next few weeks.

**Comment by marissarousseau** [comment]
Awesome, glad this feature is coming! Thank you.
