### ISSUE TITLE
Android App 1.5.0 missing

### ISSUE THREAD

**Issue by tuxStarElan** [xbrowsersync/app#146]
as mentioned in the readme the android app should be available "very soon"
By the way can the v1.4 android app be used with the v1.5 desktop extension without problems?

**Comment by nero120** [comment]
I'm currently putting the finishing touches to v1.5.1 which will be released for Android (as well as desktop extensions) and includes all the major v1.5.0 updates. Should be out in the next few weeks, time allowing.

> By the way can the v1.4 android app be used with the v1.5 desktop extension without problems?

Yes it can.

**Comment by tuxStarElan** [comment]
Cool.
Thanks for the great work.
