### ISSUE TITLE
Merge firefox bookmark and chrome

### ISSUE THREAD

**Issue by 3xploiton3** [xbrowsersync/app#147]
**Describe the issue you are experiencing**
A clear and concise description of your issue:
I have chrome bookmark and firefox bookmark, how to merge/join to 1 ID xbrowsersync?
i don't see option for this, 

**How can the issue be reproduced?**

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: win10
 - Browser [Chrome, Firefox]
 - Version [v1.5.0]

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: [e.g. Samsung Galaxy S10]
 - OS: [e.g. Android 9 Pie]
 - Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by nero120** [comment]
The only way to merge currently is manually unfortunately. Take a backup for each sync ID (sync to the ID then download a backup from the Settings panel), open each file in a text editor and then do the following:

1. In the backup from Chrome, find the `[xbs] Other` bookmark, and copy all of the bookmarks within it's `children` property. Don't copy the square braces (`[`/`]`), start with the first curly brace (`{`) of the first child bookmark and end with the last curly brace (`}`) of the last child bookmark.
2. In the backup from Firefox, find the `[xbs] Other` bookmark, go to the last child bookmark and after the last curly brace (`}`) of the last child bookmark, add a comma (`,`) then paste the text you copied from the Chrome backup.
3. Repeat steps 1 and 2 but this time find the `[xbs] Toolbar` bookmark (if it exists).
4. All of your Chrome bookmarks are now in the Firefox backup file, however there are likely duplicate ids. You'll need to make sure that each bookmark has a unique number for an id before you can restore it.
5. Create a new sync ID (don't restore to your existing sync IDs in case something goes wrong), then restore the edited Firefox backup file to this sync ID.
