### ISSUE TITLE
Automatic Backups

### ISSUE THREAD

**Issue by methanoid** [xbrowsersync/app#15]
Suggestion that the extension makes a series of regular backups of bookmarks, overwriting the oldest. 

Could be:

Daily - one backup a day at first use of browser in that day, keeping "n" numbers of backups and if there are already "n" in existence then the oldest gets lost and replaced with a new one.  "n" obviously multiplies the capacity used at the sync host by that factor. 

Weekly - same as above but would allow for longer time period coverage with any given value of "n"

Monthly - not sure I see the value here myself but ......

**Comment by nero120** [comment]
Good suggestion, thanks @methanoid!

**Comment by jcrben** [comment]
In the meantime, if it comes up, Firefox does apparently do automatic backups which I found in `~/.mozilla/firefox/gnm7ka3x.default-release/bookmarkbackups`.

**Comment by methanoid** [comment]
Thanks but IO stopped using FF years ago. Chrome now.  Had to stop using XBS too cos it would barf too much when doing multiple changes to bookmarks and then it started to lose stuff for me. real shame cos its the ONLY replacement to Xmarks we have :-(

**Comment by nero120** [comment]
@methanoid indeed there are still bugs with moving multiple bookmarks, especially in Firefox. It's a complex use case and I have a plan to greatly improve, if not fix it altogether, but it will unfortunately have to wait until after the current release is out.

I've been putting off releasing v1.5.1 for too long trying to get more stuff in, but this fix is too complex.

**Comment by methanoid** [comment]
I understand real life also affects development....   Please do tag me when the new version is out as I am always willing to try new ones as this is the only hope for "proper" sync and backups of bookmarks.

**Comment by nero120** [comment]
@methanoid I just implemented auto back up and will be included in the upcoming v1.6.0 release. If you want to give it a spin, try the latest [pre-release](https://github.com/xbrowsersync/app/releases) (once the build process has uploaded it).
