### ISSUE TITLE
Some Critical functionality features that we need...

### ISSUE THREAD

**Issue by hosadokha** [xbrowsersync/app#154]
I am aware what this extension is capable of.. **but it is too minimal for what I need**
I like that this is totally independent on Google but the world needs online backup _**not just for bookmarks, but for History (such as U History extension, but it depends on G. sync) and extensions backup and (browser & extension) Settings backup, all into one cross platform powerfull extension**_, where i am able to view what exactly is held in the cloud.
I hate G.sync btw bec. I synced once and I got BOMBARDED (without my consent or approval) by all those ancient extensions that just were there in the servers from a long time ago.  and the fact that i am not able to pick what gets synced, espesially when i cant see whats up in the cloud, AND THATS WHY I USE THE WORD "BACKUP" AND NOT "SYNC" because "syncing" is too simplistic of an idea.. MY EXISTING bookmarks also got automatically removed by G.sync..
I hope the developers take this Advice profoundly to their heart because this is truly what I need, and what I would pay for..

**Comment by nero120** [comment]
Hi @hosadokha, thanks for the comments. Have a look at the [Road Map](https://github.com/xbrowsersync/app/wiki/Roadmap) to see what are the major features planned for version 1 of xBrowserSync.

Unfortunately, syncing of browser settings is just not possible as no browser API exists to interact with. There is an API for Extensions, but from what I can tell it is only possible to query and uninstall, not install so it wouldn't be possible to implement a sync for extensions.

**Comment by hosadokha** [comment]
wow this cleared up things for me thank you...
so ur saying we should blame Google?\
i dont fully understand because i know Chromium is opensource, so anyone could make an API if not google..

**Comment by nero120** [comment]
> wow this cleared up things for me thank you...
> so ur saying we should blame Google?
> i dont fully understand because i know Chromium is opensource, so anyone could make an API if not google..

Indeed, here you go: https://chromium.googlesource.com/chromium/src/ 😉
