### ISSUE TITLE
Remove notification if syncing is not possible due to connectivity issues

### ISSUE THREAD

**Issue by hacker-h** [xbrowsersync/app#156]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is:
Everytime I launch my browser after booting the network stack is apparently not ready yet and causes the xbrowsersync app to yield a popup, which informs me that a sync is not possible.
Those popups are frustrating because they have to be manually clicked away.

**Tell us about your idea**
As a user I appreciate it when no popups occur and programs rather indicate such issues by altering their icon, e.g. by showing a red cross.

**Comment by nero120** [comment]
Why did this get closed? From the issue template guidelines:

> ** Important note: I do not have time to chase people for information so if the form below is not completed adequately your issue will likely be closed without further consideration. Remember this is FOSS, if you're using it and want a bug to be fixed then do me the courtesy of completing the issue form properly.
