### ISSUE TITLE
Password reset?

### ISSUE THREAD

**Issue by jcrben** [xbrowsersync/app#157]
Note, this might be better handled by contact but https://www.xbrowsersync.org/contact/ is a 404.
> Alternatively, if you are a user and need to report an issue with a particular xBrowserSync service, please send us a message instead using the contact form at https://www.xbrowsersync.org/contact/.

The FAQ should explain how to handle forgotten passwords
> Before you continue, please check the list of known issues (https://github.com/xbrowsersync/app/wiki/Known-issues) and the FAQs (https://www.xbrowsersync.org/#faqs). Otherwise, please fill out all of the information below.

The below template is not really relevant. I simply forgot my password and it's not clear how I proceed from there. Also, I don't want to simply create a new sync as I'd rather the data get flushed if I'm going to do that.

**Describe the issue you are experiencing**
A clear and concise description of your issue:

**How can the issue be reproduced?**

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: [e.g. Win10]
 - Browser [e.g. Chrome, Firefox]
 - Version [e.g. v1.5.0]

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: [e.g. Samsung Galaxy S10]
 - OS: [e.g. Android 9 Pie]
 - Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by nero120** [comment]
> Note, this might be better handled by contact but https://www.xbrowsersync.org/contact/ is a 404.

Thanks, I've now fixed the incorrect link.

> The FAQ should explain how to handle forgotten passwords

Indeed it does: https://www.xbrowsersync.org/?faqkw=forgotten%2520my%2520password#faqs

The "password" you enter is simply an encryption key, it cannot be recovered or reset. This is why the help text in the extensions says _"Be sure to make it strong but also memorable, there are no resets or reminders so if you forget it you won’t be able to access your synced data."_

The only thing you can do is to recover your bookmarks from a backup.

**Comment by jcrben** [comment]
I see. It would help to provide the FAQ as a single page. I didn't click "More" often enough. And I prefer to use CTRL+F to search for keywords.

How long until my data gets flushed out?

**Comment by TikiThorsen** [comment]
> 
> 
> I see. It would help to provide the FAQ as a single page. I didn't click "More" often enough. And I prefer to use CTRL+F to search for keywords.
> 
> How long until my data gets flushed out?

Hello, sorry to "nekro" but since I also forgot/lost my Sync ID and Password, I was won what will happens to that data; if it gets deleted and in how long? Like the OP "jcrben" asked.

**Comment by Adda0** [comment]
It depends on the provider of the public cloud service if you do not self-host. There is usually a time limit of about a month where data are being stored even if there are no changes to the data, no pushes and pulls – synchronization updates in general. After that, data will be deleted from the service. Every provider can set this limit and handle this problem differently, but this is usually the case from what I have seen. See these relevant [FAQs](https://www.xbrowsersync.org/?#faqs):

- **I’ve forgotten my password and can’t retrieve my synced data! What should I do?**
    - As passwords are not stored remotely they are not recoverable, and your synced data cannot be decrypted without the original password. The only thing you can do is to create a new sync and then restore your data from a backup.
- **I previously created a sync but when I try to retrieve my data I get a “No data found” error message. What is going on?**
    - When you create a new sync, the sync ID you receive is specific to the xBrowserSync cloud service you synced to, so ensure you are attempting to sync to the same service with which you created your sync. If you are using the same service then it is likely your synced data has been deleted, this can happen if you do not access your synced data for several weeks. In this case, you must create a new sync and restore from your most recent backup.
- **I’m going away for an extended period and don’t expect to use my devices, will my synced data be deleted?**
     - To keep xBrowserSync free, most services operate a fair use policy which means any synced data that is not accessed for several weeks will be removed to make space for other users. In practice, if you open your browser or use the xBrowserSync mobile app at least once a week this is not something you ever need to worry about. If you do not expect to have access to your devices for several weeks then take a backup of your synced data and if your sync is deleted before you can access your data again, create a new sync and restore from your backup.

**Comment by nero120** [comment]
@TikiThorsen @jcrben most public services will automatically delete any syncs that have not been accessed after three weeks. But please understand that the entire point of xBrowserSync is that all data transmitted between client and server is encrypted and anonymous. There is no personal identifying data contained in the synced data, it looks like this to the service admin:

```
{
    "_id" : UUID("9b0377eb-e1f3-485a-9cbe-b4b9c59ab64b"),
    "version" : "1.6.0",
    "lastAccessed" : ISODate("2021-05-11T11:21:05.479Z"),
    "lastUpdated" : ISODate("2021-05-11T11:21:03.998Z"),
    "bookmarks" : "DWCx6wR9ggPqPRrhU4O4oLN5P09oULX4Xt+ckxswtFNds..."
}
```

Even if you gave me a valid ID, as the service admin with no way of associating that data to you, how do I know that data is "yours"? I don't, and that is the whole point. You don't need to worry where this data goes since it contains no personal data that can identify you and no one except you can decrypt the bookmarks portion of it. That is the entire USP of xBrowserSync! Except that it's free of course!
