### ISSUE TITLE
When recycle bin of the bookmarks is cleared, it says "Sync Error"

### ISSUE THREAD

**Issue by cdytoby** [xbrowsersync/app#159]
**Describe the issue you are experiencing**
A clear and concise description of your issue:

When I empty the recycle bin of the bookmarks, it says "Sync Error".

![image](https://user-images.githubusercontent.com/15671368/73840412-6b9ba980-4818-11ea-9637-67664856f603.png)

**How can the issue be reproduced?**
1. Go to Bookmark Sidebar (left side of the browser)
2. Right Click on the last item, "Recycle Bin"
3. Click Empty Recycle Bin

**Screenshots**
If applicable, add screenshots to help explain your problem:

Screenshot for Right click Recycle Bin, and left click clear recycle bin.
![image](https://user-images.githubusercontent.com/15671368/73842030-1a8db480-481c-11ea-9935-46ada60ebe88.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: [e.g. Win10] Win 10
 - Browser [e.g. Chrome, Firefox] Vivaldi
 - Version [e.g. v1.5.0]  2.10.1745.26 (Stable channel) 

**Application log**
Please include the logs from the affected clients:

[xBrowserSyncLog_20200205132846597.txt](https://github.com/xbrowsersync/app/files/4159472/xBrowserSyncLog_20200205132846597.txt)

**Comment by nero120** [comment]
@cdytoby Vivaldi is not currently supported, it is currently targetted to be added in v1.6.0. You can follow the existing feature request [here](https://github.com/xbrowsersync/app/issues/6).
