### ISSUE TITLE
Expose bookmarks hierarchy in the App

### ISSUE THREAD

**Issue by cjnaz** [xbrowsersync/app#16]
### First a unsolicited plug for this project, combined with a usage note

With the demise of xmarks I went looking and took a bet on this solution.  I have my bookmarks organized in a several folders in the bookmark bar.  While the Chrome xBrowserSync App can import from the bookmark bar, and recreates the folders on sync download, that hierarchy isn't visible in the App.  So I've grown on the tags and search use model that this App provides.  FYI, new bookmarks created within the App land in Chrome's Other Bookmarks / _xBrowserSync folder.  I'm happy, and plan to contribute at some point.  Happy enough that I've set up my own API server.  Two thumbs up for Rich's work so far.  Jump on in, the water is fine.

### Feature request - _Expose bookmark hierarchy in the App_
Within the App, allow the user to browse for bookmark using the folder hierarchy.  This could be opened from a folder icon in the search bar.  This would support the browsing use model in addition to the text search use model.  An alternate solution would be for the App to present a web page of the bookmarks in (collapsed) folder hierarchical form.  When a new bookmark is created within the App somehow the user would need to have the option for placing it within the hierarchy.  For the new bookmark creation in a folder, I can use the URL drag to a bookmark folder method in PC Chrome, but I don't see how to do that on the Android side.

**Comment by nero120** [comment]
Thank you for the kind words @cjnaz, I'm really glad you're enjoying xBrowserSync so far! Thanks also for the suggestion, it does make sense for the mobile user to have some way of navigating the folder structure if that's how they are used to navigating their bookmarks.

As always, please anyone else who would also find this valuable thumbs up or chime in so I can gauge priority when implementing new features.

**Comment by truncsphere** [comment]
I agree, being able to browse your bookmarks via a folder structure is a must for me personally.

**Comment by SpearheadUK** [comment]
Definitely the main feature I'm dying to get. Bookmark folder visibility and ability to add new bookmarks to a folder withing the plugin and app.

**Comment by rocksoccer** [comment]
I am changing some code to add it. Just could someone point me how to build the final packages for different platforms, especially android? I ran `npm run build:android`, only the `build` folder is generated, no apk file is created. The same for firefox, too.
First time to do cordova, any direction will be much appreciated.

**Comment by nero120** [comment]
@rocksoccer I've updated the [README](https://github.com/xbrowsersync/app/blob/master/README.md) to provide more information, please review the installation and build steps.

Re Android, once Cordova has been [installed and configured](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html) for Android, running `npm run build:android` should produce a debug apk file nested within the `build/cordova/platforms/android` dir. You can then either install this apk manually or use Cordova to run the build in a local [emulator](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-up-an-emulator). This is from memory as I need to review these steps and cannot do this at my current machine, but that should be the gist of it. Once I've done this I'll update the README to include this.

**Comment by nero120** [comment]
https://www.patreon.com/posts/sneak-peek-view-29278175 😉

**Comment by cjnaz** [comment]
HI Rich,
Can you supply a download link on an open server not requiring a
subscription?
Thx,
Cjn

**Comment by nero120** [comment]
@cjnaz it's not a link to a download, just a blog post previewing the folder view functionality that's coming. It's exclusively for the patrons of xBrowserSync who donate regularly to the project as a way to say thank you, as I don't really do much exclusive content or benefits for them at all. Don't worry, everyone will get this functionality at the same time once it's ready, I linked to it here so you would at least know it's on it's way.

**Comment by cjnaz** [comment]
Ah thanks.  I misunderstood.  I look forward to the beta release.

Btw, when I went to app 1.5 across my various Chrome and Firefox installs I
again got a lot of bookmarks duplicated.  I haven't gone in to clean them
up yet, and I didn't file an issue - been too busy.

Regards and thanks again,
Cjn

**Comment by nero120** [comment]
Damn ok, when you get a chance create an issue and attach all the log files, hopefully they will reveal the cause of the problem.

**Comment by kkuhle** [comment]
+1

**Comment by nero120** [comment]
Long time coming this one, glad to have finally implemented it and hope you all like it! v1.5.1 should be available within the next week or so.
