### ISSUE TITLE
firefox desktop (72.0.2) crashes after installing the extention (v 1.5.1)  and tring to import bookmarks

### ISSUE THREAD

**Issue by sviluppoSoftware** [xbrowsersync/app#160]
after installing the extension from the firefox store and log in, the warning appeared that all my bookmarks would be deleted after the bookmarks are removed I restore them, first using the relative browser function then also with the file bookmark html exported from firefox before installing the extension, but immediately the browser freezes consuming a lot of cpu and also the operating system (ubuntu18.04 and windows10) freezes, I am forced to kill the browser process via taskmanager.

**Comment by nero120** [comment]
You need to attach the log as it says in the issue template!!!

**Comment by sviluppoSoftware** [comment]
sorry, it was difficult to download the log because the browser was blocked at every start ... however here it is, for privacy reasons I deleted my syncID I don't think it's important
[xbs_log_20200210225836.txt](https://github.com/xbrowsersync/app/files/4183301/xbs_log_20200210225836.txt)

**Comment by nero120** [comment]
Ok thanks @sviluppoSoftware, from your log:

```
2020-02-10 21:56:23.950	[trace]	Sync 1jjehhw (pull) queued (1 waiting to sync)
2020-02-10 21:56:23.980	[trace]	Processing sync 1jjehhw
2020-02-10 21:56:27.843	[trace]	Local population completed in 0.098s
2020-02-10 21:56:27.869	[trace]	Sync enabled
2020-02-10 21:56:27.898	[trace]	Sync 1jjehhw committed (0 waiting to sync)
```

The above logs show that you successfully connected to an existing sync.

```
2020-02-10 21:57:01.350	[trace]	Downloading file xbs_log_20200210225701.txt
2020-02-10 21:57:26.451	[trace]	onCreated event detected
2020-02-10 21:57:27.991	[trace]	onCreated event detected
2020-02-10 21:57:28.858	[trace]	onCreated event detected
...
```

25 seconds after you downloaded the log file, for some reason there are 640 onCreated events, that means 640 bookmarks were created and xBrowserSync detected those events and attempted to sync them, that's why your CPU spiked (Firefox is not the best browser at handling this load).

What did you do to trigger this many onCreated events? Do you have Firefox sync (or any other sync tool) enabled?

**Comment by sviluppoSoftware** [comment]
What did you do to trigger this many onCreated events? Do you have Firefox sync (or any other sync tool) enabled?
i have imported my bookmarks, first time using the relative browser function then also with the file html exported from firefox before installing the extension

**Comment by nero120** [comment]
Ah yes you did say that in your original post. Ok, so importing using the native browser import tool whilst xBrowserSync was synced was what caused the issue. So, I recommend:

- Disabling sync in xBrowserSync
- Import your bookmarks using the native browser import
- Create a new sync in xBrowserSync which will now have synced all of your imported bookmarks

Note: once you are synced you shouldn't use the native bookmark import, however restoring an backup in xBrowserSync is fine when you are both synced or not synced.

**Comment by sviluppoSoftware** [comment]
thank you a lot for assistance, now sync  correctly!

**Comment by nero120** [comment]
Glad to hear it @sviluppoSoftware, enjoy!
