### ISSUE TITLE
Just notice my main bookmark for work is gone

### ISSUE THREAD

**Issue by jjtuttle** [xbrowsersync/app#164]
Today I noticed that my main bookmark for work is gone on both browsers [Chrome and Firefox] I was using the work one a couple hours ago so not sure how or why I lost it all.

Attaching log file
I mostly have both browsers open all the time and work manly in Chrome. I am using a macbook pro

Chrome: Version 80.0.3987.122 (Official Build) (64-bit)
Firefox: 68.5.0esr (64-bit)

Macbook Pro: macOS Majove version 10.14.6, MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

[xbs_log_20200228152028.txt](https://github.com/xbrowsersync/app/files/4269577/xbs_log_20200228152028.txt)

**Comment by nero120** [comment]
@jjtuttle thanks for raising this, after checking your log file it appears you were hit with the bug raised in #133. This has been fixed in v1.5.2 which I will aim to release next week.

Really sorry about this, hope you can restore your bookmarks from a backup.

**Comment by jjtuttle** [comment]
This lost my bookmarks too. No where to get them back????

**Comment by nero120** [comment]
@jjtuttle restore from a backup - you did take backups didn't you (The app advises in multiple places that you need to backup regularly)?

I'm really sorry that you lost your bookmarks, but xBrowserSync is an open source project and thus will inevitably be subject to bugs that may in the very worst case result in data loss/corruption. Obviously I work hard to try to limit and resolve these issues but users need to take responsibility for their own data, and make sure you take backups!

**Comment by nero120** [comment]
[v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2) has now been released that includes a fix for this issue.
