### ISSUE TITLE
App won't open... net::ERR_FILE_NOT_FOUND (file:///android_asset/www/app.html)

### ISSUE THREAD

**Issue by bat999** [xbrowsersync/app#165]
Hi
I've installed xBrowserSync v1.5.1 from F-Droid.

The app won't open.
When I try to open it I see this message...
**Application Error
net::ERR_FILE_NOT_FOUND (file:///android_asset/www/app.html)**

My phone is Xiaomi Redmi-go
OS is Android-go Oreo v8.1.0

![Screenshot_xBrowserSync](https://user-images.githubusercontent.com/640761/75935159-6ca31380-5e76-11ea-918e-7e971dab0024.jpg)

**Comment by yashashebbarabailu** [comment]
I am having this issue.

**Comment by SuperSandro2000** [comment]
Giving the app both permissions just uninstalls it.

**Comment by nero120** [comment]
@bat999 if you install the apk from the [v1.5.1 release page](https://github.com/xbrowsersync/app/releases/tag/v1.5.1) do you get the same error?

**Comment by bat999** [comment]
No error with the apk from release page.
It opens OK.
:-)

![success](https://user-images.githubusercontent.com/640761/76132990-c4c04e00-600d-11ea-97d3-00c57d64a71d.jpg)

**Comment by nero120** [comment]
Many thanks @bat999, looks like an issue with the FDroid build process. I'll raise an issue with them.

**Comment by yashashebbarabailu** [comment]
> @bat999 @yashashebbarabailu if you install the apk from the [v1.5.1 release page](https://github.com/xbrowsersync/app/releases/tag/v1.5.1) do you get the same error?

Thanks. Apk from released worked.

**Comment by josealberto4444** [comment]
> Many thanks @bat999, looks like an issue with the FDroid build process. I'll raise an issue with them.

@nero120 Any news on this? Do you have a link of the issue you opened with them to follow the progress? The f-droid app was updated a week ago but the problem is still there. Thanks for all your effort!

**Comment by nero120** [comment]
@josealberto4444 unfortunately still trying to fix the build issues with the guy who looks after F-Droid, you can follow the conversation [here](https://gitlab.com/fdroid/rfp/-/issues/789).

**Comment by nero120** [comment]
The issues have now been resolved, F-Droid will have a working updated package shortly.

**Comment by nero120** [comment]
I'm reopening this since F-Droid build issues are preventing a working package from being built. It looks like the issues are environmental on the F-Droid side, so fingers crossed the F-Droid maintainer can get them resolved...

**Comment by nero120** [comment]
Please note, due to the broken build xBrowserSync is not currently available in the FDroid repo, will hopefully be resolved soon.

**Comment by nero120** [comment]
The F-Droid build has now been fixed and a working apk has been published to the F-Droid repo! 🤗

**Comment by josealberto4444** [comment]
A promise is a promise.

![image](https://user-images.githubusercontent.com/13300909/84832339-5a1ba700-b02d-11ea-8cc4-43a12aab9d98.png)

Thanks for all the hard work. I kept an eye on the gitlab issue and I guess it was a real nightmare.

**Comment by nero120** [comment]
@josealberto4444 really appreciate that bud, thank you very much. Yeah it was a tricky one, fixing environmental issues when you don't have access to the environment is always fun! 😱

Sorry it took so long but we got there in the end!
