### ISSUE TITLE
Firefox Sync Tags

### ISSUE THREAD

**Issue by Cupbox** [xbrowsersync/app#166]
Firefox has a native bookmark tagging system. The ability to sync those tags would be appreciated.

**Comment by nero120** [comment]
@Cupbox check [known issues](https://github.com/xbrowsersync/app/wiki/Known-issues), Mozilla have not implemented an API for native tags so there's no way for xBrowserSync to interact with it until they do.

**Comment by matthewblott** [comment]
I checked your API to see if it's possible to update bookmarks but couldn't see how to update the tags, is it possible? I thought I could perhaps write some sort of script to extract the Firefox tags and update xBrowserSync's bookmarks as a workaround. Any help appreciated :-)

**Comment by nero120** [comment]
@matthewblott there's no API that will let you extract the tags to my knowledge, however if you create a backup in 
Firefox, the resulting JSON file will include the bookmark tags along with the rest of the bookmark data. You could create a node.js (javascript) script that takes this backup file as an input and converts it to a JSON format that matches an xBrowserSync backup file, which you can then simply restore. That's a better solution that calling the APIs directly which would be very slow for many bookmarks.
