### ISSUE TITLE
No sync upload possible, only downloads.

### ISSUE THREAD

**Issue by capricorn72** [xbrowsersync/app#168]
When deleting a bookmark entry in the browser, the sync tool reports an error "local data has been refreshed..." and re-syncs the data from the server, but it should upload the deletion to the server.

Same problem on Vivaldi, Firefox and Chromium in Linux.

Tested with a newly created sync: same problem again.

**Comment by capricorn72** [comment]
Seems to be the same bug as reported in #134 about four months ago.

**Comment by nero120** [comment]
@capricorn72 if you get the "local data has been refreshed..."message then it means there was an issue or conflict with the change and it has not been committed, so you'll need to re-do the change.

**Comment by capricorn72** [comment]
I have re-done the change very multiple times. Always the same.

No good idea to simply close this ticket. The problem is not solved with this.answer.

25.03.2020 17:23:57 Rich <notifications@github.com>:
