### ISSUE TITLE
Installing beta on Brave results in Missing container: other bookmarks

### ISSUE THREAD

**Issue by poikilos** [xbrowsersync/app#169]
**Describe the issue you are experiencing**
Trying to unzip then "Load Unpacked" extension from brave-browser-beta fails with an error: `Missing container: other bookmarks`

**How can the issue be reproduced?**
1. Unzip the xBrowserSynch v1.5.2-beta1 chrome extension.
2. Install brave-browser-beta (See <https://brave-browser.readthedocs.io/en/latest/installing-brave.html#beta-channel-installation>)
3. Open brave-browser-beta executable (separate from the brave-browser-stable or other executable).
4. Navigate to <about:extensions> (which is an alias for <chrome://extensions/>)
5. Turn on "developer mode" switch at top right.
6. Click "Load Unpacked"
7. Choose the directory that is the unzipped extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/7557867/76551519-d3718f80-6469-11ea-91e3-6aa72b264d0e.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Fedora 31
 - Browser: Brave (beta)
 - Version: Version 1.5.108 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)

**Application log**
<details>
<summary>Log entries</summary>
If this is not sufficient information, tell me what and where information can be gathered.

```
Missing container: other bookmarks
```
@Rob4226 provides a full log containing the error, along with some details, here:https://github.com/xbrowsersync/app/issues/100#issuecomment-571476516 
</details>

**Comment by nero120** [comment]
@poikilos see the later posts in #100, you need to be using brave v1.7.x (which is only currently available from the nightly build).

**Comment by cordova69** [comment]
I'm at Version 1.71.114 Chromium: 
"130.0.6723.58 and getting the [warn]	Missing container: other bookmarks
bookmarks.sync: [10113] LocalContainerNotFound"
Tried to create a new profile and when syncing you receive:  Unexpected bookmarks structure
