### ISSUE TITLE
Browser crash with large number of bookmarks to up-sync.

### ISSUE THREAD

**Issue by jdevl32** [xbrowsersync/app#170]
**Describe the issue you are experiencing**
A clear and concise description of your issue:

Initially I had noticed that my bookmarks had been reduced from ~1780 down to ~200.  Firefox apparently has a built-in backup of the last ~15 revisions to bookmarks and saves them as restore points.  Checking the timestamps, it appears that the bookmark lossage happened around 3/12.  I was able to restore my bookmarks from backup to the original ~1780.  However, when xbs tries to sync back up, it causes the browser to freeze up.  Perhaps it is too large a number to queue up and sync.  I've disabled xbs for the time being, and at least I have my bookmarks restored.  I think I may try to slice up my current bookmark set into smaller chunks to see if I can get xbs to successfully sync back up.

**How can the issue be reproduced?**

I can reproduce this every time by re-enabling xbs and attempting to sync up the ~1780 bookmarks.  Although I haven't tried directly, I think these steps should be able to simulate:

1. Delete all bookmarks.
2. Offline, create a large bookmark file ("large" for this issue is 1500+).
3. Import bookmark file into the browser.
4. Browser comes to a halt on the order of 10s of seconds after xbs attempts to sync up.

**Screenshots**
If applicable, add screenshots to help explain your problem:
N/A

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser: Firefox
 - Version: v1.5.1

**Mobile device**
Please complete the following information for all affected mobile devices:
N/A

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
```
</details>

Log is too large to paste (exceeds character limit), so I've attached:

[xbs_log_20200318165452.txt](https://github.com/xbrowsersync/app/files/4351614/xbs_log_20200318165452.txt)

**Comment by jdevl32** [comment]
To clarify, the browser needs to be force quit and restarted, and the xbs sync up never succeeds.

**Comment by JMS11890** [comment]
I just had the same issue; I did not have that much bookmarks but maybe 100 and I lost maybe 40% of them just today.
I just opened my browser and after some time I noticed that some of them are missing from the bar up top.
cheers guys

**Comment by nero120** [comment]
@JMS11890 are you using Firefox at all? If so you can recover your recent bookmarks using the info [here](https://github.com/xbrowsersync/app/issues/163#issuecomment-600851798).

**Comment by JMS11890** [comment]
Thanks Rich: I recovered everything from a second pc by disconnecting network cable before switching it on and exporting them but good suggestion yours as well.

**Comment by nero120** [comment]
@jdevl32 can you please update to the latest version ([v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2)). I've added better handling for large number of changes, however ultimately the browser itself is the limiting factor so attempting to make thousands of changes at once is probably asking far too much of Firefox! I've noticed Chromium code is far better and will handle many changes much better and faster than Firefox.

Anyways, give v1.5.2 a try and see if it improves things.

**Comment by nero120** [comment]
Going to close this due to lack of activity, however feel free to respond if needed.
