### ISSUE TITLE
Issue with Bookmarks disappearing

### ISSUE THREAD

**Issue by peperami97** [xbrowsersync/app#171]
**Describe the issue you are experiencing**

Have a problem where all my bookmarks have disappeared after the update today.  I have a backup of my Bookmarks file in chrome.  However when I try to copy the original bookmarks back to chrome it doesnt update.

**How can the issue be reproduced?**

Performing a sync clears my bookmarks

**Desktop browser**

 - OS:  Win10
 - Browser Chrome
 - Version Version 80.0.3987.149

- OS Linux
- Browser Chrome
- Version Unstable

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

[xbs_log_20200323092418.txt](https://github.com/xbrowsersync/app/files/4368547/xbs_log_20200323092418.txt)
</details>

**Comment by nero120** [comment]
@peperami97 sorry about this, the issue with bookmarks being deleted is a known issue in v1.5.1. I have a fix for it but with everything happening at the moment I haven't had much time to work on xbs, I'm back on it now so hoping to have a new release out within a week or so. Bear with me.

**Comment by nero120** [comment]
This issue is resolved by 024e32ea622aa2ff3a938538ce2378cb0af511a2.

**Comment by nero120** [comment]
[v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2) has now been released that includes a fix for this issue.
