### ISSUE TITLE
Chrome/Edge Extension pop-up window does not adjust accordingly when zoom level is not 100%

### ISSUE THREAD

**Issue by ElTopo** [xbrowsersync/app#173]
**Describe the issue you are experiencing**
Chrome/Edge Extension's pop up window does not adjust accordingly with browser's zoom level other than 100%, user has to scroll right to see some icons (bookmark, settings)

**How can the issue be reproduced?**
Steps to reproduce the behavior for Microsoft Edge (chromium):
1. Go to menu "Settings" / "Appearance"
2. Adjust "Zoom" level to 100% or 150%
3. Click on XBrowserSync icon and check the extension's pop up window

**Screenshots**
When Zoom level is set to 100%:
![Screenshot - 3_31_2020 , 11_39_48 AM](https://user-images.githubusercontent.com/217195/78063923-cd265300-7345-11ea-9c74-fa438c7a3bc9.png)

When Zoom level is set to 150%
![Screenshot - 3_31_2020 , 11_36_30 AM](https://user-images.githubusercontent.com/217195/78063971-de6f5f80-7345-11ea-8c2d-e229fe47f2c7.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser Microsoft Edge
 - Version 80.0.361.69 (Official build) (64-bit)

**Comment by nero120** [comment]
@ElTopo after doing some testing on this issue, unfortunately there's nothing I can do to avoid scroll bars when you use browser zoom. There is no functionality I can use to properly detect or adjust layouts for browser zoom that will avoid scroll bars completely. Whilst I am making some changes to use more relative units when setting layout dimensions which will help in some cases, it won't resolve all sadly.

I will relate the changes to this issue once they are committed but I am now going to close it as above.

**Comment by nero120** [comment]
[v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2) has now been released that includes a partial fix for this issue.

**Comment by ElTopo** [comment]
@nero120 I updated to v1.5.2 today and this issue seems fixed and I am satisfied, thanks.

**Comment by nero120** [comment]
Great stuff @ElTopo, glad to hear it!
