### ISSUE TITLE
Getting notification from Chrome

### ISSUE THREAD

**Issue by zeroarst** [xbrowsersync/app#176]
**Describe the issue you are experiencing**
I see the notification keeps popping up from Chrome in Windows 10.
And after it shows, it re-syncs all my bookmarks. 
And the process repeats forever.
I also use this extension on my Firefox which works OK.
I also tried to disable Bookmarks sync in Chrome settings but no luck.

**How can the issue be reproduced?**
Install XBrowserSync on Chrome

**Screenshots**
![2020-04-09 11_38_10-Program Manager](https://user-images.githubusercontent.com/1834837/78849110-e4a4c080-7a56-11ea-9358-83d8b1f5b067.png)
![2020-04-09 11_41_38-Settings - Sync and Google services](https://user-images.githubusercontent.com/1834837/78849193-1ae24000-7a57-11ea-9a35-eb1746e3f466.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser: Chrome
 - Version: v.1.4.0

I don't know where to find the log for Chrome?
**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by zeroarst** [comment]
It looks ok now...I tried to disable this extension, disabled Chrome Bookmarks sync. then turn this extension back on...and now no more notifications...
I will leave it for now to see.

**Comment by nero120** [comment]
@zeroarst please update to the latest version ([v1.5.2](https://github.com/xbrowsersync/app/releases/tag/v1.5.2)) and report back!

**Comment by nero120** [comment]
No recent response so closing this.
