### ISSUE TITLE
1.5.2 - Works great on FF + Andorid

### ISSUE THREAD

**Issue by vsatmydynipnet** [xbrowsersync/app#177]
In times like this there a short break to say thank you  for the 1.5.2 update must be allowed even this is an issue tracker. 

Installed on LInux/FF + LineageOS 16/ Android 9. Looks great  again, also non standard port works fine.

Thank you very much and stay healthy!

**Comment by nero120** [comment]
@vsatmydynipnet thank you for this, consider the cockles of my heart warmed! Glad it's all working well for you now. If nothing else, lockdown has given me a chance to get lots of xBrowserSync work done! Stay safe! 😷
