### ISSUE TITLE
when opening the app show folder list instead of "add bookmark" dialog

### ISSUE THREAD

**Issue by sviluppoSoftware** [xbrowsersync/app#178]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is:

Is your feature request related to a problem? no

**Tell us about your idea**
Use screenshots and links to help illustrate if relevant:

when opening the app, show folder list instead of "add bookmark" dialog, the reason is to make bookmark access faster, it would also be even more efficient show the bookmarks of a specific folder when the app starts, for example always show the bookmarks of the "toolbar bookmarks"  folder

thank you for your job :)

**Comment by nero120** [comment]
@sviluppoSoftware I'll aim to add a preference in the next version that will allow you to default to folder view as it's not much effort. Selecting a specific folder to open by default is more complex and will need to wait until other high priority features have been implemented.
