### ISSUE TITLE
[Chrome] bookmarks.getSubTree: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by joeytwiddle** [xBrowserSync/App#18]
### Steps to reproduce
1. Have a lot of bookmarks (around 14,900, 6MB when saved as HTML)
2. Start a new sync
3. Switch to a different app while the sync is happening, e.g. focus a terminal app instead of Chrome

### Expected behaviour
The sync should keep going!

### Actual behaviour
xBrowserSync's popup window disappears, and the sync aborts.  (I assume that because CPU usage drop to 0.)
The API server's `bookmarks` collection still has 0 documents.
However the extension icon does show a "progress" (cycling arrows) symbol.  That suggests it is still working, but I don't believe it is.

### Client app information
**App Platform:** Google Chrome under Linux (Ubuntu 14.04 using Fluxbox window manager)

**App Platform Version:** 1.1.2

#### Other info
I am using my own API server, with the limit set to 10MB.

We need to run the sync in the background, so it won't be interrupted by navigation.

If I can't switch to a different tab or a different app, then my computer is unusable while the sync is happening!

And I have no idea how long the sync will take.  So it would also be great to show a progress bar.

**Comment by joeytwiddle** [comment]
Actually I'm not even sure if it's working at all.  I left it running for hours but it's still using 80% CPU and displaying this message:

> Working on it... Don't close the window yet

Nothing logged on the back-end and the `bookmarks` collection is still empty.

**Comment by nero120** [comment]
@joeytwiddle could you open [chrome://extensions/](chrome://extensions/) and under xBrowserSync, click on the "background.html" link - that will open up the Developer Tools window and in the Console you should see (I expect many) warnings and errors.

This will store all historical messages, so could I trouble you to clear the current messages then run the sync again? If you can then post here any errors that appear that would be really useful!

**Comment by joeytwiddle** [comment]
Thanks, background.html is a good trick to know!

```
background.html:1 Error in response to bookmarks.getSubTree: TypeError: Cannot read property '0' of undefined
    at Object.callback (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2857:30)
    at getLocalBookmark (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2856:30)
    at Object.getBookmarks [as Get] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2515:29)
    at sync_handlePush (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2006:47)
    at sync (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1782:27)
```

According to the sourcemap, that is the `if` here:
```js
            chrome.bookmarks.getSubTree(localBookmarkId, function(results) {
                if (!!results[0]) {
                    deferred.resolve(results[0]);
                } else {
                    deferred.reject({
                        code: globals.ErrorCodes.FailedGetLocalBookmarks
                    });
                }
            });
```

I'm a bit busy tonight but perhaps tomorrow I can get a local copy of the extension running, and help to debug.  Cheers!

**Comment by nero120** [comment]
Strange, I would have expected `results` to never be null, it should return an array that includes the bookmark who's id was supplied as the parameter. The id is retrieved directly from the chrome API so unless there's a corruption in your local bookmarks I'm stumped as to why that should be occurring...

From a code perspective it's an easy fix, just add a null check to `results`, but without understanding the underlying issue it may lead to unexpected results.

**Comment by nero120** [comment]
@joeytwiddle are you still experiencing this issue? Is there any chance you could test this using the [v1.4.0 beta](https://github.com/xBrowserSync/App/releases/tag/BETA1)? If so I can bump up the sync limit on [api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/) to 10MB for the test.

**Comment by nero120** [comment]
Closing this as I believe it's resolved in the [beta](https://github.com/xBrowserSync/App/releases/tag/BETA1), feel free to re-open if necessary.
