### ISSUE TITLE
Could be improved android chrome support

### ISSUE THREAD

**Issue by Manu99it** [xbrowsersync/app#181]
Actually the android app is "ok". But what on supporting chrome on mobile? I know chrome doesn't supports extensions, but that could be circumvented by using root and edit bookmarks file at /data/data/com.android.chrome/app_chrome/default/bookmarks

Would be great!

**Comment by nero120** [comment]
I appreciate the thought but mobile browsers are not something I'm planning on supporting at this time, perhaps at some point in the future.
