### ISSUE TITLE
Android dark theme

### ISSUE THREAD

**Issue by coreyfarrell** [xbrowsersync/app#182]
**Is your feature request related to a problem?**
Nearly all apps on my phone are now operating in dark mode, it would be really nice if xBrowserSync could do the same.

**Tell us about your idea**
I'm not a designer so my best idea is just gray scale color scheme with all dark backgrounds.  It would be nice if xBrowserSync respected the global dark mode option but even being able to manually set this in the app would be great.

**Comment by nero120** [comment]
Good idea @coreyfarrell, I'll see what I can do.
