### ISSUE TITLE
 Alternate search view quirks

### ISSUE THREAD

**Issue by kkuhle** [xbrowsersync/app#183]
1. Go to Settings and turn on "Alternate search view" 
2. Click "Find a bookmark"

## two observations:

- The text box will be halfway covered by Gboard
- results are not visible until closing the keyboard

## device info:

 - Device: OnePlus 6t
 - OS: Android 10 Havoc OS

Xbookmarks gboard hiding search box: https://imgur.com/gallery/DwGuD8j

keyboard showing: https://imgur.com/gallery/r07LpDu

Keyboard minimized: https://imgur.com/gallery/lsaTWwN

**Comment by nero120** [comment]
@kkuhle I'm using gboard on Android 10 and not seeing this:

![image](https://user-images.githubusercontent.com/4236238/80655167-e1a95880-8a75-11ea-9081-f3cbbb3083fe.png)

Can you post screenshots?

**Comment by kkuhle** [comment]
Sorry for the delay.  I've added screenshots to the OP.

**Comment by nero120** [comment]
@kkuhle I can't replicate this at all. To check if it's the device or something with gboard, could you please try installing the swiftkey keyboard and see if that resolves the issue?

**Comment by kkuhle** [comment]
Same behavior with SwiftKey

**Comment by nero120** [comment]
I'm guessing it's the same with [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard)?

I can't replicate this sadly, my guess is it's specifically due to the way OnePlus sets the height of the visible screen area when the soft keyboard is present. Not something I can fix I don't think, sorry.

**Comment by kkuhle** [comment]
No worries! I guess it's rare as no one else has commented and you can't dupe.  I'll use the regular search view. Thanks for the terrific app!

**Comment by nero120** [comment]
This is also being tracked in #263.
