### ISSUE TITLE
Feature Request: Support Basic Authentication in front of server

### ISSUE THREAD

**Issue by berlincount** [xbrowsersync/app#186]
**Is your feature request related to a problem?**

When running the xBrowserSync API behind a Reverse Proxy requiring Basic Authentication, Synchronization fails unless a separate Tab was / has logged in to the xBrowserSync API site before - Header Modification Extensions don't help. If this was not done, the local sync is logged out, requiring a full overwrite of local Bookmarks on next sync.

**Tell us about your idea**

Add a configuration option, entry field or dialog to provide Basic Authorization information when needed.

**Comment by nero120** [comment]
@berlincount I missed the fact that there is already a feature request that covers this (#29), so I'm going to close this issue.

**Comment by berlincount** [comment]
Please note that #29 is covering the same issue for the (Android) mobile version.
