### ISSUE TITLE
Update 1.5.2.1 and AMO

### ISSUE THREAD

**Issue by crssi** [xbrowsersync/app#189]
The extension version 1.5.2 installed from AMO, is reporting newer version 1.5.2.1.
Version 1.5.2.1 is not (yet) available on AMO.

Cheers

**Comment by nero120** [comment]
@crssi what is AMO?

**Comment by crssi** [comment]
Sorry... AMO = Addon Mozilla page... see https://wiki.mozilla.org/index.php?title=AMO

Cheers 😄

**Comment by nero120** [comment]
@crssi where is the reference to 1.5.2.1?

**Comment by nero120** [comment]
@crssi ah I see, the update notification is reporting a new version available. Ignore it, I had to release a new version to fix Android F-Droid build issues. That release is not for other platforms.

**Comment by crssi** [comment]
Sorry... next time I will try to be more thorough and specific.
I am ignoring it, just wanted you to know about a "problem", which is really not critical.

Cheers

**Comment by nero120** [comment]
@crssi much appreciated!

**Comment by crssi** [comment]
Thank you for the project.
