### ISSUE TITLE
Problems with regenerator-transform while compiling

### ISSUE THREAD

**Issue by joeytwiddle** [xBrowserSync/App#19]
I have been trying to build the Chrome extension here on Ubuntu.  I get the following error:
```
> xbrowsersync-app@1.3.1 copyfiles /home/joey/SYNC/src/xBrowserSync-App
> cross-var n-copy --source $npm_package_config_platformPath --destination build "*" "**/*" && n-copy --source . --destination build "app.html" "css/*" "img/*" "fonts/*" "views/*" && n-copy --source fonts --destination build/fonts "**/*" && n-copy --source node_modules/font-awesome/fonts --destination build/fonts/font-awesome "**/*"

/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-runtime" specified in "/home/joey/SYNC/src/xBrowserSync-App/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/home/joey/SYNC/src/xBrowserSync-App/node_modules/regenerator-transform" (While processing preset: "/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-preset-es2015/lib/index.js")
    at /home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
```

I can actually fix that error by running:
```sh
( cd node_modules/regenerator-transform && npm install )
```

But then I get another error:
```
/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to /home/joey/SYNC/src/xBrowserSync-App/node_modules/regenerator-transform/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/home/joey/SYNC/src/xBrowserSync-App/node_modules/regenerator-transform/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/home/joey/SYNC/src/xBrowserSync-App/node_modules/regenerator-transform/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-preset-es2015/lib/index.js")
    at /home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/joey/SYNC/src/xBrowserSync-App/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
```

I have tried with node v8.9.3 and node v10.1.0 and npm v5.4.1 and npm v6.1.0.  Using nvm here.  Also tried with yarn a bit.  Consistently got the same results.

I did get a couple of warnings from npm:
```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```
and
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

May I ask:
- What platform are you using?  (I could also try on the Mac I have at work.)
- What versions of node and npm are you using?
- Do you have a `package-lock.json` or a `yarn.lock` file you could share with me?

(I recommend adding `package-lock.json` to the repository, just as a history of which packages worked when.  You can remove it and rebuild it whenever you like.)

**Comment by nero120** [comment]
Unfortunately there wasn't a `package-lock.json` for the current version, it's something I'm currently addressing. Those errors you're getting are from dependencies as xBrowserSync doesn't directly depend on babel, nor use `prepublish` scripts.

I'll have these dependency issues resolved when I release the next version, which will include a `package-lock.json`. Apologies for the trouble!

(btw, the build should work both on Windows and Linux as I use both platforms)

**Comment by nero120** [comment]
Just ran the following on my windows box:

```
npm install
npm run build:chrome
```

and the build ran successfully. Could be a linux issue, try running `npm install --unsafe-perm` then re-run the build.

**Comment by joeytwiddle** [comment]
I tried on my MacBookPro and got the same errors! (`--unsafe-perm` also the same.)

So I would urge you to keep good backups of your node_modules folder etc., because there might be something magical happening on your machine! ;-)

The [same bug](https://github.com/elijahmanor/cross-var/issues/15) has been reported on the `cross-var` repo, but no solutions yet.

I tried a couple of fixes, but still can't get past the `{loose: true}` error.

(Adding `babel-plugin-transform-runtime` to our `package.json` does get past the first error message, although I do appreciate that should not be the responsibility of this app! An alternative is to move it from `devDependencies` into `dependencies` in `cross-var`'s `package.json`, and then do a similar fix for `babel-plugin-transform-flow-strip-types` in `babylon`'s `devDependencies`. For some reason npm isn't pulling in the devDependencies of child modules even when I ask it to!)

I notice you are pinned to `cross-var=1.0.3` but I tried with [the latest](https://www.npmjs.com/package/cross-var) `1.1.0` with no improvement. Babylon uses [**`cross-env`**](https://www.npmjs.com/package/cross-env) which is very popular, so might be an alternative solution worth trying.

**Comment by nero120** [comment]
Great work @joeytwiddle! Are you up for replacing [`cross-var`](https://www.npmjs.com/package/cross-var) with [`cross-env`](https://www.npmjs.com/package/cross-env) and submitting a pull request? I've switched the default branch to [`v1.4.0`](https://github.com/xBrowserSync/App/tree/v1.4.0), would you be able to switch to this branch and then submit the change, if so I can test the change on my Windows machine and then incorporate it with the upcoming release.

**Comment by joeytwiddle** [comment]
I will have a try, so that you can get back to the Firefox addon. :sunglasses:

**Comment by joeytwiddle** [comment]
Oh, I think I know why these packages can't find their dependencies.

It's because I am using the latest versions of npm and yarn, which _flatten the module tree_.

I suspect these packages are trying to load things specifically from deep node_modules folders, e.g. doing `require('../node_modules/' + pluginName)` instead of just `require(pluginName)`. That would have worked before flattening.

If there is no way to disable flattening in npm/yarn, I will try an older version of npm. (You never did tell me what version you are using, but I'm guessing it's not recent!)

**It would be good to document in the README what is the recommended development environment (node and npm versions).**

(I like using [`nvm`](https://github.com/creationix/nvm) to have different versions of node installed on Linux/Mac.)

**Comment by nero120** [comment]
Hmm, I'm actually on Node LTS (v8.11.1) and npm v6.1.0 and I'm not having this issue, I need to give it a try on my laptop running Ubuntu. Since it is working on Windows with latest npm I would suspect it is more of a package issue as you previously mentioned rather than an inherent npm issue?

**Comment by nero120** [comment]
@joeytwiddle I believe this issue has been resolved with the most recent commit. I've tested on an Ubuntu box with the following specs:

- Ubuntu 16.04.4 LTS
- Node v9.10.1
- NPM v6.0.0

If you get a chance could you clone the most recent [v1.4.0](https://github.com/xBrowserSync/App/tree/v1.4.0) to a **new dir**, then run `npm install` and `npm run build:chrome` and see if you get any errors?

I'm going to close this for now, I'll re-open if you still have problems after the latest commit.

If you do get around to creating a pull request to switch from using `cross-var` to `cross-env` that would be great, otherwise I'll add it to my list of dependencies to evaluate after v1.4.0 has been released. 😄

**Comment by nero120** [comment]
I decided to just do the replacement as it was quick enough, in 8c701c1.

**Comment by joeytwiddle** [comment]
Out of interest, I tried with node v8.9.3 and npm v5.4.0. The installation and the build passed with no warnings or errors!

The build took only 17 seconds, outputting 52 files.

Thanks for this nero120. The ability to compile it makes it much more likely that I will contribute in future!

**Comment by nero120** [comment]
Great stuff @joeytwiddle, thanks for testing it!
