### ISSUE TITLE
Unexpected bookmarks structure during initial setup

### ISSUE THREAD

**Issue by tmatijevich** [xbrowsersync/app#190]
**Describe the issue you are experiencing**
Initial sync results in "Unexpected bookmarks structure".
The log says I'm missing container other bookmarks, The other bookmarks folder is present, but empty. Certainly not missing.

**How can the issue be reproduced?**
1. Add xBrowserSync extension from the Chrome Web Store
2. Gives permissions
3. Follow guide
4. Enter new sync password

**Screenshots**
![image](https://user-images.githubusercontent.com/33841634/81311069-8c0f1600-904a-11ea-8e1a-255530a73c63.png)
![image](https://user-images.githubusercontent.com/33841634/81311931-9e3d8400-904b-11ea-9889-37758baebd0d.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser: Chrome
     - Version 81.0.4044.129 (Official Build) (64-bit)

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2020-05-07 14:55:53.372	[warn]	Missing container: other bookmarks
2020-05-07 14:56:37.327	[error]		Error: [10006] DailyNewSyncLimitReached at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at XMLHttpRequest.y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2020-05-07 14:57:31.779	[trace]	Starting up
2020-05-07 14:57:31.798	[trace]	{"checkForAppUpdates":true,"displayHelp":false,"displayOtherSyncsWarning":false,"displayPermissions":false,"syncBookmarksToolbar":true,"appVersion":"1.5.2","platform":{"name":"chrome","version":"81.0.4044","mobile":false,"os":"Windows 10"}}
2020-05-07 14:57:36.988	[trace]	v1.5.2.1 update available
2020-05-07 15:00:13.378	[trace]	Service url changed to: https://xbrowsersync.burrows.xyz
2020-05-07 15:00:33.150	[trace]	Service url changed to: https://xbs.25mb.co.uk
2020-05-07 15:01:01.144	[trace]	Sync jsmizm (push) queued
2020-05-07 15:01:01.149	[trace]	Processing sync jsmizm (0 in queue)
2020-05-07 15:01:01.228	[warn]	Missing container: other bookmarks
2020-05-07 15:01:01.237	[trace]	Sync jsmizm failed
2020-05-07 15:01:01.244	[error]	bookmarks.sync: [10113] LocalContainerNotFound
```
</details>

**Comment by nero120** [comment]
@tmatijevich I need more info to figure out what's going on here, can you do the following please:

- Browse to chrome://extensions 
- Toggle the "Developer mode" switch to enabled
- Under xBrowserSync in the list of extensions, click on background.html where it says "Inspect views"
- The console tab should be visible in the DevTools window, paste the following code and copy the results here:

```
chrome.bookmarks.getTree(x => console.log(JSON.stringify(x)));
```

I really just need to see the property values for the bookmarks bar Anna other bookmarks nodes, so feel free to delete the rest of your bookmarks before posting here.

**Comment by tmatijevich** [comment]
Not a problem, 

```JSON
[
  {
    "children": [
      {
        "children": [
... my bookmarks ...
        ],
        "dateAdded": 1581367543791,
        "dateGroupModified": 1582037089938,
        "id": "1",
        "index": 0,
        "parentId": "0",
        "title": "Bookmarks bar"
      },
      {
        "children": [],
        "dateAdded": 1581367543791,
        "id": "616",
        "index": 1,
        "parentId": "0",
        "title": "Other bookmarks"
      }
    ],
    "dateAdded": 1588942381538,
    "id": "0",
    "title": ""
  }
]
```

**Comment by nero120** [comment]
@tmatijevich there's the problem, the `id` of other bookmarks is `616` when it should be `2`. I've seen this happen now and again, I'm pretty sure it's a bug in chromium.

The way to fix it is to either edit the `bookmarks` file in your profile directory and change the id manually or to create a new profile.

**Comment by tmatijevich** [comment]
My bookmarks bar begins with a folder "Google" (ID #2)

```JSON
            ],
            "dateAdded": 1582037088634,
            "dateGroupModified": 1582037088649,
            "id": "2",
            "index": 0,
            "parentId": "1",
            "title": "Google"
          },
```

The first bookmark in the first folder has ID #3.

```JSON
            "children": [
              {
                "dateAdded": 1582037088637,
                "id": "3",
                "index": 0,
                "parentId": "2",
                "title": "Google",
                "url": "https://www.google.com/"
              },
```

So does every ID have to be re-ordered?

**Comment by nero120** [comment]
@tmatijevich hmm yes that's true. It's probably easier to create a temporary profile and use xBrowserSync to sync your bookmarks into that profile, then copy the contents of the `bookmarks` file back to your original profile.

**Comment by tmatijevich** [comment]
Excellent, now it is working.
Copy+paste bookmarks bar from original profile to new profile does the trick:
```JSON
         } ],
         "date_added": "13233435235928897",
         "date_modified": "13233437023564780",
         "guid": "00000000-0000-4000-a000-000000000002",
         "id": "1",
         "name": "Bookmarks bar",
         "type": "folder"
      },
      "other": {
         "children": [  ],
         "date_added": "13233435235928901",
         "date_modified": "0",
         "guid": "00000000-0000-4000-a000-000000000003",
         "id": "2",
         "name": "Other bookmarks",
         "type": "folder"
      },
      "synced": {
         "children": [  ],
         "date_added": "13233435235928902",
         "date_modified": "0",
         "guid": "00000000-0000-4000-a000-000000000004",
         "id": "3",
         "name": "Mobile bookmarks",
         "type": "folder"
      }
   },
   "version": 1
}
```

I have been manually backing up `Chrome\User Data\Default\Bookmarks` on multiple computers and using git to merge them together. After a merge, Chrome likes to re-ID all the bookmarks which resulted in the "other bookmarks" being something other than ID `#2`.

`xBrowserSync` will be less work and better performance. Having the temporary profile trick is a suitable workaround when the bookmarks structure is corrupt (will backups). 

Thanks for your support, and for the app!

**Comment by nero120** [comment]
Glad it's sorted @tmatijevich! 😄

**Comment by bitphage** [comment]
> @tmatijevich hmm yes that's true. It's probably easier to create a temporary profile and use xBrowserSync to sync your bookmarks into that profile, then copy the contents of the `bookmarks` file back to your original profile.

Did't figured out how to use xBrowserSync to sync from main profile to a temporary, but did another trick:
1. In the main profile go to bookmarks manager, and export bookmarks to a file
2. In the temp profile go to bookmarks manager, and import from that file
3. Move all bookmarks from "Imported" to "Other bookmarks"
4. Copy `Bookmarks` file from the temp profile to the main.
