### ISSUE TITLE
Unable to delete bookmarks with no name/title

### ISSUE THREAD

**Issue by javmorin** [xBrowserSync/App#2]
### Steps to reproduce
1. Add bookmark to bookmark bar with no name/title (dragging a link from the chrome start page will do this
2. Attempt to delete this link

### Expected behaviour
- Link is removed and a sync occurs

### Actual behaviour
- Dialog pops up indicating "Last change not synced" due to a bookmarks conflict and suggesting disabling and re-enabling sync
- Link is removed locally, but change is not synced to API

### Client app information
**App Platform:** Chrome

**App Platform Version:** 57.0.2987.21 beta

**Comment by nero120** [comment]
Thanks for logging this, funnily enough I'm currently working on a fix for this exact problem. Will hopefully release within a week or two.

**Comment by nero120** [comment]
Fixed in v1.2.1 available on Chrome store now.
