### ISSUE TITLE
High Ram usage during sync (firefox)

### ISSUE THREAD

**Issue by baraa272** [xbrowsersync/app#200]
**Describe the issue you are experiencing**
A clear and concise description of your issue:

during Sync the extension cause very high ram usage about 2gb of RAM and somewhat of cpu usage like 25%
this doesnt happen while extension disabled 

**Screenshots**
If applicable, add screenshots to help explain your problem:
Screenshot included 
![lol](https://user-images.githubusercontent.com/32843097/83816831-d8ce2700-a6b2-11ea-8666-f90f5bb5d8f5.PNG)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: win 10 LTSC 1809
 - Browser Icecat (firefox) 
 - Version 68.8.0

**Application log**
Please include the logs from the affected clients:
included in attachments 
[xbs_log_20200604222525.txt](https://github.com/xbrowsersync/app/files/4732982/xbs_log_20200604222525.txt)

**Comment by nero120** [comment]
@baraa272 your log shows a huge number of syncs (239) starting from `2020-06-02 21:30:59.300`. Be aware that the more simultaenous syncs you trigger the more memory is going to be consumed, and Firefox is not particularly efficient at the best of times in my experience.

I'm going to close this as there's not much I can do to reduce the amount of resources consumed if you trigger hundreds of syncs, it's just beyond what an extension is capable of controlling.
