### ISSUE TITLE
Vivaldi sync issue

### ISSUE THREAD

**Issue by userdaphi** [xbrowsersync/app#201]
If I sync from **Firefox** to **Vivaldi** -> Toolbar will get synced from FF to Vivaldi, but FF-bookmark menu will get trashed in Vivaldi
If I sync from **Vivaldi** to **Firefox** -> The whole set of bookmarks lands in the FF-Toolbar. FF-bookmark menu stays empty.

**Comment by rodrigoswz** [comment]
Yeah, same thing here. Vivaldi is a mess with his bookmarks organization and Speed ​​Dial.

I don't know if this is something that should be fixed by the browser itself or if xBrowserSync can do something to fix it.

**Comment by nero120** [comment]
Vivaldi is not currently supported! See #6 for more info.
