### ISSUE TITLE
F-Droid link is dead

### ISSUE THREAD

**Issue by lrq3000** [xbrowsersync/app#202]
**Describe the issue you are experiencing**
The link on [F-Droid is dead](https://f-droid.org/en/packages/com.xBrowserSync.android/).

**Comment by nero120** [comment]
Thanks @lrq3000, this is a known issue with the FDroid build and is still in the process of being resolved by the FDroid guys. Follow #165 for more info.

**Comment by lrq3000** [comment]
Ah ok, it wasn't clear from the other issue that the build issues prevented the older packages from appearing on F-Droid, thank you for linking the other issue.
