### ISSUE TITLE
Sync error when sorting favourites or making multiple changes at one time

### ISSUE THREAD

**Issue by doulouz** [xbrowsersync/app#204]
I systematically get "Sync error - local data has been refreshed - redo changes" every time I sort favourites through other add-ins such as SuperSorter (but other sorting add-ins will result in same error).

I also get the same sync error if I attempt to make "too many" changes in my favourites at once i.e., create a new folder, move some favourites in the newly created folder than move that folder to another folder will often throw out the error. It seems sync is very sensitive to that and I always need leaden feet before making multiple changes.

**Comment by laurin1** [comment]
Yea, I did this yesterday, and today, every browser on every machine that I have using xBrowserSync is now doing "Sync error - local data has been refreshed - redo changes" and "Sync conflict detected" over and over again. I've tried restoring from backup, but that does not fix the issue.

**Comment by laurin1** [comment]
I found my issue - somehow, I was allowed to add a bookmark by the same name twice...or xBrowserSync duplicated it.

![image](https://user-images.githubusercontent.com/75857/84567934-b175fa80-ad41-11ea-87ab-a09ff9911598.png)

**Comment by nero120** [comment]
In v1.5.2, bookmark sorters are not supported and will cause sync issues (see #120). I'm also aware of the other issue regarding making multiple changes. Rest assured that I've already fixed these issues for the upcoming v1.5.3 and you'll be able to use bookmark sorters after that version is released. 😄 

I'm going to close this as its a duplicate but feel free to respond if you have any further issues.
