### ISSUE TITLE
All Bookmarks are now duplicated

### ISSUE THREAD

**Issue by aliabianco** [xbrowsersync/app#205]
Hi,

All Bookmarks are now duplicated.

Apreciate any suggetions,

Thanks

**Describe the issue you are experiencing**
A clear and concise description of your issue:

**How can the issue be reproduced?**

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: [e.g. Win10]
 - Browser [e.g. Chrome, Firefox]
 - Version [e.g. v1.5.0]

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: [e.g. Samsung Galaxy S10]
 - OS: [e.g. Android 9 Pie]
 - Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by nero120** [comment]
No info provided.
