### ISSUE TITLE
[Browser] Let us choose at the first configuration what folder we want to sync

### ISSUE THREAD

**Issue by aelisya** [xbrowsersync/app#208]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is:

It's very annoying to have to sync all my bookmark since i only want one folder to be synced on the cloud

**Tell us about your idea**
Let us choose during the first configuration what is the "root" folder we want to sync.

**Comment by nero120** [comment]
#26 covers this functionality so I'll close this.
