### ISSUE TITLE
Camera-less android devices can not be setup.

### ISSUE THREAD

**Issue by kainz** [xbrowsersync/app#209]
**Describe the issue you are experiencing**
The mobile xBrowserSync app should allow manual entry of a sync id in the event your device does not have a camera.

**How can the issue be reproduced?**
1. Go to 'xBrowserSync android app on new installanion'
2. Unable to setup sync w/o a camera

**Mobile device**
 - Device: Onyx Boox series android readers, likely other android e-ink devices that dont package a camera.

**Comment by nero120** [comment]
@kainz I've already implemented this in dev and will be included in the upcoming release.

**Comment by nero120** [comment]
Resolved by 659cf5701bea25c050f3ed6172150bd4331086c5.

**Comment by kainz** [comment]
I have tested the manual sync detail entry in 1.6.0-beta.22, and it works fine on the devices I've gotten to test.

**Comment by nero120** [comment]
Excellent, many thanks @kainz!
