### ISSUE TITLE
Enhancement/bug - Add manual sync button on App

### ISSUE THREAD

**Issue by cjnaz** [xbrowsersync/app#21]
If I update (add a tag) to a bookmark in Chrome on one machine the change gets pushed to the server (as indicated by the bookmark toolbar getting rebuilt).  However, on another machine running Chrome the sync does not automatically get triggered.  If I then add a tag to a bookmark on the 2nd machine I get a Data out of Sync warning and lose the local change (the warning message gets clipped).  

How/when does the App check for changes on the server?  

**Enhancement request:**  
1. Add a Force Download or Manual Download button in the App Settings panel to force a sync/download from the server, and call out any sync conflicts.  
2. In the App Setting panel, add the lastUpdated info from the Server/API and the lastUpdated info for the local bookmarks.  Suggest putting this info next to the Force Download button.

### Client app information
**App Platform:**  Chrome on Win10 and Centos7

**App Platform Version:**   1.3.1

#### Other info

Running the API server V1.1.0 on the local Centos machine, with Apps referencing an an external ddns service URL.

**Comment by cjnaz** [comment]
The sync/update eventually made to the 2nd machine.  What is the sync update check period?  The manual sync/download button and lastUpdated display would be helpful.

**Comment by nero120** [comment]
> How/when does the App check for changes on the server?

The app checks every 5 minutes for updates to your synced bookmarks. I think this could be reduced to one a minute to help reduce the risk of conflicts occurring. This would increase the load on the service but shouldn't be an issue.

> Add a Force Download or Manual Download button in the App Settings panel to force a sync/download from the server, and call out any sync conflicts.

I agree there should be a better interface for resolving conflicts, though I'd hope it should be a very edge case especially if the time between checking for updates is reduced.

**Comment by Metal-Frog** [comment]
+1

**Comment by nero120** [comment]
This will be added in the next release (v1.4.1).
