### ISSUE TITLE
Android Kiwi browser Support

### ISSUE THREAD

**Issue by shuvashish76** [xbrowsersync/app#214]
Kiwi is chromium based, & supports extensions. Is it possible to make bookmarks sync through xbrowsersync extension? currently not supporting, it stuck on "Syncing..." logo.

![photo_2020-07-17_10-57-23](https://user-images.githubusercontent.com/48226312/87751731-5a6db480-c81c-11ea-8e87-ca1e48f6ac59.jpg)

**Comment by nero120** [comment]
Please search before raising issues, there's loads regarding Kiwi. Mobile browsers are not supported, use the xBrowserSync mobile app.
