### ISSUE TITLE
User interface disaster

### ISSUE THREAD

**Issue by xpusostomos** [xbrowsersync/app#215]
I've wasted multiple hours of my life trying to figure out how this thing is supposed to work, and I'm tired of it. The user interface is an utter disaster. I have no idea what I'm supposed to do, nothing I try works. What the fields mean, how to get sync working, who knows. And I'm an IT professional. Here's some advice: sit your grandma down in front of this and see how far they get. Nowhere is my prediction.

**Comment by nero120** [comment]
Congratulations, you're the only one in thousands of users who thinks so.
