### ISSUE TITLE
Firefox keywords and tags are lost (used for quick search)

### ISSUE THREAD

**Issue by egabrum** [xbrowsersync/app#219]
**Describe the issue you are experiencing**
Bookmark's keywords and tags are lost.

**How can the issue be reproduced?**
1. Open Firefox
2. Add bookmark:
    Name: Search Yubnub
    Location: https://yubnub.org/parser/parse?command=%s
    Tags: search
    Keyword: y 
3. Sync, or wait until next sync.
4. Open the properties of the bookmark on Firefox
5: Error: Tags and Keyword are empty.

**Desktop browser**
 - OS: Win10
 - Browser Firefox 
 - Version 78.0.2 64b

Addon: xBrowserSync 1.5.2

**Comment by nero120** [comment]
This is a [known issue](https://github.com/xbrowsersync/app/wiki/Known-issues) due to Firefox not implementing an API to access native bookmark tags (and descriptions). xBrowserSync warns you about this in the help content.
