### ISSUE TITLE
[FireFox] Building and running XPI

### ISSUE THREAD

**Issue by Metal-Frog** [xBrowserSync/App#22]
Hi,
I completely new here, so sorry if I'm asking nonsense :).
I've understood that the FireFox extension isn't ready yet. I've built the code and created a XPI by myself - which worked fine. But when I run it, it looks "disturbed" (see attached picture).
Is this the current state of the App in FireFox or does something went wrong with my build?

Best regards, Tom
![xbrowsersyncff](https://user-images.githubusercontent.com/11056711/40222301-56c48f1e-5a7f-11e8-8ee5-bf0688e1c22d.png)

**Comment by nero120** [comment]
Hi @Metal-Frog, yes that's the current state for branch [v1.4.0](https://github.com/xBrowserSync/App/tree/v1.4.0). I'll be commit a change shortly that will resolve this.

**Comment by nero120** [comment]
@Metal-Frog if you get the latest commit you should now be able to add the firefox extension and run it properly. Note that it's not ready to use yet though, and it may cause issues with your existing sync so please don't use it unless you accept it might corrupt your sync data!!

Subscribe to [this issue](https://github.com/xBrowserSync/App/issues/8) to keep up to get notified once it's ready to use.
