### ISSUE TITLE
Infinite sync between 3 browsers

### ISSUE THREAD

**Issue by emamontov** [xbrowsersync/app#224]
**Describe the issue you are experiencing**
Infinite sync between 3 browsers

**How can the issue be reproduced?**
I did the following setup:
Computer1: Chrome (account1)
Computer1: Opera(account2)
Computer2: Chrome (account1)

However after enabling sync on Computer2, it started to sync infinitely.
Note: Both Chrome browsers use the same google account that also sync bookmarks.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser 2 Chromes + 1 Opera
 - Version 

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
[xbs_log_20200802113545 (3).txt](https://github.com/xbrowsersync/app/files/5011890/xbs_log_20200802113545.3.txt)

```
</details>

**Comment by nero120** [comment]
Opera is not currently supported, follow [this issue](https://github.com/xbrowsersync/app/issues/11) to be notified about updates.
