### ISSUE TITLE
Synchronize additional data (tabs, extension, password, history, etc.)

### ISSUE THREAD

**Issue by alfredonodo** [xbrowsersync/app#227]
Hi,
what about synchronizing additional data (tabs, extension, password, history, etc.) across different browser?
Thank you

**Comment by nero120** [comment]
Check the [roadmap](https://github.com/xbrowsersync/app/wiki/Roadmap). Syncing of tabs and history will be implemented, but [not passwords](https://www.xbrowsersync.org/?faqkw=id%253A1#faqs). Syncing of other data is not ruled out but no plans at this time.
