### ISSUE TITLE
Accept self-signed SSL certificate issued by a non-public CA 

### ISSUE THREAD

**Issue by KROSF** [xbrowsersync/app#228]
**Is your feature request related to a problem?**

I'm using my own CA to sign my SSL certificates. This CA is imported in the androids user "trusted credentials". This works perfect for apps via Chrome and other services I use - like bitwarden.

As far as I understand the support of user "trusted credentials" CAs needs to be enabled in the apps security policy:
[developer.android.com/training/articles/security-config.html
](https://developer.android.com/training/articles/security-config.html)
The nextcloud Android App is a working [example](https://github.com/nextcloud/android/blob/5d8dd742ef9bc83ecb95ec7db7fe7af4eedd49cd/src/main/res/xml/network_security_config.xml).

Thx!

**Comment by KROSF** [comment]
Yesterday i build the branch v1.6.0 and didn't work, user certificates are still been invalid, then found [this](https://cordova.apache.org/docs/en/latest/guide/appdev/security/#self-signed-certificates) on cordova docs.

They don't recommend the use of Self-Signed Certificates. 😭

Maybe the issue should be closed.

**Comment by nero120** [comment]
@KROSF ok fair enough, thanks for trying it. Why don't you just use Let's Encrypt CA for your certs? That's what I use for my SSL certs. You can run [certbot](https://certbot.eff.org/) to automatically manage registering and renewing.

**Comment by KROSF** [comment]
I did that using traefik with the dns challenge to avoid open ports.

Thanks.

**Comment by nero120** [comment]
Ok great, I'll rollback these changes.
