### ISSUE TITLE
Bookmarking sites shared from Tor Browser on Android leaks URL over clearnet

### ISSUE THREAD

**Issue by dznsm** [xbrowsersync/app#231]
**Describe the issue you are experiencing**
Sharing site URL from Tor Browser, XBrowserSync fetches site metadata over clearnet before user approves and bookmark is synced, with end 2 end encryption, with a xbrowsersync server.

**How can the issue be reproduced?**
1. Go to a website using Tor Browser for android
2. Click on ⫶ menu button > share > Add Bookmark (with xbrowsersync icon next to it)
3. XBrowserSync opens and fetches metadata over clearnet

 - Tor Browser 
 - Version 68.11.0 (2015691619)

**Mobile device**
 - Device: Pixel 3XL
 - OS: GrapheneOS (AOSP 10)
 - Version [e.g. v1.5.0]

**Comment by dznsm** [comment]
Possible fixes-
* Add a setting to allow users to disable the metadata fetch?  Likely good to have if doing either of the following solutions
* Detect if Tor Browser is installed and either dont fetch metadata, or ask whether XBrowserSync should connect to site to fetch metadata, on receiving the share. Think can do this via the share intent as tor browser has native bookmark functionality thats listed in the intent. Not sure Tor Browser actually uses this, and guess it may be stripped in future. Probably better to look if the ports Tor Browser uses are open, think it always uses ports 8218, 9140 and 9150 on IP address 127.O.O.1 then the check is if Tor Browser is running, which increases the chance it is where the share came from.
*Just ask users if they want XBrowserSync to connect to site to fetch metadata the first time user bookmarks a site. (Could have 'yes/no' then ask 'always do this?')

**Comment by nero120** [comment]
@dznsm as this is a [cordova](https://cordova.apache.org/) app I'm using the [inappbrowser](https://github.com/xbrowsersync/cordova-plugin-inappbrowser) plugin to fetch bookmark metadata in the background. Though I have some android programming experience I don't have enough knowledge or the time to devote to building a separate plugin to optionally fetch the data over tor.

Happy to go with option 1 however and can provide this for the next release.
