### ISSUE TITLE
[Request] Nightly Release Branch

### ISSUE THREAD

**Issue by zero77** [xbrowsersync/app#235]
**Is your feature request related to a problem?**
Can you please provide a nightly release that auto updates from git.

**Tell us about your idea**
So that volunteers can help beta test any changes before it's officially released.

**Comment by nero120** [comment]
Hi @zero77, whilst I appreciate the offer to beta test, I'm currently only allowing access to [patrons](https://www.patreon.com/xbrowsersync) to beta versions. Gotta fund this show somehow!! Sorry 🙇
