### ISSUE TITLE
Tags are lost from FireFox if to sync to Chrome

### ISSUE THREAD

**Issue by dzmitry-lahoda** [xbrowsersync/app#237]
**Describe the issue you are experiencing**
Firefox -> Chrome -> Firefox -> tags are erased from Firefox bookmarks

**How can the issue be reproduced?**
1. Have 10k bookmarks with tags in Firefox
2. Install plugin into Firefox
3. Install plugin to Chrome
4. Wait for sync.
5. Got to Firefox bookmarks
Expected: tags are retained
Actual: tags are lost
Not expected: tags appear to Chrome as it has no Tags

**Desktop browser**

- Windows 10
- Firefox latest as 1 month ago
- Chrome latest as 1 month ago
- Same old version of plugin

**Notes**
Are tags are supported? 
If it plugin proven to work well with tags, will donate 10USD.

**Comment by nero120** [comment]
Hi @dzmitry-lahoda, sadly Mozilla have not implemented support for native tags into the web extension Bookmarks API, so xBrowserSync cannot sync them. As xBrowserSync has to clear down existing bookmarks when performing a local sync any existing tags are lost.

There is a warning on the [add on page](https://addons.mozilla.org/en-US/firefox/addon/xbs/) plus the help guide in the extension warns about this to let the user know (also listen on the [known issues](https://github.com/xbrowsersync/app/wiki/Known-issues) wiki page.

Once mozilla have implemented this I will happily update xBrowserSync to support native tags!
