### ISSUE TITLE
Bug/enhancement - Allow url entries without "."s in the name

### ISSUE THREAD

**Issue by cjnaz** [xBrowserSync/App#24]
The App does not accept a URL such as 'http://localhost:6419/' (which I use with [https://github.com/joeyespo/grip](url)).  Apparently the URL must contain at least one '.'.  It is not clear what the App is unhappy with, or how to fix it.

A workaround (which I'm not sure why it works of if it is robust) is 'http://localhost.localhost:6419/'.  

I recall that I had this issue with the API as well.  

### Client app information
**App Platform:** Chrome

**Comment by nero120** [comment]
This will be resolved in v1.4.0. In the meantime you can create a local hostname to get around this restriction.

**Comment by cjnaz** [comment]
Thanks Rich.  Also, for local cameras the URL is a rtsp://.  Please consider allowing all sorts of URLs.

**Comment by nero120** [comment]
Fixed in 6afd964.
