### ISSUE TITLE
ctrl-space keybinding conflicts with web based applications. Make it configurable.

### ISSUE THREAD

**Issue by git-rz** [xbrowsersync/app#241]
Binding ctrl-space interferes with web based code editors, like ScriptRunner for JIRA, illustrated below.

As a developer, the inability to customize or even just turn off the key binding for xBrowserSync, is very frustrating. Please implement a setting to control this behavior. 

![image](https://user-images.githubusercontent.com/53906153/93963078-3782e380-fd2a-11ea-862f-3e91025a2cdd.png)

![image](https://user-images.githubusercontent.com/53906153/93963126-571a0c00-fd2a-11ea-844e-4c180db10b32.png)

**Comment by nero120** [comment]
You can customise the binding in the browser's extension/add in settings, Ctrl-space is just the default.

**Comment by git-rz** [comment]
Are you saying that it available in the pre-release versions? Because it is not available in the version. I am running, v1.5.2
