### ISSUE TITLE
Permanent sync or only sync-on-demand with Browser AddOn? Exclude a bookmark subfolder?

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/app#242]
Assume I setup xBowsersync Browser-WebExtension to sync my bookmarks between my Firefox Desktop- and my Firefox-Notebook-installation.

Is this syncing automatically and permanently performed?
Or can I switch to an only-sync-on-demand only after clicking a certain button?

Can I exclude a certain bookmark-sub-folder from being synced?

Peter

**Comment by nero120** [comment]
Currently syncing occurs automatically in the background. xBrowserSync checks for updates to your synced data every 15 minutes and if it detects updates pulls them down and updates your local browser data. It will occur as long as your browser is open and sync is active.

> Is this syncing automatically and permanently performed?
Or can I switch to an only-sync-on-demand only after clicking a certain button?

Though you are able to manually force an update if detected (via the Settings panel), you cannot currently disable automatic syncing.

> Can I exclude a certain bookmark-sub-folder from being synced?

Currently you are able to disable syncing of the bookmarks bar/toolbar but that's all. There is an existing [feature request](https://github.com/xbrowsersync/app/issues/26) for sync profiles that would allow you to select which folders are synced.
