### ISSUE TITLE
It does not save my history

### ISSUE THREAD

**Issue by Tamy101** [xbrowsersync/app#244]
Why does it not save my history across different browsers?

**Comment by Tamy101** [comment]
pls help

**Comment by b-01** [comment]
Hi, 
what do you mean with history? 
This tool/extension syncs **bookmarks** - and nothing else.

**Comment by luixxiul** [comment]
You'd better go read: https://github.com/xbrowsersync/app/wiki/Roadmap

**Comment by nero120** [comment]
@Tamy101 xBrowserSync currently only syncs bookmarks. Syncing of history will be added in a [future version](https://github.com/xbrowsersync/app/wiki/Roadmap). This is explained in various places, in the app help text, on the web stores, on the website etc etc...
