### ISSUE TITLE
Android: Info message displays <br/> tags instead of actual newlines

### ISSUE THREAD

**Issue by b-01** [xbrowsersync/app#245]
**Describe the issue you are experiencing**
When syncing an empty (newly created) Sync on my Android device, the message displaying the info message contains HTML-Tags instead of the actual newlines.

**How can the issue be reproduced?**
1. Create a  new sync ID using a browser not containing any bookmarks
2. Use the newly created ID to log into the Android Application
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem: Screenshot attached.

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: Samsung Galaxy S20+
 - OS: Android 10
 - Version v1.5.2

![Screenshot_20201010-183927_xBrowserSync](https://user-images.githubusercontent.com/46758559/95660610-4e4a7800-0b29-11eb-9bca-53b4675f24dc.png)

**Comment by nero120** [comment]
Thanks for logging this @b-01, it's actually already been resolved and the fix will be included in the upcoming v1.6.0 release.
