### ISSUE TITLE
password sync

### ISSUE THREAD

**Issue by evert-mouw** [xbrowsersync/app#247]
I totally understand the team's reservations about password sync, as there are security risks. Still, skilled users might benefit from password sync. It could be disabled by default, and hidden away in an "advanced settings - use at own risk" section. E.g., I'm currently syncing parts of my Firefox profile between my Arch Linux boxes over ssh, and all my home directories are encrypted. Not storing passwords in the profile, but in KeePass instead (as you recommend) would result in also storing the passwords in my home directory, and would be just another target. Furthermore, most web services now use client identification (known devices, known browsers) or F2A so passwords become just another part of the total key (including the bookmarked URL) to unlock access to some online resource.

**Comment by wuniversales** [comment]
Passwords can be encrypted end-to-end, so I don't see a problem adding it to the plugin.

**Comment by nero120** [comment]
I hear you both, however password syncing is still not in the cards for the v1 [roadmap](https://github.com/xbrowsersync/app/wiki/Roadmap). Who knows, perhaps it will be something we'll look at adding in v2 if there is enough demand...

**Comment by AE720** [comment]
I wanted to add to this. Password managers are basically necessary. You cannot reasonably expect to have unique, complex passwords to every site you make an account on and memorize them. I'm more or less fed up with the shoehorned ways to get a similar experience between your phone and PC. If Brave didn't offer p2p syncing, I would be completely lost. In the event the password manager DOES get compromised (which is very unlikely if you do encryption and perhaps MFA) then congrats, now you have a list of everything you need to change. Given how rare it would be, the worst would be having to spend an afternoon combing through the list.
