### ISSUE TITLE
Sync only on-demand possible? Or only auto-sync?

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/app#249]
I am new to xbrowsersync and have some questions:

Are the local bookmarks always automatically synced with the remote server?
or can I decide to sync them only on demand (by clicking a button or similar)?

Is only the connection between browser and server encrypted or the data on the server itself?
end-to-end encryption?

Thank you
Peter

**Comment by nero120** [comment]
> Are the local bookmarks always automatically synced with the remote server?
> or can I decide to sync them only on demand (by clicking a button or similar)?

You already asked these questions which I answered here: #242 

> Is only the connection between browser and server encrypted or the data on the server itself?
> end-to-end encryption?

Data is encrypted clientside before being transmitted to the chosen xBrowserSync service. If the service is selected as **https** (e.g. https://api.xbrowsersync.org/) then traffic is also encrypted.
