### ISSUE TITLE
Improve the time to load the Android app

### ISSUE THREAD

**Issue by Primokorn** [xbrowsersync/app#25]
### Steps to reproduce
1. Clear your recent apps
2. Open XBrowserSync (cold start)

### Expected behaviour
Opening the app within 1-2 seconds.

### Actual behaviour
The app needs more than 4 seconds.

### Client app information
**App Platform:** Android Oreo 8.1  
OnePlus 3T

#### Other info
The splash screen is useless. Maybe it could help to reduce the opening.
Thank you.

**Comment by nero120** [comment]
Hi @Primokorn. The mobile apps are built on Apache Cordova so currently the loading time is dependent on that library/platform moreso than the xBrowserSync code.

A couple of things planned for the future that may resolve this, firstly I plan to port the app code to React (and TypeScript) from the deprecated AngularJS which will make all of the apps (browser and mobile feel quicker). Once that is done the way is then clear to port the mobile apps from Cordova to React Native which as they will now be native apps will load and function much quicker than they currently do.

Out of interest what phone are you experiencing this on? On my OnePlus 2 (a fairly old phone) the app loads in less than 4 seconds. Does it take the same amount of time to load if you disable your current sync, close the app and then re-open?

**Comment by Primokorn** [comment]
Thanks for your answer and the good news!
Did you try with a cold start? Because only 2s are necessary for a hot start.
I own a OnePlus 3T using this [custom rom](https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-omnidragon-os-t3806316). 
Disabling the current sync doesn't change the time to load the first screen.

**Comment by nero120** [comment]
Ok cool, yeah I think it's just down to the cordova/angularjs combo, two frameworks that aren't known for their native speed (though without them there wouldn't have been any xbs mobile apps!). You have very limited control over the loading process with cordova.
