### ISSUE TITLE
Firefox extension cuts off options

### ISSUE THREAD

**Issue by heyyzoeyy** [xbrowsersync/app#251]
The Firefox extension window does not have scrolling, and cuts off the options icon.

**Screenshots**

![image](https://user-images.githubusercontent.com/43478986/98472419-e9974180-21ea-11eb-8652-f478fc4fe545.png)

**Desktop browser**

- OS: Manjaro Linux
- Browser: Firefox
- Version: 82.0.2

**Comment by nero120** [comment]
@heyyzoeyy very sorry but I can't support every Firefox implementation out there for every distro. If the issue doesn't occur on Ubuntu then it's not something I have the capacity to look at.
