### ISSUE TITLE
FEATURE REQUEST: Standalone desktop application?

### ISSUE THREAD

**Issue by thunderblood101** [xbrowsersync/app#262]
Hello!
I really like xbrowsersync, because it allows me to use multiple desktop browsers and save all of my bookmarks across them. I use a certain browser because I want to, not because that's where my bookmarks are. 
*but*...
I often try other browsers, such as pale moon, basilisk, qutebrowser, tor, and others. What's the viability of a semi-lightweight desktop app that I could run alongside these other browsers, rather than having to run firefox or chrome *as well as* whatever other browser I'm using? 
Thanks :D

**Comment by nero120** [comment]
Almost none! I am only one person and don't have enough spare time as it is to develop the app, let alone a stand alone native app for multiple platforms. If you've got a spare few million $$$ to donate so I can hire a dev team then possibly, otherwise... 🤷
