### ISSUE TITLE
[v1.4.0 BETA] Issues syncing between FF & Chrome

### ISSUE THREAD

**Issue by matthewdavis** [xBrowserSync/App#27]
### Steps to reproduce
1. Create new sync on FF
2. Create new sync on Chrome (to pull down the bookmarks from step 1)
3. Make change to FF, let it sync
4. Make change to Chrome, it'll be blocked and it'll re-download the changes from FF
5. Do this a few more times on either side.

### Expected behaviour
It's ok for current changes (adding/removing of a bookmark) to be lost but notified. Claiming things were out of sync and the previous change must be re-done.

### Actual behaviour
I've done a bit of changes using the bookmarks bar between the 2 browsers, and I've found that there are times were a bookmark just gets lost. Is there parsing of the bookmark URL? The 2 that seem to be confused are

 - https://mail.google.com/mail/
 - https://mail.google.com/a/domain.com

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Chrome - Version 67.0.3396.79 (Developer Build) Fedora Project (64-bit)
FF - 61.0.1 (64-bit)

#### Other info

The testing I did was primarily within the Bookmarks bar area. Simply dragging URLs into the bar.

**Comment by nero120** [comment]
Thanks for raising this @matthewdavis. I've checked in a few bug fixes which I suspect can explain why you were seeing odd behaviour with missing bookmarks after conflicts were detected.

I've uploaded new executables to the [release page](https://github.com/xBrowserSync/App/releases/tag/BETA1), could I trouble you to uninstall your current version of v1.4.0 on both Chrome and Firefox, then install the new versions and see if you can re-create the issue?

**Comment by matthewdavis** [comment]
Sorry just now getting back to you on this one. My initial tests seem to be good. I don't see anymore lost bookmarks. Good job! This feature looks to make it feature complete to be a proper xmarks replacement.

**Comment by nero120** [comment]
Glad to hear it @matthewdavis!

**Comment by nero120** [comment]
FYI @matthewdavis, I've [uploaded new builds](https://github.com/xBrowserSync/App/releases/tag/BETA1) which have fixed a number of issues with automatic checking for sync updates between browsers which might have contributed to this issue.

I'm going to close this now but feel free to re-open if necessary.
