### ISSUE TITLE
Find as you type does not work in android app

### ISSUE THREAD

**Issue by HidiH** [xbrowsersync/app#273]
The browser extensions  show immediate results when given more than one character. This behaviour would be nice in android app too.

**Comment by nero120** [comment]
@HidiH this is a known issue with certain keyboards such as  Gboard, sadly they do not report events in the expected way and there's nothing i can do to change that given the current app architecture. I use [AnySoftKeyboard](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard&hl=en_US&gl=US), the find as you type functionality does work as intended with this keyboard.
