### ISSUE TITLE
why can't it be installed in android version 7.1.1

### ISSUE THREAD

**Issue by candrapersada** [xbrowsersync/app#279]
why can't xbrowsersync be installed in the android version 7.1.1?
and is there any other way to Scan this QR code using Android without an application to Copy and paste the Sync ID?

**Comment by nero120** [comment]
> why can't xbrowsersync be installed in the android version 7.1.1?

I don't have enough spare time to support old versions of Android, sorry.

> and is there any other way to Scan this QR code using Android without an application to Copy and paste the Sync ID?

Just use the "Copy Sync ID to Clipboard" button below the QR code.

**Comment by candrapersada** [comment]
> Just use the "Copy Sync ID to Clipboard" button below the QR code.

How do I paste the Sync ID to another PC with QR Android or use other methods?

**Comment by nero120** [comment]
Try googling it.
