### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by JimInWoodstock** [xbrowsersync/app#293]
Is it possible to get my password? I installed xbrowsersync on my PC a year ago or so. I have a new additional pc  and I want to use xbrowsersync on it. I can get my syncid from my existing installation, but I don't remember the password that I used. I, of course, need the password to start sync on my new pc. 

Thanks,

**Comment by Adda0** [comment]
There is no way to recover the password AFAIK. I would export the currently saved bookmarks (if you don't remember the password, do it anyway just to be sure if anything happens, and you are logged out from your PC), create a new ID with a password (stored somewhere safe) and import the saved bookmarks there. When you log in on both of your devices, you will have your old bookmarks available. If you stop using the old ID, after some time (usually a month or so), the old account will be purged from the host server (so the host doesn't need to save the old data, when they are not used – not updated) and you will be able to continue using the new "account" with all of your bookmarks on every device.

**Comment by JimInWoodstock** [comment]
Worked like a champ!

Thanks,
