### ISSUE TITLE
[Feature Request] Manually Input Sync ID on Mobile App

### ISSUE THREAD

**Issue by ltlnx** [xbrowsersync/app#295]
Hello, 
The xbrowsersync Android app requires users to scan QR Code to sync. However, my device has a broken camera, thus cannot use the scanning feature. Is it possible to add manual typing in Sync IDs as an option?

Thanks in advance!

Litelinux

**Comment by nero120** [comment]
Hi @ltlnx, this has already been implemented and will be available with v1.6.0.

**Comment by iwan-uschka** [comment]
Hi, v1.6.0 has not been released yet and i need to check my bookmarks while only having my phone with me. I tried to create a QR code myself by encoding the sync ID but something is missing. The release notes tell me it's the service URL. Can you please tell me what data the QR carries? Something like `serviceUrl:syncId`?
Thanks and cheers

**Comment by iwan-uschka** [comment]
Now that i am back at my computer i wanna answer my own question in case somebody else need this information. The QR code encodes `<syncId>|$$|<serviceUrl>`. If you use the default service it's `<syncId>|$$|https://api.xbrowsersync.org`.

**Comment by nero120** [comment]
@iwan-uschka for v1.5.2 yes that's right (see [this](https://github.com/xbrowsersync/app/blob/v1.5.2/js/app.js#L874) code).
