### ISSUE TITLE
Error: "Couldn't get bookmark properties. URL is invalid or webpage data could not be retrieved."

### ISSUE THREAD

**Issue by DavidPesticcio** [xbrowsersync/app#298]
Unable to populate bookmark properties when using share to xBrowserSync "Add Bookmark" from Android "DuckDuckGo" browser v5.89.0 (58000)

URL: https://drjohnrusin.com/thoracic-spine-mobility-fix/

**Comment by nero120** [comment]
Thanks for reporting @DavidPesticcio
