### ISSUE TITLE
Is v1.40 beta still open?

### ISSUE THREAD

**Issue by crankynet** [xBrowserSync/App#30]
Is v1.40 beta still open? Not able to create sync ID at api-beta.xbrowsersync.org

**Comment by nero120** [comment]
Hi @crankynet, yes it is still open. The beta service had gone down temporarily but I've just restarted it and it's up and running again so you should be able to create a new sync ID now.

**Comment by crankynet** [comment]
The server status now shows it is online. However, the "next" button stays grayed out even though  a valid password (background changed from red to green) has been entered. This is done on Firefox 61.0.1 (64 bit) on Windows 10 x64.

**Comment by nero120** [comment]
Thanks @crankynet, I've just committed 2be3259 to resolve this.

**Comment by crankynet** [comment]
Ticket can be closed. I am able to create sync ID from Firefox. Thanks.
