### ISSUE TITLE
Adding extensions sync in some way or other

### ISSUE THREAD

**Issue by fine2006** [xbrowsersync/app#302]
Syncing extensions, I doubt if its possible with all browsers, but could you just sync a list of addons/extensions/whatever installed? This is the main part of the proprietary sync I use, since I don't have to be annoyed by ads if I forget to install an adblock

**Comment by nero120** [comment]
Sorry @fine2006, syncing of extensions is not on the roadmap for the foreseeable future.

**Comment by Spl0itable** [comment]
> Sorry @fine2006, syncing of extensions is not on the roadmap for the foreseeable future.

Any change on this? You could potentially isolate the extension data by browser type, which would let it sync and populate the installed extensions. Thanks
