### ISSUE TITLE
Feature request: Also search in the URL when using the search feature

### ISSUE THREAD

**Issue by eschaubert** [xbrowsersync/app#309]
Hi,

it would be really good if the search would also include the URL, not only the title, description and tags.
Because sometimes I might not remember under which title I saved the bookmark, but I most likely remember the main URL (e.g. article from a newspaper, so I look for the name of the newspaper).

For example, let the webpage be lifehacker.com. I see that i can start typing "life" it will not show the results but offer autocomplete which after pressing the tab key. will show "lifehacker.com" and the bookmarks that are connected to this webpage. But if i search for "hacker" the bookmarks will not be displayed.

Best regards
Eugene

**Comment by nero120** [comment]
@eschaubert I intentionally did this to keep search results as relevant as possible. Wildcard matching any part of a url causes all kinds of irrelevant results which makes the search much less effective. If you want to search by url, you can enter the url host (with autocomplete) as you mentioned, which I think is  a good compromise and gives you the best of both worlds.
