### ISSUE TITLE
Feature Request/Bug? - offline backup

### ISSUE THREAD

**Issue by bmorgy** [xbrowsersync/app#310]
My service provider (https://xbs.xv.rs/) is currently down.  I'd like to change providers using backup/restore feature. I'd like to start by backing up my existing bookmarks, however this is not allowed when the service is down - I get a "connection to service lost" error.  As my (unsynced) bookmarks are still on my computer - can you please allow backups without establishing a connection to the service first?   This will simplify changing providers and provide more security.

**Comment by nero120** [comment]
@bmorgy this issue has already been resolved and will available once v1.6.0 is released.
