### ISSUE TITLE
iOS: Apple announced safari will support WebExtensions

### ISSUE THREAD

**Issue by dada513** [xbrowsersync/app#311]
**Tell us about your idea**
At the WWDC 2021 conference apple announced it will be adding WebExtensions support to safari. This might allow an iOS version of xbs to be possible

**Comment by SingingZach** [comment]
Web extensions are now available on betas for iOS 15 and you can download them through the Apple App Store.

**Comment by whalley** [comment]
iOS 14 is now GA.

Extensions now supported.  https://developer.apple.com/safari/extensions/

**Comment by fabian-st** [comment]
Would love to see XBS working on my iPad. ❤️

**Comment by fabian-st** [comment]
Is there anything one can contribute in order to get XBS running on iOS, now that the preconditions are set?

**Comment by amit510** [comment]
Would love to see this working on iOS devices like iPhone & iPad.

**Comment by nero120** [comment]
In typical Apple style, it turns out you stil need Apple hardware (to run xcode) to build extensions for Safari, so this is a non-starter.

The best you'll get is a progressive web app (PWA) that I'm planning to add in v1.7.0 (don't ask me for timescales!).

Sorry folks.

**Comment by fabian-st** [comment]
I could provide you with the required hardware and also have an Apple Developer account. Unfortunately i don't have experience with Cordova, so I woulsn't know how to get started...

**Comment by fabian-st** [comment]
> In typical Apple style, it turns out you stil need Apple hardware (to run xcode) to build extensions for Safari, so this is a non-starter.
> 
> The best you'll get is a progressive web app (PWA) that I'm planning to add in v1.7.0 (don't ask me for timescales!).
> 
> Sorry folks.
> 
> Edit: However, if someone with the necessary hardware wants to figure out how to convert the xBrowserSync chromium build to work with Safari and host a build in their own repo then please do go ahead. I have no idea if it will work (does Safari actually implement the web extension API properly? If so they're doing better than Mozilla...), but if it does I'll be happy to link to your repo from the README.

I could provide you with the required hardware (you could keep the MacBook if you maintain it) and also have an Apple Developer account. Unfortunately i don't have experience with Cordova, so I woulsn't know how to get started...

**Comment by fabian-st** [comment]
Seems like we're out of luck anyway...
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#bookmarks

**Comment by BirdInFire** [comment]
Proposed an alternative to full sync to have access to bookmark even without sync : https://github.com/xbrowsersync/app/issues/375
