### ISSUE TITLE
 Bottom part of extension panel cut off on Firefox 89.0

### ISSUE THREAD

**Issue by vtibix** [xbrowsersync/app#314]
Description:

The bottom of the Firefox extension's panel is cut off on Firefox 89.0 on Gnome 40 when the display scaling is set to anything higher than 100%. The panel would not fit the screen area therefore it is displayed in a scrollable container. The problem is that it is not possible to scroll all the way to the bottom of the panel this way some of the buttons are not accessible.

1. Install the extension for firefox 89.0 on gnome 40 desktop
2. Set scaling on display higher than 100%
3. Open the gui panel and try to scroll to the bottom so you can click on the very first button to continue with using xbrowsersync
4. The buttons at the bottom part are furter down but you cant scroll that far

![Képernyőkép erről: 2021-06-18 14-20-16](https://user-images.githubusercontent.com/86109947/122560082-6f605280-d040-11eb-9a4c-5ef703b9f19e.png)

- OS: [Fedora 34 with Gnome 40
- Browser: Firefox
- Version: 89.0

**Comment by nero120** [comment]
@vtibix I can't replicate this on win10 with Firefox 89.0.1, it is likely a Firefox display issue with the distro implementation, not specific to extensions (I've seen it before with other distros). Can you report it to the distro team responsible for Firefox please?

**Comment by vtibix** [comment]
Firefox was updated on Windows 10 to 89.0.1 and I have the same issue there. This leds to the conclusion that this is a Firefox issue, since it happening in both OS-es for me when screen is scaled to 150%. It also affects other extensions which confirms that this is indeed a Firefox issue.

Sorry for bothering you with this but I was really upset that I could not use my beloved xbrowsersync on my laptop when I'm away from my external monitor.

![Screenshot 2021-06-20 090247](https://user-images.githubusercontent.com/86109947/122665232-55408480-d1a6-11eb-814a-9be76a7393c6.png)

**Comment by nero120** [comment]
@vtibix not a problem, if it's an issue with xBrowserSync then I'm happy to fix it, just that Firefox tends to have lots of issues which can appear like it's an issue with the extension. However, I can't even recreate this issue, see this screenshot:

![image](https://user-images.githubusercontent.com/4236238/123264292-cc04b700-d4f1-11eb-81c8-ee6d8380df3e.png)

At 150% scaling, xBrowserSync still looks fine in Firefox v89.0.2.
