### ISSUE TITLE
Messed up all my bookmarks.

### ISSUE THREAD

**Issue by Samisaprogrammer** [xbrowsersync/app#319]
**Describe the issue you are experiencing**
Messed up all my bookmarks.

**How can the issue be reproduced?**

1. Move a bunch of bookmarks around.
2. Wait for client out of sync error
3. See that most bookmarks have been placed in random folders and some have been deleted.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: Win10
- Browser Firefox
- Version 89

**Application log**
Please include the logs from the affected clients:

There are no logs

**Comment by Samisaprogrammer** [comment]
I am no longer using XBrowserSync. Thanks for lying in the review section about all sync errors being fixed in the new version.
Also, fuck you.

**Comment by nero120** [comment]
This is F(ree) O(pen) S(ource) S(oftware), though I do my best to fix issues it goes without saying that you need to use your own common sense when installing and running such software.

However there's an easy solution to this problem - just restore your bookmarks from the backup you took before installing xBrowserSync.

**Comment by Samisaprogrammer** [comment]
Huh? Do you seriously think i haven't created ANY new bookmarks since i took that backup?

**Comment by Samisaprogrammer** [comment]
Yes, I can tell this is F(ree) O(pen) S(ource) S(oftware), we are on github. You just mock your users instead of stfu-ing and listening to their problems. If there's gonna be such major issues mark this as alpha or beta.

**Comment by nero120** [comment]
Don't you take regular backups?

**Comment by Samisaprogrammer** [comment]
I do, although not daily.

**Comment by Samisaprogrammer** [comment]
And they are kinda useless considering how much I mess with my bookmarks.

**Comment by nero120** [comment]
Then perhaps you should "stfu" and go take regular backups when the FOSS software you insist on using tells you to.

**Comment by Samisaprogrammer** [comment]
where? am i just blind?

**Comment by nero120** [comment]
Help guide > Remember to back up

**Comment by nero120** [comment]
Have you tried using Firefox's bookmark restore:

![image](https://user-images.githubusercontent.com/4236238/124283412-c9ced800-db43-11eb-91f6-dfaffdce9b8c.png)

**Comment by Samisaprogrammer** [comment]
oh. welp. that worked. sorta. i take most stuff back. thank you!

**Comment by nero120** [comment]
I'm glad it helped. Seriously, you need to remember that people who run FOSS projects do not have the time and resource of corporations and work on it in their own free time. Don't expect any FOSS software to be bullet proof. Also, don't be a sociopath, show a bit of empathy.
