### ISSUE TITLE
[Feature Request] Default view to folder view

### ISSUE THREAD

**Issue by notally-web** [xbrowsersync/app#330]
Seeing all the bookmarks based on timestamp(latest added first) is of not much use. 
Search is great but I'd rather prefer a sorted 'Folder View' as default.

Feature Request: An option to make 'Folder View' as default on opening xBrowserSync on Mobile or Desktop.

Thank you.

**Comment by nero120** [comment]
@notally-web this feature has already been added, it will be available once v1.6.0 is released.

**Comment by notally-web** [comment]
> @notally-web this feature has already been added, it will be available once v1.6.0 is released.

Nice. Thanks.
What's the eta on 1.6.0 :)
