### ISSUE TITLE
Language Japanese support

### ISSUE THREAD

**Issue by surapunoyousei** [xbrowsersync/app#331]
I wrote messages.json for the Chrome extension, translated into Japanese.
Can I provide this to xBrowserSync?
![image](https://user-images.githubusercontent.com/73892113/130354360-33147a8a-27d9-44c6-83da-db9d99470418.png)

**Comment by nero120** [comment]
Thank you @surapunoyousei! Could you please add your translations through [crowdin](https://crowdin.com/project/xbrowsersync-app/ja) and I'll approve them for inclusion in the next release.

**Comment by surapunoyousei** [comment]
OK I see

**Comment by nero120** [comment]
@surapunoyousei thank you for this! I've approved the translations, just one needs your attention when you have a moment. Thank you again!

**Comment by surapunoyousei** [comment]
If my translation is wrong, I'll be ready to fix it immediately.
Thanks！
:)

**Comment by nero120** [comment]
@surapunoyousei just this one:

https://crowdin.com/proofread/xbrowsersync-app/34/en-ja#6588

The string refers to Firefox but the translation mentions Chrome. Once that's fone I'll approve and then it's all finished. Thank you!

**Comment by surapunoyousei** [comment]
Sorry My English isn’t good. 

I fixed it.

Thank you @nero120 !

**Comment by nero120** [comment]
Thank you @surapunoyousei!
