### ISSUE TITLE
Add folder management capability, local encryption without any file size limit, allow users to opt out from cloud sync.

### ISSUE THREAD

**Issue by Pinaki82** [xBrowserSync/App#35]
Everything seems fine, except a sub-folder management capability. Users should be able to create an encrypted backup locally without any file size restrictions, so the encrypted backup can be uploaded to a cloud service later. Key-files can also be added to strengthen the security of the backed up data before uploading it to the cloud. I do not want to use https://api.xbrowsersync.org or any of the three servers provided by the app, I'll upload the data to Dropbox manually.

 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 

**App Platform Version:** 

#### Other info
```
Enter any other information you think would be helpful here.
```

**Comment by nero120** [comment]
Hi @Pinaki82, hopefully the answers below provide some clarification:

> Add folder management capability

I'm afraid this is out of scope for this project as it can already be done using the native browser bookmarking tools. Implementing it would be a lot of effort for duplicating existing "out of the box" functionality.

> Local encryption without any file size limit

You are able to export your bookmarks data in unencrypted, JSON format. As the data is saved locally it does not need to be encrypted by the app as the data is not going out over the internet. If the user wishes to store the backup encrypted of course they can do that, but I think it's a feature that doesn't provide a huge benefit at this time.

> Allow users to opt out from cloud sync

You are already able to [run your own xBrowserSync service](https://github.com/xBrowserSync/API) if you do not want to sync your data to one of the existing services. If you would like to sync your browser data to other services such as dropbox then unfortunately that is not something that I personally plan on implementing. It would be great if others want to fork the xBrowserSync API to support other data stores such as dropbox!

_Note: if you are running into data limits then I would recommend running a local xBrowserSync API service as you can set the maximum sync size yourself to a much higher value in accordance with your requirements._

**Comment by Pinaki82** [comment]
Hello Rich!
First of all, thanks for your reply. However, I find xBrowserSync is an
obvious choice for those who need the convenience of a traditional bookmark
manager along with the added security advantages. As of today, no
xBrowserSync server provides more space than 1 MB. We need to sync our data
encrypted locally and store it somewhere else. A key file could add an
extra layer of security besides passwords. Add Dropbox sync feature, so
we'd never have to rely on a sync server. It's a necessity. Thanks in
advance.
Sincerely,
Pinaki Gupta

**Comment by nero120** [comment]
> Add Dropbox sync feature, so we'd never have to rely on a sync server.

@Pinaki82 I've been thinking about this some more over the past few days, I have to agree that it would be useful to allow users to sync to many different services. However, the benefit of syncing to an xBrowserSync service is the fact that it is completely anonymous - you can trust that you IP address is not being logged and with no personal data to identify you, were anyone to get data off the server they could never link it back to you. Also, if you don't trust [api.xbrowsersync.org](https://api.xbrowsersync.org/) then you can run your own service. Were xBrowserSync to support services like Dropbox then the anonymity factor is lost.

I do like the idea of adding support for different services though, especially [Nextcloud](https://nextcloud.com/) as I can imagine users that are interested in xBrowserSync may also be running their own Nextcloud server.

**Comment by Pinaki82** [comment]
Hello Rich!
It's true that if you allow syncing with different cloud providers, then
they can log the IP address through the data will always remain encrypted.
But, those third-party cloud services come with another advantage, they
offer 2FA so you can never lose your bookmarks. Plus any nosy guest cannot
accidentally or intentionally alter your bookmarks. I would sacrifice a
little convenience with this, but the idea of syncing with different cloud
providers won't be a bad idea.
Thanks.
With best regards,
Pinaki Gupta
