### ISSUE TITLE
Can't sync on Firefox 88

### ISSUE THREAD

**Issue by JohnnyDongVN** [xbrowsersync/app#350]
Lile title, i cant Sync it on Firefox 88. Im using Ubuntun 16.04 LTS. Please check it ! Thanks !

**Describe the issue you are experiencing**
A clear and concise description of your issue:

**How can the issue be reproduced?**

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: [e.g. Win10]
- Browser [e.g. Chrome, Firefox]
- Version [e.g. v1.5.0]

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device: [e.g. Samsung Galaxy S10]
- OS: [e.g. Android 9 Pie]
- Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```

</details>

**Comment by nero120** [comment]
Just tested syncing v1.5.2 on Firefox v94.0 in 20.04.3 LTS and was able to sync without any issues. Note that Firefox's privacy features (such as never remember history) disable some of the web extension APIs that xBrowserSync relies on so if you have these enabled that may be the cause. To confirm this, try disabling privacy features and then see if xBrowserSync syncs properly. Unfortunately, this is a browser issue and there's nothing I can do to resolve this.
