### ISSUE TITLE
None English Accented character search bug

### ISSUE THREAD

**Issue by good2see** [xbrowsersync/app#357]
None English accented characters cannot be searched in the search bar. 

For instance;

Turkish accented letters:
Lower: ı, Upper: I (Not the same with upper i or lower L in English)
Lower: ö, Upper: Ö
Lower: ğ, Upper: Ğ
Lower: ü, Upper: Ü
Lower: ş, Upper: Ş

-Win 10
-Opera Browser

**Comment by nero120** [comment]
@good2see could you possibly test the fix using this [beta release](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.26) (make sure to read [this](https://github.com/xbrowsersync/app/wiki/Installing-beta-releases) before running it)?

**Comment by an-ca** [comment]
@nero120, does it make the search accent insensitive, i.e. results with « â » show up when searching for « a »?
