### ISSUE TITLE
How to delete all bookmarks in xBrowserSync remote storage?

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/app#366]
How can I delete all bookmarks in xBrowserSync remote storage WITHOUT deleting them in local browser?

**Comment by Avinash-Lvs** [comment]
I don't understand the usecase but here how it is done:

1. Disable sync for all your other instances of XbrowserSync.
2. Create a backup of bookmarks from your browser bookmark manager.
3. Use the revert option in XbrowserSync settings.
4. disable sync in your XbrowserSync.
5. Restore from your browsers bookmark manager with the backup you previously made.

**Comment by pstein** [comment]
very user-unfriendly

**Comment by nero120** [comment]
@pstein create a backup in xBrowserSync, delete all bookmarks (using the browser's bookmark manager), disable sync then restore the backup to re-create the bookmarks locally.
