### ISSUE TITLE
Fails to setup on new machine "something went wrong" can't log in

### ISSUE THREAD

**Issue by ChiefGyk3D** [xbrowsersync/app#368]
All I get is this error, nothing more and no syncing or anything
![image](https://user-images.githubusercontent.com/19499446/151558308-8eb636ca-0e6d-49d7-bf53-4564403f400b.png)
[xbs_log_20220128085154.txt](https://github.com/xbrowsersync/app/files/7959116/xbs_log_20220128085154.txt)

**Comment by stfnx** [comment]
I've had the same issue some days ago.
Do you have a lot special characters in your password?
Or a very long password?

That was the issue for me.

**Comment by leder11011** [comment]
Thanks  @stfnx ,

having this issue, too. Relative short (11) and simple (no specials) PW.

Any other idea how to fix?

Best regards
Gerrit

**Comment by nero120** [comment]
@ChiefGyk3D it appears from the log file you provided that you're using a linux distro that has not implemented Firefox properly, expected bookmark containers were not found.

If you're using a Linux distro other than Ubuntu chances are you're going to encounter issues with that distros Firefox build. This is not an xBrowserSync issue so I'd take it up with whomever maintains Firefox for that distro.

@stfnx @leder11011 interested to know what passwords are causing issues, can you provide me with an example so I can replicate please?

**Comment by nero120** [comment]
@stfnx @leder11011 interested to know what passwords are causing issues, can you provide me with an example so I can replicate please?

**Comment by leder11011** [comment]
@nero120 I would not like to share a PW in public, plz give me your PM.

**Comment by nero120** [comment]
@leder11011 I don't want your actual password, can you not find a different password that results in the same issue?

**Comment by leder11011** [comment]
try something with special charachter "-"

**Comment by leder11011** [comment]
xbrowsersync app populated my vivaldi browser bookmarks folder: trash has 45000 duplicate bookmarks inside. I am very unhappy!

**Comment by nero120** [comment]
@leder11011 you should have [read the instructions](https://github.com/xbrowsersync/app/wiki/Supported-browsers-and-operating-systems), Vivaldi is NOT SUPPORTED.
