### ISSUE TITLE
IOS app to "only" show our bookmark.

### ISSUE THREAD

**Issue by BirdInFire** [xbrowsersync/app#375]
Actually i already know that sync bookmark on Apple device is nearly impossible, but here i would like to ask if it's possible to have an app who "show" our extension and add them directly from this app, like that we can open our bookmark from this app (and IOS will use our default browser to open it (also work for iPad)).

And from our browser we share the URL we want to save with this app, and the app open the "new bookmark" process with the "shared" link.
Good compromise to have our bookmark on Apple device even without a full proper "sync" since it's seem impossible : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#bookmarks.
Link from this FR : https://github.com/xbrowsersync/app/issues/311

For MAC OS the chrome / Firefox extension can do it and for Safari user (MAC M1 only) iPad app can be used).

Note: i propose this since if we compare IOS and Android, IOS is **BY DEFAULT** (yeah upper case and bolt to be sure), more secure and private than Android, some privacy conscious can be there (with apple crap disable), and will (like me) appreciate this kind of app.

**Comment by paulwratt** [comment]
If you can runs something like GreaseMonkey (or something that runs GM scripts - TamperMonkey, ViolentMonkey) you can write your "plug-in" in JS

**Comment by BirdInFire** [comment]
> If you can runs something like GreaseMonkey (or something that runs GM scripts - TamperMonkey, ViolentMonkey) you can write your "plug-in" in JS

or not since this kind of app isn't really tolerated on IOS

**Comment by vpctorr** [comment]
+1, seems like share/shortcuts are good enough for saving from Safari
Might be nice to have a web interface for easy access from Safari as well, I might work on that

**Comment by nero120** [comment]
@vpctorr I plan to add PWA support that should enable using xBrowserSync from iOS/Safari, prob from v1.7.0.

**Comment by RokeJulianLockhart** [comment]
Since this is completed, what's the link to the app?
