### ISSUE TITLE
Login error with correct info

### ISSUE THREAD

**Issue by MylesBolton** [xbrowsersync/app#383]
Windows 10, Firefox extra plugins are bitwarden i removed the others any idea what it going on 

Error Log
[xbs_log_20220323133843.txt](https://github.com/xbrowsersync/app/files/8333468/xbs_log_20220323133843.txt)

**Comment by MylesBolton** [comment]
if someone can make sence of the error please comment it

**Comment by MylesBolton** [comment]
error log for the fresh instal
[xbs_log_20220323135943.txt](https://github.com/xbrowsersync/app/files/8333629/xbs_log_20220323135943.txt)
l

**Comment by nero120** [comment]
@MylesBolton would you mind installing the [v1.6.0 45 beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.45) and seeing if this works? At the least you should get a more useful debug log out which should help narrow down the issue.

Make sure to create a dummy sync id don't use your "live" one with beta releases.

**Comment by MylesBolton** [comment]
ye was just loggin into github to remove this turns out my sync was removed or something it no longer exists on the API so thats fun

**Comment by MylesBolton** [comment]
do you know if there is a way to get it back

**Comment by nero120** [comment]
Doubtful, which API were you synced to? https://api.xbrowsersync.org? If so any syncs get automatically removed if not accesssed after three weeks. Do you have a back up to restore from?

**Comment by MylesBolton** [comment]
ye i dont so thats fun

**Comment by MylesBolton** [comment]
i stopped using it for a while as i was having a onload error when the plugin was looking for a update so went to try debug it today as i have some free time looks like i was too late

**Comment by nero120** [comment]
Sorry to hear that @MylesBolton, but please take regular backups as stuff can go wrong (the upcoming release includes auto-backups which should make things easier).

**Comment by MylesBolton** [comment]
ye il close this now

**Comment by nero120** [comment]
Are you able to include the log from the 45 beta? Would be very useful.

**Comment by MylesBolton** [comment]
ah send the link for the install

**Comment by nero120** [comment]
https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.45

Thanks!

**Comment by nero120** [comment]
Ah yes, you need to install it as a temporary add on, see here for more info: https://github.com/xbrowsersync/app/wiki/Installing-beta-releases

**Comment by MylesBolton** [comment]
[xbs_log_20220323163906.txt](https://github.com/xbrowsersync/app/files/8334888/xbs_log_20220323163906.txt)
here it is

**Comment by MylesBolton** [comment]
hope it helps btw dont you think 3 weeks is abit short of a timeframe for removing data

**Comment by nero120** [comment]
Thanks for that, yes the error log confirms that the "login" failed as the sync was not found on the service.

Three weeks might seem quick but this is a free and anonymous service with no limit to the amount of syncs anyone can created so I have to be defensive, if you're not using it then it goes. You're not creating an "account" you're uploading a random encrypted data payload to the server.

As I said you can always restore your data from a backup at any time.
