### ISSUE TITLE
Latest betas do not work on OnePlus 8T

### ISSUE THREAD

**Issue by olavinto** [xbrowsersync/app#384]
For some reason beta 45 and 47 do not work on my OnePlus 8T but on my Samsung Galaxy Tab S5e they both work just fine. They also work on most desktop browsers.

I have unistalled them compleyely but they always open with a "Something went wrong" error. This is immediate after opening the app and it will only show

OnePlus Oxygen OS version is 11.0.13.13.KB05BA.

A couple of screenshots of everything that can be seen (the error is in Finnish):
![Screenshot_20220323-175250.jpg](https://user-images.githubusercontent.com/23163218/159741082-a775ad11-3902-4625-92e6-2c3762fc93e8.jpg)
![Screenshot_20220323-175200.jpg](https://user-images.githubusercontent.com/23163218/159740943-958bf047-efe4-4123-9459-4cf72c5e9970.jpg)

**Comment by nero120** [comment]
@olavinto hmm, are you able to switch your locale to English and see if it resolves the issue? Try it with the [v1.6.0 45 beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.45) (not the v1.7.0) please.

**Comment by nero120** [comment]
Ok thank you for trying, must be specific to OnePlus as it's fine on my Pixel 3a, let me have a think...

**Comment by olavinto** [comment]
The previous beta worked, 44, if I'm not mistaken. Since then there has been at least one system update though so that could have done something.

**Comment by nero120** [comment]
![Screenshot_20220325-111354.png](https://user-images.githubusercontent.com/4236238/160110969-b5d4d915-6632-4290-b54e-1a50513022ef.png)

**Comment by olavinto** [comment]
Thanks! Here is the screenshot:
![Screenshot_20220325-135916](https://user-images.githubusercontent.com/23163218/160117172-c0cecb18-3f42-4a16-80c8-d2ce12d7967d.jpg)

**Comment by nero120** [comment]
I think [this](https://github.com/storesafe/cordova-sqlite-evcore-extbuild-free/issues/60) is the issue occurring here. I'll try switching to the more widely used [cordova-sqlite-storage](https://www.npmjs.com/package/cordova-sqlite-storage) plugin for stability and get another debug build out for you to try later on.

**Comment by nero120** [comment]
@olavinto ok here's a debug release using the [cordova-sqlite-storage](https://www.npmjs.com/package/cordova-sqlite-storage) plugin:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.50

Remember to uninstall xBrowserSync before installing this version. Thank you for testing this!

**Comment by olavinto** [comment]
No errors this time followed by "Done!".

**Comment by nero120** [comment]
Excellent, thank you for your help @olavinto!!

**Comment by nero120** [comment]
@olavinto latest [beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.51) is up.
