### ISSUE TITLE
Camera is black when I want to scan qr-code to receive id on mobile

### ISSUE THREAD

**Issue by mariosadov** [xbrowsersync/app#385]
1. Go to android App
2. skip all the starting info(clicked "Got it")
3. Click SCAN ID
4. ALLOW CAMERA IN ANDROID SETTINGS
5. You get black screen instead of working camera to scan id
6. without id app doesn't work

flashlight button works, but it doesn't help to turn the camera on.

![зображення](https://user-images.githubusercontent.com/93256729/159759315-f5a8e2b0-896f-45c4-9605-9ccf0b128267.png)

**Mobile device**

- Device: [Xiaomi note 8 pro]
- OS: [Android 11, MIUI 12.5.7]
- Version [v1.5.2]

If you can't make camera work, I recommend you to:
1) add option on android app to write your existing id manually(textfield like on a desktop version) 
2) or you can add ability to get a new sync id in app without desktop browser

**Comment by nero120** [comment]
@mariosadov could you please try the latest beta release:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.51

(note that manual entry has already been added in the beta)

Please do not use your main sync id when using the beta, create a new test sync.

**Comment by mariosadov** [comment]
Could you please add an apk file to assets?

![IMG_20220329_145655](https://user-images.githubusercontent.com/93256729/160605976-7fabef20-0eae-451b-be61-0304a3be449b.jpg)

**Comment by nero120** [comment]
@mariosadov I replaced beta 51 with 52 yesterday, try here:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.52

**Comment by nero120** [comment]
Interesting, Xiaomi devices must not like the cordova plugins being used. It would be extremely helpful to get some debug info as to what is causing the issue, mind if I upload a debug build later for you to try?

**Comment by mariosadov** [comment]
Ok, but before please tell me what my personal info you will get from me with the debug data

**Comment by nero120** [comment]
@mariosadov I've created [this debug release](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.53) for you to try which should print the startup error info to the screen (make sure to uninstall the existing xBrowserSync app before installing this one) (this debug version doesn't do anything besides verify the startup process, no personal data is collected at all).

It will print "Installing..." at the top and then if everything initialises correctly it will print "Done!" as in the screenshot below (the rest of the functionality has been disabled for this debug release). Hopefully on your Xiaomi it will display the error, if you could post a screenshot here that would be extremely useful! 🙏 

![Screenshot_20220325-111354.png](https://user-images.githubusercontent.com/4236238/160110969-b5d4d915-6632-4290-b54e-1a50513022ef.png)

**Comment by olavinto** [comment]
I first installed the latest beta on top of the previous version and it also showed only an empty screen (the frame/background of the UI without content). I uninstalled it and then installed the beta again and it worked. I have a OnePlus device though.

**Comment by nero120** [comment]
> I first installed the latest beta on top of the previous version and it also showed only an empty screen (the frame/background of the UI without content). I uninstalled it and then installed the beta again and it worked. I have a OnePlus device though.

That's a good point, @mariosadov make sure to uninstall xBrowserSync before installing the [debug](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.53) release. If this works (you see "Done!" and no error is displayed) then uninstall the debug build and then try installing the [latest beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.52).

**Comment by mariosadov** [comment]
Installed debug and what it says:

![IMG_20220330_192425](https://user-images.githubusercontent.com/93256729/160884333-9ffef1a6-a283-4734-b9d6-74e65d74b83a.jpg)

Should I still try the latest beta now?

**Comment by nero120** [comment]
> Yes, I deleted the app before, as you asked me. After some time I installed the debug version

Ok thanks for confirming, looks like this is a storage compatibility issue. Will have a think.

**Comment by nero120** [comment]
@mariosadov think I might know what the issue is. I've made a change and created a new debug build:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.54

Would you be able to give it a try please? Remember to uninstall xBrowserSync before installing this build. Thank you!!

**Comment by mariosadov** [comment]
> https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.54

![IMG_20220401_124802](https://user-images.githubusercontent.com/93256729/161239967-02077ea6-cd5e-4707-b901-078324da7213.jpg)

**Comment by nero120** [comment]
Damn. This is very strange. I'm using [BrowserStack](https://www.browserstack.com/) to test using a Xiaomi Note 8 but I can't replicate the issue. I'll try to increase the amount of debug info displayed on the screen when the error occurs so that we can try and get to the root cause. Will provide a new debug build shortly.

**Comment by nero120** [comment]
@mariosadov ok I've added a new debug build that will display details of the trace log that it is attempting to insert into the db, that should help pinpoint at what point during initialisation the error is occurring:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.55

**Comment by nero120** [comment]
@mariosadov ah ha! That's exactly what I needed, thank you! What locale is your device set to?

**Comment by mariosadov** [comment]
> @mariosadov ah ha! That's exactly what I needed, thank you! What locale is your device set to?

You mean device language?

**Comment by nero120** [comment]
Device Language, yes.

**Comment by nero120** [comment]
Ok great, I'll do some testing and get a (hopefully final) debug build uploaded later.

**Comment by mariosadov** [comment]
> Ok great, I'll do some testing and get a (hopefully final) debug build uploaded later.

Thank you very much 🥰

**Comment by nero120** [comment]
@mariosadov I think we've got it this time! I've tested a fix on Xiaomi Note 8 in Ukrainian and it does indeed resolve the issue for me. Try this new debug version, if it works then I'll prep a new beta that includes the fix:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.56

**Comment by mariosadov** [comment]
> https://github.com/xbrowsersync/app/releases/tag/v1.6.0-debug.56

Yay🎉

![IMG_20220404_003337](https://user-images.githubusercontent.com/93256729/161449640-56e768f7-82f5-471b-87c2-837c6b2cde50.jpg)

**Comment by nero120** [comment]
Woop! Will merge the fix into the master branch tomorrow and release a new beta. Many thanks for all your help with this @mariosadov!

**Comment by nero120** [comment]
Here you go @mariosadov:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.57

**Comment by mariosadov** [comment]
> Here you go @mariosadov:
> 
> https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.57

Cool, now camera works)

![IMG_20220404_143735](https://user-images.githubusercontent.com/93256729/161536209-631d5683-4cda-4dc9-bd86-4c28349a5767.jpg)
