### ISSUE TITLE
Sync to Synology NAS using xBrowserSync

### ISSUE THREAD

**Issue by mccart15** [xbrowsersync/app#388]
I have a Synology NAS (Model: ds214sg) on my home network.   Is it possible to use my Synology NAS as the server to sync my bookmarks/favorites rather than using your servers?   If so, can you provide me with some simple instructions on how I would setup xBrowserSync to use my NAS?  I am not a programmer or by no means a computer expert, so the instructions need to be for a layman.

**Comment by nero120** [comment]
I don't have any experience with this NAS, but you need a machine capable of running Docker containers in order to install and run the API. If that NAS supports Docker then theoretically yes, you should be able to run it.
