### ISSUE TITLE
Connection to service lost

### ISSUE THREAD

**Issue by nelson-tamayo** [xbrowsersync/app#391]
1. Happens every time Chrome starts.
2. Only happens on Chrome.
3. Stopped happening after a Chrome reinstall but then started again on its own - no settings changed.
4. Screenshot of error below.
5. Log output attached.
6. I did try disabling the check for updates to no avail.
7. I can see no firewall rules or logs regarding it (and remember it worked for some time after a reinstall).
8. Note that syncing works just fine and that the status displayed on the plugin is nominal. Green/checks (screenshot of that below, too)

![image](https://user-images.githubusercontent.com/8443504/161430535-57aae6c5-eb4b-4af9-8045-1b4c045e7ddd.png)
![image](https://user-images.githubusercontent.com/8443504/161430673-fa7a0f2c-62e2-4b45-ad32-acb8e6b3c189.png)

[xbs_log_20220403092847.txt](https://github.com/xbrowsersync/app/files/8404611/xbs_log_20220403092847.txt)

**Comment by nero120** [comment]
Hi @nelson-tamayo, this issue is fixed in the upcoming v1.6.0 release.
