### ISSUE TITLE
Suddenly lost sync and now no login

### ISSUE THREAD

**Issue by 9784** [xbrowsersync/app#395]
I have saved my encryption password to a password manager. 
When I try to login to brave browser it started showing as invalid credentials or lost sync. I looked at my Android 10.phone and it had same issue. 
Looks like am not able to login to my existing sync ID.
For testing purposes, I had created a new sync ID and it works fine. But I lost all bookmarks saved.
Is there any way to recover the encrypted data , since I do hve the encryption password.

**Comment by nero120** [comment]
Are you definitely using the correct sync id? What service were you syncing to?

If the sync has been removed then the remove data is gone so you won't be able to retrieve it. The only option is to restore a local backup to a new sync.

Also, I know this may be small consolation but the upcoming v1.6.0 release handles missing syncs much better - you get the option of backing up the data when the sync has been removed.

**Comment by 9784** [comment]
100% positive am using the right sync ID and the password, as it's saved to a password manager, and using it, I had also logged in to a couple of devices few weeks ago.
..
I was syncing to
 https://api.xbrowsersync.org/

**Comment by nero120** [comment]
Ok in that case it's possible your sync was removed if you hadn't accessed it in three weeks. The server automatically removes "stale" syncs to make room for new users.

**Comment by 9784** [comment]
Yes. I didn't access it for 3-4 weeks. 
Thank you for your time and clarifying this!
I will be more careful with it now.

**Comment by nero120** [comment]
No problem @9784, v1.6.0 will make life easier I promise!
