### ISSUE TITLE
How To Sync From Firefox Android? 

### ISSUE THREAD

**Issue by Robby9705** [xbrowsersync/app#396]
I Can't Seem To Find An Option For Syncing My Bookmarks From The Firefox Android App To xBrowserSync On My Laptop. I Can Sync Bookmarks From My Laptop To The xBrowserSync App Just Fine. Is The Feature Not Implemented Or Something?

**Comment by nero120** [comment]
xBrowserSync is not available for Firefox for Android as it does not support certain require web extension APIs.
