### ISSUE TITLE
Sync Issue Through xbsapi.cgrx.de NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by itgl72** [xbrowsersync/app#397]
Having issues with sync. Could be just the site itself. Sync is cancelling when trying to connect to xbsapi.cgrx.de. When I try to go to the site directly it shows Your connection isn't private. Attackers might be trying to steal your information from xbsapi.cgrx.de (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID

**Comment by nero120** [comment]
Looks like the SSL certificate has expired for that service. You should stop using it for now. Back up your data, create a new sync on a different service and restore your data to that sync.

I'll try to contact the service admin and ask them to update the cert.

**Comment by itgl72** [comment]
Seems like that was the issue. Resolved now.
