### ISSUE TITLE
Mobile app not syncing

### ISSUE THREAD

**Issue by Roebie** [xbrowsersync/app#398]
**Describe the issue you are experiencing**
**How can the issue be reproduced?**
I have installed mongodb and xbs as a docker stack on my Synology NAS which went smoothly. 
Then, I installed the xbs extension in my Brave browser which uploaded data to my xbs service.
Next, I installed the mobile app on my Android phone and linked it using the qr code. That went well too as all my bookmarks nicely showed up and both the browser and the app showed the same bookmarks in the same folder structure.
Then, I added a subfolder in my browser's bookmarks manager, moved 2 bookmarks from its parent folder into the subfolder and added 1 new bookmark in the subfolder. I suppose the browser extension synced the new information to my service as the data usage amount is now higher than before the change.
However, this subfolder doesn't show up in the mobile app, the moved bookmarks are still in their original spot and the new bookmark is nowhere to be found.
It seems that the mobile app is not syncing.

**Desktop browser**
- OS: Latest Linux Mint
- Browser: Brave (latest version)
- Version: Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit) 

**Mobile device**
- Device: OnePlus 3T
- OS: Android 9
- Version: OxygenOS 9.0.6

**Application log**
Mobile app log attached

[xbs_log_20220502110039.txt](https://github.com/xbrowsersync/app/files/8601887/xbs_log_20220502110039.txt)

**Comment by nero120** [comment]
Try installing the the latest beta on your desktop and mobile:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.62

**Comment by Roebie** [comment]
I have tried to install the apk. At first it seems to being installed, but the procedure ends with the message "app not installed". 
![Screenshot_20220504-224552](https://user-images.githubusercontent.com/2420046/166823099-fa7dc3e6-0956-4775-a9d3-697e3697705c.jpg)

**Comment by nero120** [comment]
Depending on your Android version you might need to grant the app your browser the "install unknown apps" permission:

https://android.gadgethacks.com/how-to/android-101-sideload-apps-by-enabling-unknown-sources-install-unknown-apps-0161947/

**Comment by Roebie** [comment]
Sideloading the app is not the problem. I've done that numerous times before.
Doing it without first removing the Google Play Store installed version apparently is.
Now that I've removed that one completely I was able to install the latest beta.
This one refuses to work without first resyncing with the beta desktop app. I'll do that this evening. I'll keep you posted.

**Comment by nero120** [comment]
Apologies @Roebie yes you're right, the version on the Play Store is signed with a different certificate so if that was already installed then Android would prevent the beta from being installed on top of it.

**Comment by nero120** [comment]
Glad to hear it @Roebie !

Your old sync id will automatically be removed in a few weeks, no need to do anything.
