### ISSUE TITLE
ERROR: Manifest version 2 is deprecated, and support will be removed in 2023.

### ISSUE THREAD

**Issue by bu11etpr00f** [xbrowsersync/app#399]
**Describe the issue you are experiencing**
A clear and concise description of your issue: Error received when loading unpacked Extension: xBrowserSync 1.6.0-beta.61

**How can the issue be reproduced?**

1. Go to 'Extensions'
2. Click on 'Errors'

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: Ubuntu focal
- Browser: Chromium
- Version: 101.0.4951

ERROR REPORT:

`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

{
  "manifest_version": 2,
  "name": "__MSG_App_Title_Default__",
  "description": "__MSG_App_Description_Default__",
  "icons": {
    "48": "assets/icon48.png",
    "128": "assets/icon128.png"
  },
  "default_locale": "en",
  "browser_action": {
    "default_icon": {
      "32": "assets/notsynced.png"
    },
    "default_popup": "app.html",
    "default_title": "__MSG_App_Title_Default__"
  },
  "background": {
    "page": "background.html"
  },
  "commands": {
    "_execute_browser_action": {
      "suggested_key": {
        "default": "Ctrl+Space",
        "mac": "MacCtrl+Space"
      }
    }
  },
  "content_security_policy": "connect-src *; default-src 'none'; font-src 'self' data:; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline';",
  "permissions": [
    "activeTab",
    "alarms",
    "bookmarks",
    "downloads",
    "notifications",
    "storage",
    "tabs",
    "unlimitedStorage"
  ],
  "optional_permissions": [
    "http://*/",
    "https://*/"
  ],
  "incognito": "not_allowed",
  "version": "1.6.0.61",
  "version_name": "1.6.0-beta.61"
}`

**Comment by bu11etpr00f** [comment]
FYI: Extension does work as expected! :)

**Comment by nero120** [comment]
I have migrating background pages to service workers on my to-do list, this will enable both the migration to web extension manifest v3 and PWA support for iOS. Thanks!
