### ISSUE TITLE
New to xbrowseersync Query

### ISSUE THREAD

**Issue by PeterKW** [xbrowsersync/app#405]
This looks interesting, just started digging into the project. 

The version I have installed in Firefox seems to be from 2 years ago (9 Apr 2020). 
Is that the best version to use, seen a lot of commits to the project with bug fixes?
Thank you for the help

**Comment by nero120** [comment]
Hi @PeterKW, it's a good question as I've been working on v1.6.0 for quite a while now! It's a complete code re-write that includes many new features, I am just in the process of final testing before release but as it's such a large change it's been a long slow grind to get to this point with the limited free time I have to devote to the project. If you'd like to try v1.6.0 you can download the latest beta release directly from GitHub [here](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.62).

I'm hoping it won't be too long before I can release v1.6.0 but I can't say when as I've missed too many self-imposed deadlines already!!
