### ISSUE TITLE
is development dead ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [xbrowsersync/app#416]
i just found about this and wanted to use it. but last release was in 2020 . is development dead, is it still safe, can we still use it ?

**Comment by nero120** [comment]
Not dead no, but as I'm the only contributor it very much depends on my free time and lately I've had very little. If you want to use the latest version then grab the latest [beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.62).
