### ISSUE TITLE
"No bookmars found" while the bookmark does exist

### ISSUE THREAD

**Issue by Primokorn** [xbrowsersync/app#418]
**Describe the issue you are experiencing**
I added a bookmark for this URL: **https://github.com/zixpo/candybar**
Name of the bookmark: **GitHub - zixpo/candybar**

When I search for _candybar_, I found no bookmarks.

**How can the issue be reproduced?**
Bookmark the mentioned URL using the same name and try to find it.

**Screenshots**
![Sélection_001](https://user-images.githubusercontent.com/5938828/182120761-808ff644-c27a-4fd8-ba82-e16f64991c8e.png)
![Sélection_002](https://user-images.githubusercontent.com/5938828/182120775-8bb939a5-524b-43a9-827c-6e508ef797db.png)
![Sélection_003](https://user-images.githubusercontent.com/5938828/182120781-29a46c99-1f0f-4d35-b42e-5c262cb31a35.png)

**Desktop browser**
- OS: KDE Neon User Edition x64 5.25 - based on Ubuntu Focal 20.04
- Browser : Firefox 102.0

**Mobile device**
- Device: Oneplus 3T
- OS: Android 11

**Application log**
No available log. I cleared the log then reproduce the problem and I can't download the log file now (the button is greyed out).

Thank you.

**Comment by nero120** [comment]
@Primokorn this issue is fixed in the latest [beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.62).

**Comment by Primokorn** [comment]
OK, I'll wait for the next stable release.
