### ISSUE TITLE
Switch to manifest V3 ?

### ISSUE THREAD

**Issue by BirdInFire** [xbrowsersync/app#423]
I would like to ask the start of switching to manifest V3, by following the migration guide of manifest V3 i have made it work (only the "service worker" (replacement of background page) need a fix because it don't work in this state.

Since the V2 will be removed in chrome in 2023 it's maybe time to switch ?

**Comment by natpicone** [comment]
MarkSync is now live on both stores, built on Manifest V3:

Chrome Web Store: https://chromewebstore.google.com/detail/marksync/ajmlmhlkkindginlgpgeeelnimadgckl
Firefox Add-ons: https://addons.mozilla.org/firefox/addon/marksync/

Source: https://github.com/MarkSyncOrg
Site: https://marksync.org/

See #534 for the full announcement.
