### ISSUE TITLE
Password validation reject options

### ISSUE THREAD

**Issue by fantawttw** [xbrowsersync/app#48]
Relates to #42 
When entering a password the front end currently rejects any password that doesn't match the relevant criteria.

Change the server side to let the client side know, via the json, how to handle such situations.
so for example /info (Not sure if this may be the best place) responds with
`{"maxSyncSize":1048576,"message":"server owner message","status":1,"version":"1.1.4","passwordfail":x}`
where passwordfail's x is say 1 reject, or 0 warn.

The client can then do validation as currently however it can then either **warn** the user that the password doesn't meet criteria or **reject** it.

**Comment by nero120** [comment]
In the upcoming `v1.5.0` release, the password field validation has been updated to resolve the underlying issue. The minimum requirement has been reduced to a single character so xbs does not enforce any particular password requirement, which gives the user control to use whichever password they want. However, the password strength meter is more accurate and it also displays warnings and suggestions to aid the user in choosing a more effective password.

I believe this solution is resolves the issue without requiring more complex interaction between app and api, so I'm going to close this. A beta will be released shortly should you wish to test this before final release.
