### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by Larx** [xBrowserSync/App#5]
Is this project still active? There seem to be no commits since months. I think it would be great to have a software like this, so it would be sad if development had stalled already.

**Comment by nero120** [comment]
You didn't look at branch [v1.3.0](https://github.com/xBrowserSync/App/commits/v1.3.0) did you? :)

I've been working over the past six months to get the mobile apps finished (besides getting married and various other real life distractions!) which are now done and are currently going through the Apple (painful) and Android app review processes. Expect these to be released in the next few weeks and at the same time a significant update to the Chrome extension.

I've also been working on Firefox support which should follow shortly after that.

So don't worry, xBrowserSync is very much still active!

**Comment by Larx** [comment]
Great!
