### ISSUE TITLE
Enhancement: Sync Now 

### ISSUE THREAD

**Issue by Actrack** [xBrowserSync/App#50]
Would be great to have a "Sync Now" option so the user could quickly force a sync event. Useful when working on multiple devices at the same time and you want a new bookmark to sync to the other device quickly.

For example, in Chrome: right-clicking the extension icon could reveal something like:
xBrowserSync //standard
Sync Now //*new enhancement*
Options //currently greyed out but could open the same as the "Setting Gear". *new enhancement*
Remove from Chrome //standard
Hide in Chrome Menu //standard
Remove from Chrome //standard
Manage extensions //standard

Thanks and keep up the great work!

**Comment by nero120** [comment]
Hi @Actrack, thanks for the suggestion. Actually this has already been requested (#21) and is going to be delivered in the next version (v1.4.1). I'll close this issue as the other is tracking the feature but if you have any questions feel free to reply here. 😄

**Comment by Actrack** [comment]
Oops, I searched but somehow missed seeing #21. Great to hear it is being added! :-)
