### ISSUE TITLE
Unable to start a sync 

### ISSUE THREAD

**Issue by javmorin** [xbrowsersync/app#52]
### Steps to reproduce
1. Start a sync with an existing (1.4 updated) sync id and password
2. Confirm acceptance of "clear and rebuild" of bookmarks
3. Leave "Working on it" window up for several minutes

### Expected behaviour
Browser bookmarks are cleared and re-created based on synced data

### Actual behaviour
- Existing bookmarks are all purged
- Browser sits at the  "Working on it" screen for several minutes with no change to bookmarks

### Client app information
**App Platform:** Chrome
**App Platform Version:** 71.0.3578.30 (Official Build) beta (64-bit)

#### Other info
```
This only happens on one of my machines. I have tried removing and re-adding the extension. Clearing the cache. Still will not run. 

I would be happy to debug, but I am not certain how to do so. I see no output on the JS console and I cannot browse through things without the extension window closing (which I wonder if it stops the sync)

```

**Comment by nero120** [comment]
Hi @javmorin, couple of things to try:

1. Just to check, could you try creating a new Chrome profile, install xbs then try syncing to your existing sync ID, does it work successfully?
2. To get an error trace, open the xBrowserSync extension window, go to Settings and enable Debug Mode. Attempt to sync, then when it fails if you browse to chrome://extensions in a new tab, check that Developer mode is enabled, then under xBrowserSync click on `background.html`. In the Console tab you should now see many trace messages. Right click and Save as to save the output, then please email it to admin@xbrowsersync.org and I'll see if I can identify the problem.

**Comment by javmorin** [comment]
@nero120 Thanks for the quick response. It did work without issue in a fresh Chrome profile so I went ahead and did the debug steps as indicated to get the following error message.
```
background.html:1 Unchecked runtime.lastError while running bookmarks.getChildren: Can't find bookmark for id.
    at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2771:34
    at p (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:142:60)
    at Object.clearBookmarks [as Clear] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2769:31)
    at refreshLocalBookmarks (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1996:35)
    at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2305:20
    at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44
    at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185)
```
I can still email the error separately if desired, but as it appears to have no PII, I felt comfortable posting to the issue. Please let me know if I can get you any further debug info.

**Comment by nero120** [comment]
Yes I've seen this before in #40. If you check your Chrome profile folder (should be in `%LOCALAPPDATA%\Google\Chrome\User Data\Default`), open the `Bookmarks` file in a text editor and then search for "Other bookmarks". Does the `id` = "2"?

**Comment by javmorin** [comment]
Ahh.. I see that now. FYI, I am also running on ArchLinux, though as the binary is built by Google for Ubuntu and that is what is used to install on ArchLinux I don't expect that to have any impact on the behavior.

I checked the Bookmarks file for this profile as requested and found it also is not using an id of "2" for the Other bookmarks, it is using "14". I wonder if the id "2" variant was removed in previous re-sync operations? I have restarted xbrowsersync and previous tools a number of times in the past (for new versions, or just new sync ids).  

Here is my Bookmarks file: [Bookmarks.zip](https://github.com/xBrowserSync/App/files/2562933/Bookmarks.zip)

**Comment by nero120** [comment]
> Ahh.. I see that now. FYI, I am also running on ArchLinux, though as the binary is built by Google for Ubuntu and that is what is used to install on ArchLinux I don't expect that to have any impact on the behavior.

Hmm that is interesting that both people who've reported this issue are using ArchLinux, perhaps it is related to the build for that platform?

I've [posted a message to the chromium google group](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/bI1Vmrapbmw) asking about this as I had assumed the ids for the root children should always be constant. If I get some kind of response that indicates this is either not platform related or not a bug, then I'll mark it as a bug here and fix it.

**Comment by nero120** [comment]
@javmorin I'm going to mark this as a bug as I'm currently treating the (root children) bookmark IDs as constants and the fact is they can and do change. I'll need to query for the IDs before attempting to run queries against those bookmarks.

**Comment by nero120** [comment]
After a fair amount of testing and investigation, I'm afraid I have to conclude there's nothing I can do to fix this particular issue.

Since the Chrome extensions API does not provide specific functions for returning the root bookmark containers (other bookmarks and bookmarks bar), they can only be retrieved via querying their properties: id or title. As title changes depending on locale, that leaves only the id as it will always be consistent - or so I had thought until these issues started cropping up.

The cause of why the root bookmark container ids are changing is unknown. The confirmed issues were both reported on ArchLinux so that does suggest a platform-specific Chromium bug but that's just speculation on my part.

I've added better logging in the upcoming v1.5.0 to indentify this issue, but the only resolution will be for the user to either:

1. Modify the `profile/Default/Bookmarks` file for their profile so that `bookmark_bar.id` = `1` and `other.id` = `2` (could inadvertantly corrupt the profile).
2. Create a new Chrome profile.

**Comment by javmorin** [comment]
Appreciate the efforts. I haven't encountered the issue since, so it does seem to be a very specific circumstance that triggers it. Possible it was a bug in a beta build of Google Chrome as well that has been fixed in future versions as well.
