### ISSUE TITLE
I want to translate it into Chinese, but I can't pass the reCAPTCHA. So how to do it?

### ISSUE THREAD

**Issue by linsui** [xBrowserSync/App#54]

**Comment by nero120** [comment]
@linsui I'm not sure I follow... what reCAPTCHA?

If you'd like to volunteer to translate though please email admin@xbrowsersync.org and I'll add you to the translation list.

**Comment by linsui** [comment]
OK. :joy: I mean when I contact you from web I will get (this)[https://formspree.io/admin@xbrowsersync.org]. And I was stuck by the reCAPTCHA.

**Comment by nero120** [comment]
Ah I see! Yes that reminds me I need to build a contact form for the website rather than using formspree but for more spare time... 🙏
