### ISSUE TITLE
Syncing on Firefox does not come to an end

### ISSUE THREAD

**Issue by haslinger** [xBrowserSync/App#55]
### Steps to reproduce
1. Enter the encryption password on Firefox
2. Click Next

### Expected behaviour
Syncing on Firefox should finish (as it does perfectly for me on Chrome).

### Actual behaviour
* Sync shows roughly hard of the bookmarks correctly. 
* The message "working on it, don't close the window" stays for at least 5 mins.
* Web Content and Firefox process have some load, that deceases after several seconds, but I don't see any error messages.
* update: I see an error message, when I start Firefox from the console and I'm interacting with the extension dropdown:
`GLib-GObject-WARNING **: /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f4dd92cb290' of type 'MaiAtkType139'` 

### Client app information
**App Platform:** Firefox 63.0 on Ubuntu 14.04

#### Other info
* I did enable browser history (which was disabled before)
* I did log out from Firefox sync (which I was logged into before)
* Video Download Helper and browserpass-ce are the only other to extensions I have installed
* If there is a way, I could give proper debugging output, I would be happy to share. 
  I am a developer myself, but I have no clue on how to get to the logs of Firefox extensions, if there are any at all.

I would like to state a big **Thank you for your work and time!**, I think that xBrowserSync is a fantastic idea / project.

**Comment by jmseaton** [comment]
I had the same issue.  Seems that the plugin is not gracefully handling invalid bookmarks.  Turn on Debug mode in the settings, start the sync, then go back into settings and you'll see the logs.  I also use chrome, so I had a bookmark for chrome apps (chrome://apps/), and I had a bookmark of an empty tab.  

You'll find the bookmarks in the debug log that it's hanging on, similar to:


    ERROR: Error: Invalid bookmark: {"title":"Apps","type":1,"url":"chrome://apps/","index":0,"parentGuid":"toolbar_____"}
    ERROR: Error: Invalid bookmark: {"title":"New Tab","type":1,"url":"chrome://newtab/","index":27,"parentGuid":"AUnuecY_1k3m"}

**Comment by haslinger** [comment]
@jmseaton thank you very much! 
I had a bookmark to Chrome's sync internals that caused an error and stupid me completely missed the debug mode within the extension itself.

**Comment by nero120** [comment]
Hi guys, sorry I've pre-occupied with new baby and trying to finish the API docker config.

First of all thank you @haslinger for the nice comments! @jmseaton is right there is indeed a bug where bookmark urls valid on one platform (e.g. `chrome://...`) but not valid on a different platform are breaking the sync. Would one of you mind opening a separate issue for this so that we can track it properly please (respond here with the issue id once created). Thank you both!

**Comment by jmseaton** [comment]
Opened https://github.com/xBrowserSync/App/issues/58

**Comment by nero120** [comment]
Thank you @jmseaton!
