### ISSUE TITLE
Platform specific bookmarks break sync

### ISSUE THREAD

**Issue by jmseaton** [xbrowsersync/app#58]
### Steps to reproduce
1. Create a bookmark in chrome to chrome://apps
2. Attempt to start sync in Firefox
3.

### Expected behaviour
Should sync between platforms

### Actual behaviour
Sync hangs on platform specific bookmarks

### Client app information
Chrome, and Firefox

#### Other info
https://github.com/xBrowserSync/App/issues/55

**Comment by nero120** [comment]
Just to let everyone know, this is currently in the process of being fixed. In the meantime, in order to get synced with Firefox, remove any Chrome bookmarks with url starting `chrome://`. Once v1.4.1 is released you can recreate them and they will then sync in Firefox successfully. 😄
