### ISSUE TITLE
Chrome first sync don't download remote bookmark

### ISSUE THREAD

**Issue by FloLaco** [xBrowserSync/App#60]
### Steps to reproduce
1. Create a new Sync on PC1 via Chrome
2. On Mac1, use the previous Sync created (There is 1 folder on my bookmark Mac1) on Chrome

### Expected behaviour
My PC1 bookmarks should appear on Mac1

### Actual behaviour
The Mac1 still have the originate folder and the 2 new folder but I doesn't see any bookmark on these folders

### Client app information
**App Platform:** Chrome

**App Platform Version:**  1.4.0 on both

#### Other info
I also tried : 
1. disable sync on Mac1 and reenable it -> Doesn't not change anything
2. Try to delete my only local bookmark folder present on Mac1 and disable sync on Mac1 and reenable it -> Doesn't not change anything

**Comment by FloLaco** [comment]
I close this issue ... It's a human error. All my bookmark was on toolbar folder and I uncheck this settings.

**Comment by nero120** [comment]
Glad to hear you resolved it @FloLaco! 🥇
