### ISSUE TITLE
URL has already been bookmarked - bug

### ISSUE THREAD

**Issue by cjnaz** [xbrowsersync/app#62]
If a bookmark for a sub-page of a given site exists, and another bookmark is added without the sub-page then the add is rejected with "URL has already been bookmarked".

Also, related, if bookmark xyz.com/hello exists then bookmark xyz.com/hell is rejected as already bookmarked.  Basically, any shorter url of an existing bookmark appears to be rejected.

It seems that if the URL was previously bookmarked and deleted, then that URL, or a shorter one, cannot be bookmarked again.  The app seems to have a history of the bookmark even though it no longer exists.

### Steps to reproduce
1.  Add a bookmark for https://abc.go.com/shows
2.  Add a bookmark for https://abc.go.com/   << this one is rejected.

![image](https://user-images.githubusercontent.com/14854881/49203270-d758cb80-f364-11e8-881b-b8b108962fc0.png)

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Chrome and Android (likely all)

**App Platform Version:** 
1.4.1 beta

**Comment by nero120** [comment]
Confirmed, thanks @cjnaz.

**Comment by tlindsay42** [comment]
Workaround verified in v1.4.0: Insert a character into the base string so that it is no longer matches the parent and then update it again to the desired URL (eg: https://github.com/tlindsay42 -> https://g*r*ithub.com/tlindsay4 -> https://github.com/tlindsay4). 🎉
