### ISSUE TITLE
Browser extension automatically closes on fresh install

### ISSUE THREAD

**Issue by mehronkugler** [xbrowsersync/app#63]
### Steps to reproduce
1. Install the extension
2. Click the icon to open it
3. The extension automatically closes the window

### Expected behaviour
The extension should stay open

### Actual behaviour
The extension window shuts automatically. 

### Client app information
**App Platform:** Firefox 63.0 (64-bit) Ubuntu 18.04.1 LTS

**App Platform Version:** 

#### Other info

I can manage to click on the settings icon in the extension window, and that keeps the window open. I suspect the extension is opening itself, and then trying to create the "Start typing to find bookmarks..." window, and failing to do that for some reason.

I spent a few minutes trying to click "Already have an account" in the window that briefly opens. I managed to finally hit it to get the browser extension window to stay open. I was able to type my account password and then I pressed "tab" to go to the password field and now the extension still closes automatically but now it shows the account/pass page.

Is there some kind of preference I could set in my browser that would clear out xbrowsersync's data?

**Comment by nero120** [comment]
I can't replicate this issue on Firefox 63.0.1 (64-bit) with Ubuntu 18.04.1 LTS. When I install the extension and click on the icon, the window opens fine.

If you remove the extension then any existing data should be delete along with the extension. Can you try doing this and see if that resolves your issue?

**Comment by budbay** [comment]
I was recently having this issue on my laptop with Ubuntu 18.04, with this extension and bitwarden.  after a little digging it seems it was a bug with gnome-shell and password fields.  after updating packages and rebooting the problem is gone.  sorry I don't have the links handy at the moment but try updating, close firefox and reboot.

**Comment by nero120** [comment]
Ah thanks for the insight @budbay!

**Comment by nero120** [comment]
@mehronkugler did @budbay's [comment](https://github.com/xbrowsersync/app/issues/63#issuecomment-452380326) address the issue for you?

**Comment by mehronkugler** [comment]
Hi all. The issue seems to have resolved itself. I did try budbay's steps but those didn't help. I'm able to use xbrowsersync on a fresh install of Firefox and with a fresh install of the plugin without issues. Thanks for looking into this.

**Comment by nero120** [comment]
Great stuff, glad to hear it @mehronkugler!
