### ISSUE TITLE
Support for separators

### ISSUE THREAD

**Issue by iTob191** [xbrowsersync/app#64]
### Type
Feature request

### Expected behaviour
Separators are synchronized if the current browser does support them (e.g. Firefox). If it doesn't, they are ignored.

### Actual behaviour
Synchronizing separators is not supported.
In addition, due to the problem described in #51, existing separators are deleted once sync is enabled.

### Client app information
**App Platform:** Firefox
**App Platform Version:** 64.0

**Comment by nero120** [comment]
Thanks @iTob191, good idea.

**Comment by iTob191** [comment]
Thanks a lot!

**Comment by nero120** [comment]
No worries @iTob191 😄 

I've implemented it so that in Chrome, when you create an empty folder named with three or more dashes ("---") it will be synced in Firefox as a native separator and vice versa.

If you want to try out this functionality @iTob191, the [v1.5.0 beta release](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta2) is available now.

**Comment by iTob191** [comment]
Seems to work fine so far. Thanks again!

One thing that could be improved though, is how those separators look in the bookmarks toolbar in Chrome. Since the toolbar is horizontal, the "------" title doesn't really work to simulate a separator there. I came across https://separator.mayastudios.com/ when searching for how to add separators in chrome. Maybe one could use something similar to implement separators? Top-Level separators in the toolbar could use the vertical version and separators within folders the horizontal one.

**Comment by nero120** [comment]
Very good point @iTob191! 🤔

**Comment by nero120** [comment]
Is this the kind of thing you had in mind @iTob191:

![image](https://user-images.githubusercontent.com/4236238/54516911-3d8b4d80-4958-11e9-9077-c0c9964be755.png)

Not sure if you can hide the folder icon next to the vertical separator in the bookmark bar unfortunately.

**Comment by iTob191** [comment]
Yeah, that already looks far better in the toolbar.

I think the solution of the website I linked above is:
- Vertical separator: Empty bookmark title and the favicon contains the vertical bar
- Horizontal separator: "───────────" as title and a transparent favicon

**Comment by nero120** [comment]
Ah I see, funnily enough those favicons don't work for me for some reason which is why I was a bit confused:

![image](https://user-images.githubusercontent.com/4236238/54529792-da5de300-4978-11e9-9efd-bdfd981752fc.png)

**Comment by iTob191** [comment]
That's strange. For me, they look like this:

### vertical:
![grafik](https://user-images.githubusercontent.com/8921465/54601830-5a02b500-4a40-11e9-8cbc-fd223dc29fca.png)

### horizontal:
![grafik](https://user-images.githubusercontent.com/8921465/54601853-62f38680-4a40-11e9-8c6f-f103e90e9e80.png)

**Comment by nero120** [comment]
@iTob191 I've just uploaded a new version of the [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) which includes updates to the separator functionality on Chrome.

In v1.5.0beta5 on Chrome, you can create a separator by creating a folder named with one or more dashes. This will then be converted to a bookmark whose title will be determined by if it's immediate parent is the bookmarks bar - if so the title will be a vertical bar (`|`), otherwise a long horizontal span of horizontal bars (`─`). Firefox is unchanged and works as per v1.5.0beta4.

I looked into using favicons as per your link but decided against it for the moment. There are a number of issues open in the Chromium bug tracker relating to favicons behaving incorrectly (which might cause confusion for users), plus the ideal solution of being able to set the favicon via the API (rather than having to set the bookmark url to point to a page whose favicon is the one you want to use for the bookmark) has been requested already and will hopefully be implemented soon. Once it is then I can update xBrowserSync to take advantage.

**Comment by iTob191** [comment]
Sorry for the late response. I have some trouble installing the extension in my test environment. Every time I try to install the beta version (`v1.5.0beta5`) in chromium (`Version 73.0.3683.103 (Official Build) Arch Linux (64-bit)`), I get the error message `Package is invalid: 'CRX_HEADER_INVALID'`. Any suggestion how to resolve this?

**Comment by nero120** [comment]
@iTob191 unfortunately you cannot use any version of Google Chrome to install the beta as Google have disabled this ability (because, you know, "security" 🙄). You'll need to install [Chromium](https://chromium.woolyss.com/) (e.g. one of the Marmaduke builds) and install the beta into that.

**Comment by iTob191** [comment]
Tried with the [Marmaduke / ungoogled Archive build](https://github.com/macchrome/winchrome/releases/download/v73.0.3683.103-r625896-Win64/ungoogled-chromium-73.0.3683.103-1_windows.7z) from the page you linked, same error.

**Comment by nero120** [comment]
@iTob191 sorry this was caused by Google changing the way crx files are packaged in v73. I've updated the [beta crx](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta), please re-download and try installing again, should install fine this time.

**Comment by iTob191** [comment]
Installation worked fine with the updated version. 👍 

From the appearance point of view it looks good. I'd still prefer the favicon version once chrome provides an API for it though.

Creating separators in firefox and syncing them to chrome works fine too.
I had some problems the other way round. When renaming a bookmark in chrome to "|" in the toolbar, I get an error:
<details><summary>Error log</summary>

Log was cleared just before renaming.
```
VM50:1 Console was cleared
undefined
background.min.js:1927 onChanged event detected
background.min.js:1927 Sync 4yfkn0 (push) queued (1 waiting to sync)
background.html:1 Unchecked runtime.lastError: Can't find bookmark for id.
background.min.js:1927 Failed to get local bookmark tree at id: 168
background.min.js:1927 Sync 4yfkn0 failed.
background.min.js:1911 bookmarks.sync: Cannot read property 'stack' of undefined TypeError: Cannot read property 'stack' of undefined
    at background.min.js:4277
    at background.min.js:140
    at m.$digest (background.min.js:151)
    at background.min.js:154
    at Tg.completeTask (background.min.js:166)
    at background.min.js:52
(anonymous) @ background.min.js:1911
(anonymous) @ background.min.js:140
$digest @ background.min.js:151
(anonymous) @ background.min.js:154
Tg.completeTask @ background.min.js:166
(anonymous) @ background.min.js:52
setTimeout (async)
Ag.h.defer @ background.min.js:51
$evalAsync @ background.min.js:154
(anonymous) @ background.min.js:137
k @ background.min.js:139
l @ background.min.js:140
h @ background.min.js:140
(anonymous) @ background.min.js:142
(anonymous) @ background.min.js:3732
```

</details>

**Comment by nero120** [comment]
@iTob191 sorry for delay in responding. I've just tried recreating your error but I'm unable to, are you able to recreate it and provide steps?

In Chrome, renaming an existing bookmark to '`|`' will not sync it as a separator (it will appear as a bookmark with title '`|`' in Firefox), you need to create a folder named with dashes (`-`) or pipe (`|`), xBrowserSync will immediately convert this folder to a bookmark with a newtab URL and it will be synced as a separator. However you shouldn't get an error regardless.

**Comment by iTob191** [comment]
Okay, when creating a folder with the name "|" everything does work fine for me. I forgot that one is supposed to create a folder instead of a bookmark.

> In Chrome, renaming an existing bookmark to '|' will not sync it as a separator (it will appear as a bookmark with title '|' in Firefox)

When creating a bookmark (not folder) in chrome with name "|" and URL "chrome://newtab" or "about:newtab" it does actually appear as a separator in Firefox after syncing. Every other URL that I've tested syncs to a normal bookmark though.

Anyway, I can still reproduce the error mentioned above:
![thgfUiiiYg0yDWdWtcKQ](https://user-images.githubusercontent.com/8921465/58559903-5c457480-8224-11e9-96e8-ca5788d3d56a.gif)
I've found that this does only happen for bookmarks with the URLs "chrome://newtab" or "about:newtab". In addition, it does also happen when renaming a folder to "|".

**Comment by nero120** [comment]
Thanks @iTob191! Just duplicated your process using v1.5.0beta6 and I managed to recreate. I suspected I fixed this subsequently after the last beta release and so re-tested using a build of latest source code and the error did not occur. 😄 I'll get another (hopefully final) beta release out this week which will include the fix.

> When creating a bookmark (not folder) in chrome with name "|" and URL "chrome://newtab" or "about:newtab" it does actually appear as a separator in Firefox after syncing. Every other URL that I've tested syncs to a normal bookmark though.

Yes that is indeed expected.

**Comment by nero120** [comment]
Updated the beta to [v1.5.0beta7](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta).

**Comment by iTob191** [comment]
Getting `Package is invalid: 'CRX_HEADER_INVALID'` in Chromium again.

**Comment by nero120** [comment]
If the .crx doesn't work you can use the attached .zip file, just follow the instructions on the release page.

**Comment by iTob191** [comment]
Everything seems to work fine now, thanks!

**Comment by nero120** [comment]
Great stuff, thanks for letting me know @iTob191! 🙇
