### ISSUE TITLE
Can't sync links to pdf files

### ISSUE THREAD

**Issue by qazip** [xbrowsersync/app#66]
Sorry if this is not app-related but I am using firefox and I can't test with other browsers right now.

### Steps to reproduce
1. Go to a page of a pdf file (for example http://simons.hec.utah.edu/NewUndergradBook/Chapter1.pdf)
2. Try to bookmark the page using xbrowsersync
3. Notice that it gives an error "Something went wrong".

### Expected behaviour
One should be able to bookmark pdf links.

### Actual behaviour
"Something went wrong"

### Client app information
Firefox 64.0, on antergos.

**App Platform Version:** 
xbrowsersync 1.4.0

**Comment by nero120** [comment]
Confirmed, thanks @qazip.

**Comment by nero120** [comment]
Resolved in 7ab2652dcc000d06d2e6edb92e56f0fae2e6b72c, release to follow.
