### ISSUE TITLE
Feature to mass delete entries (basically, a list of bookmarks with a delete option)

### ISSUE THREAD

**Issue by qazip** [xbrowsersync/app#67]
This is a feature request. 

It is pretty common to bookmark pages and pages and then it turns out that we never use those pages so the wasted space becomes a problem.. It would be nice if had an option in the GUI to list all entries with a handy delete icon to delete several entries in a fast way.

**Comment by nero120** [comment]
I think I'd rather leave that to the native bookmark manager rather than re-implement it in xBrowserSync, sorry.

**Comment by nero120** [comment]
No worries @qazip! 😄
