### ISSUE TITLE
Adding existing sync for new Firefox Install - Stuck on 'Working on it'

### ISSUE THREAD

**Issue by feerlessleadr** [xbrowsersync/app#70]
### Steps to reproduce
1.Copy sync key from Chrome installation
2.Paste key and input encryption password
3.XBS asks to confirm the deletion of local bookmark data, to which I hit yes, and then it is stuck on 'Working on it'.

### Expected behaviour
local FF bookmarks should be deleted and replaced with those store in the cloud

### Actual behaviour
XBS stays on 'Working on it', regardless of how long I wait.

### Client app information
**App Platform:** Windows 10 Pro - Firefox 64.0.2 (64-bit)

**App Platform Version:** 

#### Other info
```
I figured that something might be screwed up with my FF profile, so I created a fresh one, but have the same result.

Additionally, I figured that something on my work laptop might be blocking this (although XBS through Chrome on my work laptop works without problems), so I tried on a personal Windows 10 Pro computer I have, and have the same result.

I then tried to create a new sync key, w/ a new passphrase, and that works. I then tried to restore my bookmarks manually (backed up via XBS in Chrome) into the new sync ID, and XBS still stays at 'Working on it', no matter how long I wait.
```

**Comment by nero120** [comment]
Hi @feerlessleadr, do you have any Chrome bookmarks with url starting `chrome://`? If so this is [known issue](https://github.com/xbrowsersync/app/issues/58) with v1.4.0. Currently in the process of being fixed.

**Comment by feerlessleadr** [comment]
@nero120 That was exactly my problem! Thanks so much for pointing it out to me, and apologies for missing the known issue.

I've removed the link, and everything syncs perfectly now.

Thanks again for a great extension!

**Comment by nero120** [comment]
Great stuff, glad it's working now! 😄
