### ISSUE TITLE
Error when trying to configure app (Android)

### ISSUE THREAD

**Issue by jerheij** [xbrowsersync/app#71]
### Steps to reproduce
1. Install addon on firefox in android
2. Trying to open configuration of addon

### Expected behaviour
Being able to configure the app and sync bookmarks

### Actual behaviour
I got the error attached in the screenshot

### Client app information
**Phone:** Sony Xperia XZ Premium

**App Platform:** Firefox Beta/Firefox Stable (most updated)

**OS Platform:** Android 9 
![screenshot_xbrowsersync_20190118-143105](https://user-images.githubusercontent.com/14292978/51390428-9349a200-1b2f-11e9-8c7c-a152d6cefeb9.png)

**Comment by nero120** [comment]
Hi @jerheij, Firefox on Android is not supported (and I have no plans to add support in future), use the xBrowserSync app for Android instead (available from the [IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/) or [Play Store](https://play.google.com/store/apps/details?id=com.xBrowserSync.android)).

**Comment by jerheij** [comment]
Sorry for reopening but is there any browser on Android with a supported xBrowserSync extension? I already love the self hosted part of the software but mobile browser sync is a big thing for me.

**Comment by nero120** [comment]
Unfortunately not, I think only Firefox allows web extentions to run in their mobile browser, I know Chrome does not.
