### ISSUE TITLE
Feature Request: Local bookmark sync (without external server)

### ISSUE THREAD

**Issue by Darthagnon** [xbrowsersync/app#72]
Greetings, xBrowserSync.

Thought it might be worth asking - would it be possible for you to implement local machine bookmark sync, without the use of an external server (e.g. via Windows service)? 

I use 3 or so browsers on my PC, and it would be really handy to keep the bookmarks in sync between them; it just seems a bit extraneous to have to sync my bookmarks to an external server and download them again per browser, per bookmark change, when the bookmark files all exist on my PC locally.

[ymarks](https://www.ymarks.org/)([source](https://bitbucket.org/ymarks/ymarks-server)) already implements something similar, involving running an exe-based host on the local machine. I would use ymarks, but am not convinced that it has sufficient redundancy/conflict checks, or code quality, to keep up without losing bookmarks.

**Comment by nero120** [comment]
You can do this very easily by [running a local xBrowserSync service using Docker](https://github.com/xbrowsersync/api#running-with-docker). On the [Docker image](https://hub.docker.com/r/xbrowsersync/api) page, read the info for running a production-ready service in full and you should be able to get it up and running without much difficulty.

If you're only accessing locally, SSL certs are not required so before running `sudo docker-compose up -d`, update the `traefik.toml` file as follows:

```
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[api]
dashboard = false
```

Once it's running, test it by browsing to `http://localhost/` or `http://127.0.0.1/`, if the service appears you can then set the service URL in your xBrowserSync browser clients to point to it.

Hope that helps!
