### ISSUE TITLE
Support browser-specific bookmarks / URL's

### ISSUE THREAD

**Issue by ashrafhadden** [xbrowsersync/app#73]
Browser-specific bookmarks such as `chrome://extensions` result in hanging / freezing on the page where it says "Working on it..."

It would be great if xBrowserSync could handle browser-specific bookmarks in a separate logic which would only import and sync browser-specific URL's if they match the current browser, and simply skip them for browsers that don't match.

### Steps to reproduce
1. Open xBrowserSync in Chrome and make a `Back up`, include a `chrome://extensions` bookmark
2. Open xBrowserSync in Firefox and `Restore` from the backup file

### Expected behaviour
xBrowserSync should be able to properly import, export and sync browser-specific bookmarks

### Actual behaviour
Hanging / freezing on the page where it says "Working on it..."

**Debug log**
```
    INFO: Sync data: {"type":2,"command":1,"deferred":{"promise":{"$$state":{"status":2,"value":{},"processScheduled":false,"pur":true}}}}
    ERROR: Error: Invalid bookmark: {"title":"","type":1,"url":"chrome://extensions","index":18,"parentGuid":"toolbar_____"}
```

### Client app information
- Chrome 71.0.3578.98 (Official Build) (64-bit)
- Firefox 64.0.2 (Official Build) (64-bit)

**Comment by nero120** [comment]
Hi @ashrafhadden, this one's already been reported #58. It will be fixed for the next release.
