### ISSUE TITLE
Firefox extension broken for Version 65.0?

### ISSUE THREAD

**Issue by T3ll1nG** [xbrowsersync/app#76]
### Steps to reproduce
1. install extension on Firefox 65.0 (tried it on Win 10 Pro and Mac OS X)

### Expected behaviour
On clicking the extension the enter password or sign in window should show up.

### Actual behaviour
Upon use instead of the password / sign in you just see the background and half a rectangle and in the background is written {{vm.platform.GetConstant(vm.globals.Constants.Button_Close_Label) }}
### Client app information
**App Platform:** Firefox 

**App Platform Version:** 65.0
![firefoxbug](https://user-images.githubusercontent.com/8617976/52654627-ae22f280-2ef2-11e9-80c9-e4ff90accae5.png)

**Comment by T3ll1nG** [comment]
Seems to have to do something with my changes to the firefox config it does work on a fresh default installation

**Comment by nero120** [comment]
Hi @T3ll1nG, I've just checked this and it works fine for me on Win10. What version of xBrowserSync are you using?

**Comment by nero120** [comment]
> Seems to have to do something with my changes to the firefox config it does work on a fresh default installation

I upgraded FF to 65.0 and my existing xBrowserSync installation worked fine. I then removed it and re-installed from the store, and that also worked fine. Perhaps something with your particular config?

**Comment by T3ll1nG** [comment]
So I found out what breaks the extension. If you disable dom.storage in the config then the extensions shows up like in the picture above.

**Comment by nero120** [comment]
Ah! Ok that will be fixed in v1.4.1, as it is covered by #38.
