### ISSUE TITLE
xBrowserSync ID Save

### ISSUE THREAD

**Issue by candrapersada** [xbrowsersync/app#79]
How to save and load or share xBrowserSync ID to pc, without QR code?

**Comment by nero120** [comment]
Hi @candrapersada, I'm not sure what you mean. You should only be able to create a new sync on your desktop pc browser (chrome or firefox), have you done this already?

**Comment by candrapersada** [comment]
yes but how to copy xBrowserSync ID to pc other without QR code?

**Comment by nero120** [comment]
Ah I see what you are saying. You'd copy it the same way you'd copy any text data between pcs - email, whats app, etc. I quite like using [cl1p.net](https://cl1p.net/) for this purpose.
