### ISSUE TITLE
Receive the error 'Not a valid xBrowserSync service'

### ISSUE THREAD

**Issue by fantawttw** [xbrowsersync/app#80]
### Steps to reproduce
1. Set Service URL to https://xbrowsersync.burrows.xyz

### Expected behaviour
Service should be available and work correctly

### Actual behaviour
Receive the error 'Not a valid xBrowserSync service'
I have temporarily enable logging on the webserver and there appears to be no call to the site
Your own site 'https://www.xbrowsersync.org/' is also showing it is down, however I can see a request from your site to /info and it responds with a 200 code 
It is also returning bookmarks correctly for current users.

### Client app information
Chrome

**App Platform Version:** 1.1.8

#### Other info
There has been no change on my server regarding the service.
I have setup another url https://xbs.25mb.co.uk which points to the same xbrowser webserver and this is working correctly.
SSL certificate is also valid.

Any help resolving the issue would be gratefully received.

**Comment by nero120** [comment]
I can't seem to reproduce this. I've checked your service from both chrome and android xbs v1.4.0 and I can connect and create syncs fine. Can you try from a different network, could be a local issue?

**Comment by fantawttw** [comment]
Hi @nero120,
It seems to have resolved itself. Everything is back to normal must have been a DNS glitch somewhere along the line.
Many thanks
Jon
