### ISSUE TITLE
[v1.5.0beta1] Cannot start using the service

### ISSUE THREAD

**Issue by knu** [xbrowsersync/app#81]
### Steps to reproduce
1. Install the 1.5.0beta1 xpi from the release page (Is it gone by now?)
2. Enter an encryption code twice to start using it

### Expected behaviour
xBrowserSync starts operating sync.

### Actual behaviour
It says something went wrong:

<img width="336" alt="Screenshot 2019-03-13 19 29 54" src="https://user-images.githubusercontent.com/10236/54272134-67deb300-45c6-11e9-9da3-202d496743c2.png">

### Client app information
**App Platform:** (Chrome, Firefox, etc) 
Firefox

**App Platform Version:** 
65.0.1 (64bit)

macOS Mojave 10.14.3

#### Other info
The downloaded log file reads this error:
```
20190313191948124	[trace]	New sync id created: a68abc1405c44f6ab5c48647455b979f
20190313191948460	[trace]	Sync 1vp8kgk (push) queued (1 waiting to sync)
20190313191948973	[error]	bookmarks.sync: menuBookmarksNode is undefined	getLocalContainerIds/<@moz-extension://5793cc21-e9a7-344e-9a3e-8754bb4f3928/js/background.min.js:3542:13 
```

**Comment by knu** [comment]
Changing the service URL does not make any difference, so I suspect this is a problem on the app side.

**Comment by nero120** [comment]
@knu you are fast!! Yep I've removed v1.5.0beta1 as I found a couple of issues (typical), will get v1.5.0beta1 up in the next day or two. Thanks for taking the time to test and raise this! 🙇

**Comment by nero120** [comment]
@knu would you mind running `browser.bookmarks.getTree().then(x => console.log(x));` inside the debug console, then expand the root children and paste a screenshot? i.e.:

![image](https://user-images.githubusercontent.com/4236238/54280425-604fe780-458f-11e9-8bb4-51efba6101c6.png)

I'd like to see the structure you have on your installation and how the bookmark root children differ from mine so that I don't make any incorrect assumptions.

(Just in case you're not aware, you can get to the debug console by browsing to `about:debugging`, then clicking on `debug` under xBrowserSync.)

**Comment by nero120** [comment]
It's ok, reckon I know what the problem is...

**Comment by knu** [comment]
Hmm, I wasn't able to run the debugger; it showed the following error:

```
Browser Toolbox connection status:

Connecting to localhost:58378, ws: false
[Exception... "Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIInputStream.available]"  nsresult: "0x804b000d (NS_ERROR_CONNECTION_REFUSED)"  location: "JS frame :: resource://devtools/shared/security/socket.js :: onInputStreamReady :: line 328"  data: no]
onInputStreamReady@resource://devtools/shared/security/socket.js:328:9
```

😢

**Comment by nero120** [comment]
No worries @knu, I believe I know what the issue is. I'll reply once `v1.5.0beta2` is released which will include the fix.

**Comment by nero120** [comment]
[v1.5.0beta2](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta2) now available, hope this one doesn't fail straight away for you! 🙏

**Comment by knu** [comment]
@nero120 Thanks!  I installed it and it has been working great with support for separators I've long been waiting for!

**Comment by nero120** [comment]
Ah great stuff, glad to hear it!
