### ISSUE TITLE
1.5.0b4 anoying problem :-)

### ISSUE THREAD

**Issue by vsatmydynipnet** [xbrowsersync/app#82]
Hi,

first, thank you so much for this cool software. I just installed b4 on FF ESR latest version. It syncs the separators now, i am more than happy.

There is only one small problem for me:

- create new sync id on sys 1
- save stuff in keepass
- start ff on sys 2
- say have sync id
- copy/paste id into field
- click on keepass to copy password
- now xbrowsersync has closed the popup and loosed the entered id, so unable to copy id and pass :-)

workaround temporary:

- view page source with right click on window
- remove view-source: and reload
- enter in full ff windows the data
- all fine

Greetings!

**Comment by nero120** [comment]
Ah a fellow keepass user! Easy fix my friend, simply go to `about:config` in Firefox and update the `ui.popup.disable_autohide` setting to `true`. Web extension pop up windows will now no longer close when losing focus meaning you can autopaste your xbs creds from keepass into xBrowserSync with ease:

![image](https://user-images.githubusercontent.com/4236238/54622247-2ab07000-4a61-11e9-8f67-c45c17e9e1a3.png)

To close the extension popup, hit the escape key when the popup has focus. Alternatively just change the setting back to `false` when you're done! 😎
