### ISSUE TITLE
[v1.5.0beta] Extension won't install in Chrome

### ISSUE THREAD

**Issue by pauldurham** [xbrowsersync/app#83]
### Steps to reproduce
1.  Downloaded v1.5.0beta5 from https://github.com/xbrowsersync/app/releases/download/v1.5.0beta/xbrowsersync_1.5.0beta5.crx
2. Uninstalled current xBrowserSync v1.4.0
3. Dragged xbrowsersync_1.5.0beta5.crx to Chrome's extensions page
4. Chrome reported:  Package is invalid:  'CRX_Header_invalid'.

### Expected behaviour
Tell us what should happen
I expected the extension to install.

### Actual behaviour
Tell us what happens instead
Extension failed to install.

### Client app information
**App Platform:** (Chrome, Firefox, etc) 
Chrome

**App Platform Version:** 
Version 73.0.3683.86 (Official Build) (64-bit)

#### Other info
```
Win10 Enterprise 64-bit
```

**Comment by nero120** [comment]
Ah yes, Google have disabed the ability to install extensions outside of the Chrome Web Store to, ahem, "protect" users...

If you'd like to test the beta then I recommend grabbing the "ungoogled" archive of Chromium from [here](https://chromium.woolyss.com/). Using this version you should be able to drag the downloaded crx onto the `chrome://extensions` page.
