### ISSUE TITLE
In 1.5.0.beta5 impossible to cut and paste my password from password manager

### ISSUE THREAD

**Issue by ipk01** [xbrowsersync/app#86]
### Steps to reproduce
1. Copy and paste ID from password manager (or other location)
2. Copy password from password manager

### Expected behaviour
Should be able to come back to the identification interface and paste password

### Actual behaviour
Identification interface is gone and opens up again all empty.

### Client app information
Chrome, Firefox, both on Windows and Ubuntu

**App Platform Version:** 

#### Other info
```
This requires that I manually write the password (which is lengthy and cryptic) every time I try to re-connect to the service. This behaviour differs from the regular release version 1.4, where I could copy and paste ID and password from my password manager.
```

**Comment by nero120** [comment]
@ipk01 this issue description is not clear, what do you mean by:

> Should be able to come back to the identification interface and paste password

and

> Identification interface is gone and opens up again all empty.

?

Simply open the extension window, click on the "Already got a sync ID?" link (if both ID and password fields are not visible), then select the field you want to paste into and paste:

![image](https://user-images.githubusercontent.com/4236238/56654836-fd229c00-6688-11e9-80b5-b00133b91e8b.png)

**Comment by ipk01** [comment]
Indeed ... the issues seems to have "gone away" under Windows and works as you suggest, and as one would expect. Under Ubuntu, however, the moment I click into another tab or another window to copy ID or password, the dropdown closes. When I re-open it, both fields are empty again, even although I, i.e., pasted the ID into the upper field before.

**Comment by nero120** [comment]
Ah ok, I'll spin up my ubuntu laptop tonight and try to recreate.

**Comment by nero120** [comment]
Right, it's not a bug but default behaviour for Firefox. Go to `about:config` in Firefox and change the `ui.popup.disable_autohide` setting to `true`. Web extension pop up windows will now no longer close when losing focus meaning you can autopaste your creds from keepass into xBrowserSync with ease:

![image](https://user-images.githubusercontent.com/4236238/56848846-2f303a00-68e5-11e9-8f28-113c9d77b983.png)

To close the extension popup, hit the escape key when the popup has focus. Alternatively just change the setting back to `false` when you're done!

**Comment by dabreese00** [comment]
Same issue here, Firefox on Debian Stretch.  This had me stumped for a while, took a little digging to find this.  Thanks so much for providing the solution.  Just want to bump it for other Firefox Debian/Ubuntu users who might hit the same issue too.

**Comment by nero120** [comment]
Good stuff, glad to hear it @dabreese00!

**Comment by nero120** [comment]
Just to say this is no longer an issue, 660274f9f1dcc4fdac2e3fb757b27d314d5fe4f5 adds saving of the sync ID whenever the field value is updated.
