### ISSUE TITLE
Special characters are garbled after backup/restore cycle

### ISSUE THREAD

**Issue by ipk01** [xbrowsersync/app#88]
### Steps to reproduce
1. Backup Bookmarks with German Umlauts
2. Restore
3. 

### Expected behaviour
"München" should come back as "München"

### Actual behaviour
"München" comes back as "MÃ¼nchen"

### Client app information

**App Platform Version:** 

#### Other info
```
Enter any other information you think would be helpful here.
```

**Comment by ipk01** [comment]
Can not reproduce this behaviour. Please ignore for now.

**Comment by nero120** [comment]
Thanks @ipk01, I have seen your other issues just haven't had a chance to pick them up yet. Bear with me.
