### ISSUE TITLE
[FR] Shortcut to open the extension

### ISSUE THREAD

**Issue by Primokorn** [xBrowserSync/App#9]
### Expected behaviour
Being able to open the search bar from a keyboard shortcut.

### Actual behaviour
We have to open it by clicking on the extension icon.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Inox (Chromium based browser)

**App Platform Version:** 
Manjaro Linux

#### Other info
Inox and Firefox have their own bookmarks and I'm used to pressing CTL + L to go to the URL bar and type the keywords of my bookmarks such as **G+** to get the URL of Google Plus.
Something like CTRL + M for example could open the Xbrowsersync search bar.

Thank you!

**Comment by nero120** [comment]
Hi @Primokorn, you should be able to do this already in a Chromium-based browser. Just go to the Extensions (chrome://extensions/) page and click on the Keyboard Shortcuts link at the bottom, you can then set up a shortcut to open any of your installed extensions:

![image](https://user-images.githubusercontent.com/4236238/34918366-797affda-f949-11e7-9855-b65e8d311cd1.png)

**Comment by Primokorn** [comment]
I didn't know, thanks!

**Comment by Primokorn** [comment]
@nero120 I will also use your extension once available for Firefox.
Do you know how to get the same thing?

**Comment by fllprbt** [comment]
Bumping for FF shortcut change.
