### ISSUE TITLE
Twitter is blocked when adding emojis

### ISSUE THREAD

**Issue by Primokorn** [xbrowsersync/app#90]
### Steps to reproduce
1. Install Brave browser
2. Go to twitter.com and log in
3. Click on the "Add emoji" icon on Twitter when writing a new tweet

### Expected behaviour
Emojis should be added into the tweet.

### Actual behaviour
The tab is frozen/blocked when I open the Emoji popup or click on one emoji.
I have to close the tab and clear browser data to be able to use Twitter again.

### Client app information
**App Platform:** Brave browser 
Xubuntu 18.04

**App Platform Version:** Version 0.63.48 Chromium: 74.0.3729.108 (official buid) (64 bits)

#### Other info
```
Very weird behavior with Brave browser and your extension. It's very strange and I honestly hesitated before creating this issue.

I have 2 laptops. Xubuntu 18.04 and Brave browser are installed on both laptops.
With the laptop A, Xbrowsersync is installed but not on laptop B.

Laptop A: when I click on the "Add emoji" icon on Twitter when writing a new tweet, the tab is frozen and I have to close it, clear browser data to be able to use Twitter again.

Laptop B: no issue at all.

I don't understand how could your extension interfere but I was able to reproduce the problem several times so...
I also uninstalled and reinstalled Brave snap package and reset its settings.
I don't have this problem with Chromium.

What do you think? Which additional information would you need?
Thank you!
```
On a side note, I first tried to send you an email through the contact form of your website but I have never received the activation link from formspree.io...
*This form needs Activation. We've sent you an email containing an 'Activate Form' link. Just click it and your form will be activated!*

**Comment by nero120** [comment]
Hi @Primokorn, unfortunately Brave is not currently supported (if you'd like to submit a separate feature request for this please do!) so I have no idea what could be causing this, nor why one extension would affect another (they should be isolated). Could be a bug in Brave...

> On a side note, I first tried to send you an email through the contact form of your website but I have never received the activation link from formspree.io...
This form needs Activation. We've sent you an email containing an 'Activate Form' link. Just click it and your form will be activated!

The activation email comes to me but it should be activated already. I've just tried to submit a test message using the form and I received it successfully.

**Comment by Primokorn** [comment]
@nero120 Thank you for the answer. I'll check with Brave support.
This kind of service (formspree) doesn't like VPN... It can explain the situation. No email at all on my side (spam folder empty).

**Comment by nero120** [comment]
Formspree is not the best but it does mean I don't have to spend time building a form for the website when I could be putting dev time into xbs! 😄
