### ISSUE TITLE
Download failed. Please check your connection.

### ISSUE THREAD

**Issue by tjerry** [xbrowsersync/app#91]
### Steps to reproduce
1. Run IceCat 60.3.0
2. Go to https://addons.mozilla.org/en-US/firefox/addon/xbs/
3. Add to firefox

### Expected behaviour
Addon installed.

### Actual behaviour
After clicking "Add to Firefox" an error occurs - "Download failed. Please check your connection."

### Client app information
IceCat 60.3.0

#### Other info
Trying to install directly from an xpi file also fails with a message - "The addon downloaded from this site could not be installed because it appears to be corrupt".

Apparently the source of this behavior seems to be explained here - https://github.com/mozilla/addons/issues/851. Something with a manifest file?
Though installing it as a temporary addon works fine.

**Comment by nero120** [comment]
@tjerry xBrowserSync does not support Firefox forks (see the [FAQs](https://www.xbrowsersync.org/#faqs)), though xBrowserSync installs fine from [AMO](https://addons.mozilla.org/en-GB/firefox/addon/xbs/) in latest Firefox (v66.0.3). I can also install the ([beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta)) xpi directly to `about:addons` so I'm going to close this.

Maybe raise a bug request with the IceCat devs?
