### ISSUE TITLE
Skip Bookmarks That Fail to Sync, Instead of Crashing (related to Brave support, possibly Opera & Vivaldi)

### ISSUE THREAD

**Issue by poikilos** [xbrowsersync/app#93]
### Steps to reproduce
1. Sync with Brave
2. Sync with Firefox

### Expected behaviour
The xBrowserSync plugin should either convert or ignore any URL that the web API can store & deliver, then continue to sync bookmarks after that one (Additionally, xBrowserSync should probably not attempt to upload internal hidden URLs not created by the user, such as URLs with the "data" protocol). 

### Actual behaviour
The xBrowserSync plugin stops synchronizing, crashes, and logs out when the web storage contains a URL type not supported by the browser (possibly hidden internal `data:` URLs), rendering the user's web storage on that server permanently inaccessible.
I only have 2 bookmarks in Brave:
```
projects
  - [https://github.com/brave/brave-browser/issues/3991](Bold Styling for GitHub Markdown Does not Work · Issue #3991 · brave/brave-browser)
[https://github.com](GitHub)
```
Log:
```
20190502060915227	[trace]	Installed v1.5.0beta6
20190502060915231	[trace]	Starting up
20190502060915241	[trace]	{"appVersion":"1.5.0beta6","platform":{"name":"firefox","version":"66.0.0","mobile":false,"os":"Fedora"}}
20190502061010407	[trace]	Starting up
20190502061010483	[trace]	{"appVersion":"1.5.0beta6","platform":{"name":"firefox","version":"66.0.0","mobile":false,"os":"Fedora"}}
20190502061122835	[trace]	Sync saiqat (pull) queued (1 waiting to sync)
20190502061123058	[trace]	Failed to create local bookmark: {"parentId":"5Cv_tdN0jxl7","url":"data:"}
20190502061123066	[trace]	Error populating other bookmarks.
20190502061123071	[error]	bookmarks.sync: [10103] FailedCreateLocalBookmarks
20190502061202049	[trace]	Sync pfj2n3 (pull) queued (1 waiting to sync)
20190502061202239	[trace]	Failed to create local bookmark: {"parentId":"bORZdYYlErvZ","url":"data:"}
20190502061202255	[error]	bookmarks.sync: [10103] FailedCreateLocalBookmarks
```

### Client app information
* Firefox 66.0.3 (Chrome, Firefox, etc) 
* Brave Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
* xBrowserSync plugin 1.5.0 beta 6

#### Other info
Originally discovered while diagnosing issue #84

~~Is there some way to erase all web storage in order to alleviate these issues temporarily (clear all then not use other browsers until this issue is resolved)? The permanent inaccessibility of any server I already used is really a drag.~~ I've created a new sync id for use while working around this issue and for further testing.

**Comment by nero120** [comment]
@poikilos I've updated the [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) to include this fix if you'd like to try it.

**Comment by poikilos** [comment]
It works! Sync between Firefox, Brave, and Chromium is perfect (tested with old and new bookmarks).
