### ISSUE TITLE
Provide Chrome Betas in ZIP format Since Chrome No Longer Allows Local crx Installs

### ISSUE THREAD

**Issue by poikilos** [xbrowsersync/app#94]
### Steps to reproduce
1. Download a crx file
2. Drag to extensions page in Chrome

### Expected behaviour
Install.

### Actual behaviour
Chrome prevents install.

### Client app information
Chrome 74.0.3729.131 (Official Build) (64-bit)
on Windows 10

xBrowserSync plugin 1.5.0beta 6 

#### Other info
Chrome no longer allows installing plugins from unknown sources unless unpacked. Even after dragging the crx to the Extensions page in Developer mode and clicking allow, Chrome 74 on Windows 10 (or Brave on Fedora 29) says "Apps, extensions, and user scripts cannot be added from this website." I had to extract the crx with <https://github.com/poikilos/uncrx> which I forked to work with crx version 3 (most other tools that can unpack crx v3 are JavaScript). I also added instructions in the README.md there explaining how to install unsigned extensions.

Distributing the beta plugins (or any other CRX not distributed via the chrome web store) in ZIP format would solve the issue, if you provide the following instructions:
* Save the Chrome extension zip file.
* Open the zip file and click Extract All (in the Compressed Folder Tools tab on Windows) then confirm "Extract" (such as to a new xbrowsersync folder in Downloads).
* Open Chrome
* Click Menu button near the top right, "More options," "Extensions"
* Turn on Developer Mode switch.
* Click the "Load unpacked" button
* Choose the directory you extracted above, such as the main xbrowsersync folder (click once on it then click "Select folder") in Downloads.

**Comment by ipk01** [comment]
My solution: Rename .crx to .zip and it works just fine.

**Comment by poikilos** [comment]
Thanks for getting back to me. I had tried that but it doesn't work with the default zip extraction tool in GNOME (Archive Manager a.k.a. file-roller). Actually it is not supposed to work, because the zip format is preceded by metadata specific to chrome extensions. That is why I forked the program above, renamed it to uncrx, and made it work with crx 3 (most extractors on GitHub and embedded in websites are only able to strip crx 2 headers). If renaming does work without uncrx, then your unzip program is designed to work with nonstandard zip data and to seek to the 32-bit PKxx header that is normally at the beginning of the file. This is not a normal expectation for people making zip programs (and GNOME tends to follow standards minimalistically and not add optional nonstandard features), so releasing zip files would still be the enhancement that is prerequisite for using betas without a debug build of Chrome. You could also link to my program for now if you want (it requires Python).

**Comment by ipk01** [comment]
Re-reading your answer, you say:
"I had tried that but it doesn't work with the default zip ..."
and am not completely sure I understand what you mean.

What I suggested, and what works for me:

Rename the .crx to .zip (i.e. in linux: "mv xbrowsersync_1.5.0beta6.crx xbrowsersync_1.5.0beta6.zip). 
Doing this allows me to drop the file into regular chrome both in windows as on linux.
So 1. not sure where that could have to do with the zip extraction tool, and 2., if any zip extraction tool would work behind the scenes here, whatever I have on Windows or Ubuntu does the trick. no special installs.
Does that make sense?
Ingo

**Comment by ipk01** [comment]
I guess it does not  make any sense that this should work. Hmmm ... right ... But whatever works ... fine with me ... :-)

**Comment by poikilos** [comment]
Ok, yes, dragging does work. I thought you meant rename to ZIP then extract it to a directory, since elsewhere online, "Load unpacked" was the accepted solution to install extensions not on the chrome web store.

**Comment by nero120** [comment]
Guys can you elaborate on how you can add the zip as I'm unable to add the extension in Chrome v74 after renaming the crx to zip. Are you dragging to `chrome://extensions/`? Is Developer Mode enabled? Cheers!

**Comment by ipk01** [comment]
Yes ... your are right ... I just tried .. It does not seem to work anymore. Was probably a bug that they fixed with an update in the last weeks. Grrrrrr...

**Comment by nero120** [comment]
Damn. Ok in that case I think the only easy option is for me to provide a zip as stated in the OP. Will do so when I release the next (and hopefully final) beta this week.

**Comment by nero120** [comment]
I've updated the latest [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) to include a zip file as requested, and will do for all future betas, which you can add using the Load Unpacked option in Chrome.

**Comment by ipk01** [comment]
Installed your latest .zip beta7 on Chrome Version 74.0.3729.169 (Windows) by dragging the .zip into the extensions (developper mode). Not sure why this now works again.

**Comment by nero120** [comment]
@ipk01 you are right! I've removed the .crx and updated the beta release notes to account for this much simpler process.
