### ISSUE TITLE
Date added is not preserved

### ISSUE THREAD

**Issue by tjerry** [xbrowsersync/app#96]
### Steps to reproduce
1. Install addon
2. Start bookmarks sync
3. Open bookmarks manager
4. Check dates

### Expected behaviour
Dates of when bookmarks where created are preserved.

### Actual behaviour
Dates of when bookmarks where created are set to the time of the last sync.

### Client app information
Firefox

Maybe not so important.
However, sometimes I find myself to sort bookmarks by the date added.

**Comment by nero120** [comment]
Hi @tjerry, unfortunately the web extensions API [does not currently support](https://developer.chrome.com/extensions/bookmarks#method-create) adding date information to bookmarks so not much I can do about this, sorry.
