### ISSUE TITLE
[Firefox] The following extensions have no shortcuts

### ISSUE THREAD

**Issue by Primokorn** [xbrowsersync/app#98]
Xubuntu 18.04
Firefox stable 67.0 (64 bits)
Xbrowsersync 1.4.0

Firefox settings > Extensions > Gear icon > Manage extension shortcuts. Is it a new problem from Firefox?
Thanks.

![2019-05-25_16-16](https://user-images.githubusercontent.com/5938828/58370571-74598300-7f08-11e9-8030-c8918e4c65f2.png)

**Comment by nero120** [comment]
Extension keyboard shortcuts are a new addition since Firefox v66. I'll add support for the next release.
